"""Access records for therapies that had no (or thin) location coverage.

Researched regulatory posture by jurisdiction — not clinic-specific marketing claims.
Prices are ESTIMATED midpoints where public ranges exist.
"""
from datetime import date

from .models import (
    LegalStatus as LS,
    OversightQuality as OQ,
    AccessPathway as AP,
    PriceConfidence as PC,
    Confidence as CF,
    Volatility as VL,
)

LV = date(2026, 7, 1)


def R(
    proc,
    jur,
    legal,
    pathway,
    oversight,
    details,
    eligibility,
    providers,
    oversight_notes,
    cost_range,
    cost_notes,
    travel,
    risks,
    summary,
    price=None,
    basis="cash_pay",
    pconf=PC.ESTIMATED,
    conf=CF.MODERATE,
    vol=VL.STABLE,
    sources=None,
):
    return {
        "procedure_id": proc,
        "jurisdiction_id": jur,
        "legal_status": legal,
        "access_pathway": pathway,
        "oversight_quality": oversight,
        "access_pathway_details": details,
        "eligibility_requirements": eligibility,
        "provider_requirements": providers,
        "oversight_notes": oversight_notes,
        "estimated_cost_range_usd": cost_range,
        "cost_notes": cost_notes,
        "residency_travel_notes": travel,
        "risk_notes": risks,
        "arbitrage_summary": summary,
        "price_usd": price,
        "price_basis": basis,
        "price_confidence": pconf if price is not None else PC.UNKNOWN,
        "total_access_cost_usd": price,
        "confidence": conf,
        "volatility": vol,
        "verified_by": "seed_access_expansion_v1",
        "last_verified": LV,
        "sources": sources or [],
    }


S = {
    "zol_fda": {"title": "Zolgensma FDA", "url": "https://www.fda.gov/vaccines-blood-biologics/zolgensma"},
    "zol_ema": {"title": "Zolgensma EMA", "url": "https://www.ema.europa.eu/en/medicines/human/EPAR/zolgensma"},
    "bpc": {"title": "FDA bulk substances safety risks (peptides)", "url": "https://www.fda.gov/drugs/human-drug-compounding/certain-bulk-drug-substances-use-compounding-may-present-significant-safety-risks"},
    "ta1": {"title": "FDA Ta1 bulk substances memo", "url": "https://www.fda.gov/media/183892/download"},
    "ldn": {"title": "LDN Research Trust", "url": "https://ldnresearchtrust.org"},
    "vyleesi": {"title": "Vyleesi FDA", "url": "https://www.accessdata.fda.gov/scripts/cder/daf/"},
    "cannabis": {"title": "Legality of cannabis overview", "url": "https://en.wikipedia.org/wiki/Legality_of_cannabis"},
    "ptcog": {"title": "PTCOG particle therapy facilities", "url": "https://www.ptcog.site"},
    "tame": {"title": "TAME metformin aging trial", "url": "https://clinicaltrials.gov/ct2/show/NCT03294824"},
}


ACCESS_EXPANSION = [
    # ── AAV9 / Zolgensma class ────────────────────────────────────────────
    R("proc-gene-aa9", "jur-us-federal", LS.FULLY_APPROVED, AP.STANDARD_PRESCRIPTION, OQ.HIGH,
      "Zolgensma FDA-approved for SMA <2y; other AAV products (Luxturna, Hemgenix, Elevidys) for labeled uses at qualified centers.",
      "Genetic confirmation; age/weight limits; anti-AAV Ab screen; specialist referral.",
      "Qualified gene-therapy centers; multi-disciplinary teams.",
      "FDA biologics + REMS/registries.",
      "$2.1–3.5M list + hospital", "Payer coverage common on-label; cash inaccessible.",
      "US qualified centers only.", "AAV immune/liver/TMA risks; steroids typical.",
      "US: primary approved market with insurance for labeled SMA.",
      price=2100000, basis="insured", pconf=PC.QUOTED, conf=CF.HIGH, sources=[S["zol_fda"]]),
    R("proc-gene-aa9", "jur-de", LS.FULLY_APPROVED, AP.STANDARD_PRESCRIPTION, OQ.HIGH,
      "EMA full MA for Zolgensma; Germany reimburses eligible SMA via statutory insurance at specialist centers.",
      "EU SMA label; residency/insurance for reimbursement.",
      "University SMA/gene-therapy centers.", "EMA + BfArM/G-BA.",
      "~€2M product", "Public insurance for eligible; not tourism-priced.",
      "EU referral pathways.", "Class AAV risks in tertiary care.",
      "Germany: approved + reimbursed SMA gene therapy, high oversight.",
      price=2000000, basis="insured", conf=CF.HIGH, sources=[S["zol_ema"]]),
    R("proc-gene-aa9", "jur-fr", LS.FULLY_APPROVED, AP.STANDARD_PRESCRIPTION, OQ.HIGH,
      "EMA authorization; France reimburses via HAS/CNAM after assessment (early ATU history).",
      "EU label + national funding criteria.", "Reference neuromuscular centers.", "HAS + ANSM.",
      "~€2M", "Public cover for eligible SMA.", "Residency/insurance linked.", "Class risks.",
      "France: regulated reimbursed pathway, not cash arbitrage.",
      price=2000000, basis="insured", conf=CF.HIGH, sources=[S["zol_ema"]]),
    R("proc-gene-aa9", "jur-uk", LS.FULLY_APPROVED, AP.STANDARD_PRESCRIPTION, OQ.HIGH,
      "MHRA authorization; NHS England/NICE managed access at designated centers.",
      "NICE commissioning criteria.", "NHS specialist centers.", "MHRA + NICE.",
      "Multi-million GBP list", "NHS for eligible; not private tourism market.",
      "UK residents via NHS.", "Class risks.",
      "UK: approved with NHS managed access.",
      price=1900000, basis="insured", conf=CF.HIGH, sources=[S["zol_ema"]]),
    R("proc-gene-aa9", "jur-jp", LS.FULLY_APPROVED, AP.STANDARD_PRESCRIPTION, OQ.HIGH,
      "MHLW approved Zolgensma for SMA under age 2 (incl. pre-symptomatic) at designated hospitals.",
      "Japanese label criteria.", "Designated pediatric centers.", "PMDA/MHLW.",
      "Multi-million JPY", "Public insurance for labeled use.", "Primarily domestic.", "Class risks.",
      "Japan: early non-US approver with strong regulation.",
      price=2000000, basis="insured", conf=CF.HIGH, sources=[S["zol_fda"]]),
    R("proc-gene-aa9", "jur-ca", LS.FULLY_APPROVED, AP.STANDARD_PRESCRIPTION, OQ.HIGH,
      "Health Canada authorized; provincial funding gates vary.",
      "Label + provincial plan approval.", "Pediatric tertiary centers.", "Health Canada + provinces.",
      "CAD multi-million", "Province-by-province delays common.", "Residents.", "Class risks.",
      "Canada: authorized; access rationed by provincial funding.",
      price=2100000, basis="insured", conf=CF.MODERATE, sources=[S["zol_fda"]]),
    R("proc-gene-aa9", "jur-au", LS.FULLY_APPROVED, AP.STANDARD_PRESCRIPTION, OQ.HIGH,
      "TGA approved; PBS/state arrangements for eligible SMA infants.",
      "TGA + PBS criteria.", "Children's hospitals.", "TGA.",
      "AUD multi-million", "Public funding when listed.", "Residents.", "Class risks.",
      "Australia: regulated approved SMA gene therapy.",
      price=2000000, basis="insured", conf=CF.HIGH, sources=[S["zol_fda"]]),
    R("proc-gene-aa9", "jur-br", LS.FULLY_APPROVED, AP.STANDARD_PRESCRIPTION, OQ.MEDIUM,
      "ANVISA authorized; SUS access often via litigation; private cover limited.",
      "Labeled SMA; court orders frequent for SUS.", "Few specialty centers.", "ANVISA; access uneven.",
      "Multi-million USD", "Approval ≠ affordable access.", "Domestic specialty cities.", "Class risks; fewer centers.",
      "Brazil: authorized but cost/courts gate real access.",
      price=2000000, basis="cash_pay", conf=CF.MODERATE, vol=VL.ACTIVE_FLUX, sources=[S["zol_fda"]]),
    R("proc-gene-aa9", "jur-kr", LS.FULLY_APPROVED, AP.STANDARD_PRESCRIPTION, OQ.HIGH,
      "MFDS approved Zolgensma; limited specialty centers; insurance assessment applies.",
      "Korean label + insurer criteria.", "Tertiary hospitals Seoul etc.", "MFDS.",
      "Multi-million KRW/USD equivalent", "National insurance pathways for eligible.", "Domestic.", "Class risks.",
      "South Korea: approved regulated access.",
      price=2000000, basis="insured", conf=CF.MODERATE, sources=[S["zol_fda"]]),

    # ── BPC-157 ───────────────────────────────────────────────────────────
    R("proc-peptide-bpc", "jur-us-federal", LS.PHYSICIAN_DISCRETION_GRAY, AP.NONE, OQ.LOW,
      "Not FDA-approved. FDA has cited significant safety concerns for BPC-157 in compounding (Category 2 history); 2026 PCAC review does not equal authorization to compound. Research-chemical sales are not a medical pathway.",
      "No approved indication.", "No clear legal compounding pathway.", "FDA peptide compounding policy in flux.",
      "N/A legal medical market; illicit $50–200/mo", "Do not treat research vendors as pharmacies.",
      "N/A", "Impurity/immunogenicity concerns; authenticity risk.",
      "US: not approved; compounding not clearly legal — high uncertainty.",
      price=None, conf=CF.MODERATE, vol=VL.ACTIVE_FLUX, sources=[S["bpc"]]),
    R("proc-peptide-bpc", "jur-mx", LS.PHYSICIAN_DISCRETION_GRAY, AP.MEDICAL_TOURISM_CASH, OQ.MINIMAL,
      "Functional/regenerative clinics market BPC-157 cash-pay; no robust national approved-drug pathway.",
      "Cash-pay; clinic screening varies.", "Private clinics Tijuana/Cancún/CDMX.", "Minimal product standards.",
      "$200–1,500/protocol", "Quality opaque.", "Easy US tourism.", "Unverified injectables.",
      "Mexico: easy to find, low oversight.",
      price=600, conf=CF.LOW),
    R("proc-peptide-bpc", "jur-th", LS.PHYSICIAN_DISCRETION_GRAY, AP.MEDICAL_TOURISM_CASH, OQ.MINIMAL,
      "Wellness clinics advertise BPC-class peptides outside a standardized approved pathway.",
      "Tourist packages.", "Bangkok/Phuket clinics.", "Variable Thai FDA enforcement for wellness peptides.",
      "$300–2,000", "Tourism pricing.", "Major tourism hub.", "Authenticity risk.",
      "Thailand: wellness-clinic peptide access, minimal oversight.",
      price=800, conf=CF.LOW),
    R("proc-peptide-bpc", "jur-hn-prospera", LS.UNREGULATED_PERMITTED, AP.LICENSED_PROVIDER_REGIME, OQ.LOW,
      "ZEDE informed-consent model permits peptide protocols restricted under FDA compounding rules.",
      "Consent + ability to pay/travel.", "ZEDE-registered providers.", "Light-touch; ZEDE status contested historically.",
      "$500–3,000", "Experimental cash market.", "Roatán flights.", "Product + infrastructure risk.",
      "Próspera: permissive peptides, low external oversight.",
      price=1200, conf=CF.LOW, vol=VL.ACTIVE_FLUX),
    R("proc-peptide-bpc", "jur-uk", LS.PROHIBITED, AP.NONE, OQ.HIGH,
      "Not MHRA-authorized; unlicensed medicines for human use tightly controlled — no legitimate routine pathway.",
      "None for routine care.", "No authorized product.", "MHRA unlicensed medicines regime.",
      "N/A", "Black market not medical guidance.", "N/A", "Legal + product risk if illicit.",
      "UK: no legitimate medical BPC-157 pathway.",
      price=None, conf=CF.MODERATE, sources=[S["bpc"]]),
    R("proc-peptide-bpc", "jur-au", LS.PROHIBITED, AP.NONE, OQ.HIGH,
      "Not TGA-approved as a medicine; compounding/import for human therapeutic use not a standard lawful pathway.",
      "None standard.", "No registered product.", "TGA medicines framework.",
      "N/A", "Avoid research chemical imports for injection.", "N/A", "Legal/safety risk.",
      "Australia: no approved medical pathway.",
      price=None, conf=CF.MODERATE, sources=[S["bpc"]]),

    # ── Thymosin alpha-1 ──────────────────────────────────────────────────
    R("proc-peptide-thymosin", "jur-us-federal", LS.PHYSICIAN_DISCRETION_GRAY, AP.COMPOUNDING, OQ.MEDIUM,
      "Thymalfasin (Zadaxin) not FDA-approved. FDA: approved in many Asia-Pacific/LatAm/ME/EE countries and historically Italy; US via fluctuating compounding/research channels.",
      "No US labeled indication.", "Compounders when permitted — often restricted.", "No approved US finished drug.",
      "$500–3,000/course", "Higher/less reliable than approved overseas markets.", "Some travel to approved markets.",
      "Quality variability; autoimmune caution.",
      "US: not approved; overseas approved product is the clearer path.",
      price=1200, conf=CF.MODERATE, vol=VL.ACTIVE_FLUX, sources=[S["ta1"]]),
    R("proc-peptide-thymosin", "jur-in", LS.FULLY_APPROVED, AP.STANDARD_PRESCRIPTION, OQ.MEDIUM,
      "Thymalfasin marketed in India for hepatitis/immune uses (Zadaxin/generics where registered).",
      "Local label; physician Rx.", "Hospital/specialty pharmacies.", "CDSCO where registered.",
      "$200–800/course", "Much cheaper than US compounded.", "Medical tourism possible — verify authenticity.",
      "Counterfeit risk — use licensed pharmacies.",
      "India: accessible approved/marketed Ta1 at lower cost.",
      price=400, conf=CF.MODERATE, sources=[S["ta1"]]),
    R("proc-peptide-thymosin", "jur-ph", LS.FULLY_APPROVED, AP.STANDARD_PRESCRIPTION, OQ.MEDIUM,
      "Early Zadaxin market; registered thymalfasin for hepatitis/immune indications where still marketed.",
      "Physician Rx.", "Manila/Cebu pharmacies.", "FDA Philippines.",
      "$250–900/course", "Regional pricing.", "English-friendly medical sector.", "Sourcing quality.",
      "Philippines: historical approved Ta1 market.",
      price=500, conf=CF.MODERATE, sources=[S["ta1"]]),
    R("proc-peptide-thymosin", "jur-sg", LS.FULLY_APPROVED, AP.STANDARD_PRESCRIPTION, OQ.HIGH,
      "Early Asian Zadaxin approval market; high HSA standards for registered products.",
      "Specialist Rx; labeled uses.", "Tertiary hospitals/pharmacies.", "HSA.",
      "$800–2,500/course", "Premium vs India/PH.", "Excellent tourism infrastructure.", "Lower product risk.",
      "Singapore: approved, high oversight, higher price.",
      price=1500, conf=CF.MODERATE, sources=[S["ta1"]]),
    R("proc-peptide-thymosin", "jur-ar", LS.FULLY_APPROVED, AP.STANDARD_PRESCRIPTION, OQ.MEDIUM,
      "Argentina in historical Zadaxin LatAm footprint; ANMAT-registered product where available.",
      "Local label.", "Urban hospital pharmacies.", "ANMAT.",
      "$300–1,200", "Currency-sensitive USD cost.", "Buenos Aires.", "Supply interruptions possible.",
      "Argentina: LatAm approved-market option.",
      price=600, conf=CF.LOW, sources=[S["ta1"]]),
    R("proc-peptide-thymosin", "jur-de", LS.PROHIBITED, AP.NONE, OQ.HIGH,
      "FDA notes Ta1 not generally approved in Europe (Italy historical exception). Germany has no routine authorized Ta1 marketing pathway.",
      "No routine authorized product.", "Named-patient only if any.", "EU marketing authorization required.",
      "N/A", "Unlicensed import exceptional.", "Patients may seek Asia.", "Legal constraints.",
      "Germany/most EU: no routine approved Ta1 access.",
      price=None, conf=CF.MODERATE, sources=[S["ta1"]]),
    R("proc-peptide-thymosin", "jur-mx", LS.PHYSICIAN_DISCRETION_GRAY, AP.MEDICAL_TOURISM_CASH, OQ.LOW,
      "Private clinics may supply Ta1; confirm whether product is registered Zadaxin-class vs unregulated peptide.",
      "Cash-pay.", "Private clinics.", "Variable.",
      "$300–1,500", "Verify registration.", "Tourism.", "Quality risk if unregistered.",
      "Mexico: possible clinic access — verify product registration.",
      price=700, conf=CF.LOW, sources=[S["ta1"]]),

    # ── LDN ───────────────────────────────────────────────────────────────
    R("proc-repurposed-ldn", "jur-us-federal", LS.APPROVED_OFF_LABEL, AP.COMPOUNDING, OQ.MEDIUM,
      "Naltrexone FDA-approved full-dose for OUD/AUD; LDN 0.5–4.5 mg off-label via compounding for inflammatory/autoimmune uses.",
      "Prescriber judgment; no concurrent opioids.", "Licensed Rx + compounding pharmacy.", "State boards; off-label practice.",
      "$30–100/month", "Usually cash-pay; inexpensive.", "Nationwide mail compounders.",
      "Vivid dreams; opioid blockade if acute opioids needed.",
      "US: easy low-cost off-label compounded LDN.",
      price=60, conf=CF.HIGH, sources=[S["ldn"]]),
    R("proc-repurposed-ldn", "jur-uk", LS.APPROVED_OFF_LABEL, AP.COMPOUNDING, OQ.MEDIUM,
      "Licensed naltrexone; LDN private/specials common; rarely NHS-commissioned for autoimmune indications.",
      "Private Rx typical.", "Private GPs/specialists + specials.", "MHRA + GMC off-label guidance.",
      "$40–120/month", "Private pathway dominant.", "Domestic private.", "Standard LDN effects.",
      "UK: private off-label LDN accessible.",
      price=70, conf=CF.MODERATE, sources=[S["ldn"]]),
    R("proc-repurposed-ldn", "jur-ca", LS.APPROVED_OFF_LABEL, AP.COMPOUNDING, OQ.MEDIUM,
      "Off-label LDN via Canadian physicians and compounders.",
      "Physician Rx.", "Family/specialty + compounders.", "Provincial colleges.",
      "CAD $40–100/month", "Often OOP.", "Domestic.", "Standard risks.",
      "Canada: straightforward compounded LDN.",
      price=55, conf=CF.MODERATE, sources=[S["ldn"]]),
    R("proc-repurposed-ldn", "jur-au", LS.APPROVED_OFF_LABEL, AP.COMPOUNDING, OQ.MEDIUM,
      "Compounded LDN with Australian prescriber; not TGA-approved autoimmune indication.",
      "Prescription required.", "GP/specialist + compounder.", "TGA + AHPRA.",
      "AUD $40–120/month", "Cash-pay.", "Domestic.", "Standard.",
      "Australia: off-label compounded LDN available.",
      price=55, conf=CF.MODERATE, sources=[S["ldn"]]),
    R("proc-repurposed-ldn", "jur-de", LS.APPROVED_OFF_LABEL, AP.COMPOUNDING, OQ.MEDIUM,
      "Rezeptur compounding of low-dose naltrexone under physician responsibility.",
      "Ärztliche Verordnung.", "Arzt + Apotheke.", "AMG off-label; high pharmacy quality.",
      "€30–90/month", "Often self-pay.", "Domestic EU.", "Standard.",
      "Germany: high-quality compounded off-label LDN.",
      price=55, conf=CF.MODERATE, sources=[S["ldn"]]),
    R("proc-repurposed-ldn", "jur-nl", LS.APPROVED_OFF_LABEL, AP.COMPOUNDING, OQ.MEDIUM,
      "Off-label LDN via Dutch physicians and apotheek compounding.",
      "Prescription.", "Prescriber + apotheek.", "IGJ medicines framework.",
      "€30–100/month", "Self-pay common.", "Domestic.", "Standard.",
      "Netherlands: accessible off-label LDN.",
      price=55, conf=CF.MODERATE, sources=[S["ldn"]]),

    # ── Methylene blue ────────────────────────────────────────────────────
    R("proc-repurposed-methylene", "jur-us-federal", LS.APPROVED_OFF_LABEL, AP.OFF_LABEL_PRESCRIPTION, OQ.MEDIUM,
      "USP methylene blue FDA-approved for methemoglobinemia; low-dose neuro/mito use off-label. Pharmaceutical grade only.",
      "G6PD screen; caution with serotonergic drugs.", "Prescriber + pharmacy/compounder.", "Approved drug, off-label use.",
      "$50–150/month", "Drug cheap; clinic markups vary.", "Domestic telehealth possible.",
      "Serotonin syndrome risk with SSRIs/MAOIs; G6PD hemolysis.",
      "US: easy pharmaceutical-grade off-label access.",
      price=90, conf=CF.HIGH),
    R("proc-repurposed-methylene", "jur-de", LS.APPROVED_OFF_LABEL, AP.OFF_LABEL_PRESCRIPTION, OQ.HIGH,
      "Methylthioninium chloride authorized for labeled uses; off-label low-dose is physician discretion.",
      "Rx; G6PD check.", "Physicians + pharmacies.", "High EU pharmacy standards.",
      "€40–120/month", "Pharma grade available.", "Domestic.", "Class risks.",
      "Germany: medical-grade available; off-label clinician-led.",
      price=80, conf=CF.MODERATE),
    R("proc-repurposed-methylene", "jur-uk", LS.APPROVED_OFF_LABEL, AP.OFF_LABEL_PRESCRIPTION, OQ.HIGH,
      "Licensed methylthioninium products; off-label low-dose via private clinicians.",
      "Prescription; interaction check.", "Private/NHS as appropriate.", "MHRA licensed product quality.",
      "$50–140/month", "Avoid non-medical dyes.", "Domestic.", "Interactions; G6PD.",
      "UK: medical-grade available.",
      price=85, conf=CF.MODERATE),
    R("proc-repurposed-methylene", "jur-ca", LS.APPROVED_OFF_LABEL, AP.OFF_LABEL_PRESCRIPTION, OQ.MEDIUM,
      "Hospital methemoglobinemia use; compounded low-dose off-label via clinics.",
      "Prescription.", "Physicians + compounders.", "Health Canada framework.",
      "CAD $50–150/month", "Cash-pay off-label.", "Domestic.", "Standard.",
      "Canada: accessible off-label medical-grade.",
      price=80, conf=CF.MODERATE),
    R("proc-repurposed-methylene", "jur-mx", LS.PHYSICIAN_DISCRETION_GRAY, AP.MEDICAL_TOURISM_CASH, OQ.LOW,
      "Wellness clinics offer MB protocols; demand pharmaceutical documentation.",
      "Clinic screening variable.", "Private clinics.", "Less standardized supply.",
      "$40–200", "Cheap; quality risk.", "Border tourism.", "Non-pharma dye substitution danger.",
      "Mexico: available — insist on pharmaceutical grade.",
      price=100, conf=CF.LOW),

    # ── Exosomes ──────────────────────────────────────────────────────────
    R("proc-stem-exosome", "jur-us-federal", LS.CLINICAL_TRIAL_ONLY, AP.CLINICAL_TRIAL_ENROLLMENT, OQ.HIGH,
      "No FDA-approved exosome therapeutic for regenerative use. FDA warns against unapproved clinic products; legitimate path is IND trials.",
      "Trial criteria.", "Trial sites only for compliant use.", "FDA CBER enforcement.",
      "Trial may be free; illegal clinics $2k–20k", "Clinic price ≠ legality.", "Academic sites.",
      "Contamination/immunogenicity; legal risk for unapproved marketing.",
      "US: trials only — avoid illegal clinic marketing.",
      price=None, conf=CF.HIGH, vol=VL.ACTIVE_FLUX),
    R("proc-stem-exosome", "jur-mx", LS.PHYSICIAN_DISCRETION_GRAY, AP.MEDICAL_TOURISM_CASH, OQ.MINIMAL,
      "Widespread cash-pay exosome aesthetics/ortho packages; product characterization inconsistent.",
      "Cash-pay.", "Private regenerative clinics.", "Limited enforcement capacity.",
      "$2,000–15,000", "Opaque packages.", "Tourism hubs.", "Uncharacterized product risk.",
      "Mexico: easy cash access, high product risk.",
      price=6000, conf=CF.LOW),
    R("proc-stem-exosome", "jur-kr", LS.PHYSICIAN_DISCRETION_GRAY, AP.LICENSED_PROVIDER_REGIME, OQ.MEDIUM,
      "Active regenerative/aesthetic EV market under evolving MFDS rules — stronger baseline than LatAm tourism.",
      "Clinic evaluation.", "Licensed clinics/hospitals.", "MFDS facility/product rules.",
      "$3,000–12,000", "Premium tourism.", "Seoul aesthetics hub.", "Still limited hard outcome evidence.",
      "Korea: higher facility standards than pure tourism markets.",
      price=7000, conf=CF.MODERATE),
    R("proc-stem-exosome", "jur-th", LS.PHYSICIAN_DISCRETION_GRAY, AP.MEDICAL_TOURISM_CASH, OQ.MINIMAL,
      "Anti-aging clinics market exosome drips/facials; quality spectrum wide.",
      "Tourist packages.", "Private hospitals/boutiques.", "Variable.",
      "$1,500–10,000", "Cheaper than Korea/UAE.", "Bangkok/Phuket.", "Opaque origin.",
      "Thailand: accessible; diligence required.",
      price=4000, conf=CF.LOW),
    R("proc-stem-exosome", "jur-uae", LS.PHYSICIAN_DISCRETION_GRAY, AP.LICENSED_PROVIDER_REGIME, OQ.MEDIUM,
      "Dubai luxury regenerative clinics under DHA facility licensing; evidence for systemic benefit still weak.",
      "Cash-pay screening.", "DHA-licensed clinics.", "Facility standards high; product evidence thin.",
      "$5,000–20,000", "Luxury pricing.", "Visa-friendly tourism.", "Cost vs evidence mismatch.",
      "UAE: high-end clinic access, better facility oversight.",
      price=10000, conf=CF.LOW),
    R("proc-stem-exosome", "jur-hn-prospera", LS.UNREGULATED_PERMITTED, AP.MEDICAL_TOURISM_CASH, OQ.LOW,
      "ZEDE informed-consent regenerative EV products outside FDA marketing rules.",
      "Consent + pay.", "ZEDE clinics.", "Light touch.",
      "$3,000–15,000", "Experimental.", "Roatán.", "High uncertainty.",
      "Próspera: permissive, low external oversight.",
      price=8000, conf=CF.LOW, vol=VL.ACTIVE_FLUX),

    # ── PT-141 ────────────────────────────────────────────────────────────
    R("proc-pt-141", "jur-us-federal", LS.FULLY_APPROVED, AP.STANDARD_PRESCRIPTION, OQ.HIGH,
      "Vyleesi (bremelanotide) FDA-approved for premenopausal HSDD. Compounded PT-141 used more broadly off-label.",
      "Labeled HSDD evaluation; BP contraindications.", "Prescriber + specialty pharmacy; compounders for PT-141.",
      "Approved Rx drug; compounding separate channel.",
      "Vyleesi high if uninsured; compounded ~$50–150/dose", "Insurance variable for Vyleesi.",
      "Domestic.", "Nausea, flushing, BP changes.",
      "US: approved Vyleesi pathway; compounded cheaper parallel path.",
      price=120, conf=CF.HIGH, sources=[S["vyleesi"]]),
    R("proc-pt-141", "jur-ca", LS.PHYSICIAN_DISCRETION_GRAY, AP.OFF_LABEL_PRESCRIPTION, OQ.MEDIUM,
      "Less straightforward than US Vyleesi retail; specialist/compounding/special access more common.",
      "Sexual medicine assessment.", "Specialists + compounders.", "Health Canada specials/compounding.",
      "$80–200/dose est.", "Private market.", "Domestic.", "BP/nausea; source quality.",
      "Canada: specialist gray/compounding more than open retail.",
      price=140, conf=CF.LOW, sources=[S["vyleesi"]]),
    R("proc-pt-141", "jur-uk", LS.PHYSICIAN_DISCRETION_GRAY, AP.COMPOUNDING, OQ.MEDIUM,
      "Not routine NHS; private sexual medicine may use specials/unlicensed approaches.",
      "Private specialist assessment.", "Private clinics.", "MHRA unlicensed framework.",
      "$100–250/dose est.", "Private.", "Domestic private.", "Unlicensed governance.",
      "UK: private/specialist only.",
      price=160, conf=CF.LOW),
    R("proc-pt-141", "jur-au", LS.PHYSICIAN_DISCRETION_GRAY, AP.COMPOUNDING, OQ.MEDIUM,
      "Private men's/women's health clinics compound PT-141; not PBS standard.",
      "Private Rx.", "Private clinics + compounders.", "TGA compounding rules.",
      "AUD $80–200/dose", "Cash-pay.", "Domestic.", "BP effects.",
      "Australia: private compounded access.",
      price=120, conf=CF.LOW),
    R("proc-pt-141", "jur-mx", LS.PHYSICIAN_DISCRETION_GRAY, AP.MEDICAL_TOURISM_CASH, OQ.LOW,
      "Sexual health clinics offer PT-141 cash-pay.",
      "Clinic screening variable.", "Private clinics.", "Variable product quality.",
      "$40–120/dose", "Lower cost, higher quality risk.", "Tourism.", "Counterfeit peptides.",
      "Mexico: cheap cash access with caveats.",
      price=70, conf=CF.LOW),

    # ── Cryotherapy ───────────────────────────────────────────────────────
    R("proc-cryotherapy", "jur-us-federal", LS.UNREGULATED_PERMITTED, AP.LICENSED_PROVIDER_REGIME, OQ.LOW,
      "WBC as wellness service — not FDA-approved to treat disease. FDA has warned about chamber risks.",
      "Age/CV screening forms at better sites.", "Spas/gyms/recovery studios.", "Commercial, not medical approval.",
      "$75–250/session", "Cash wellness.", "Most metros.", "Frostbite, asphyxiation risk, BP surge.",
      "US: widely available wellness, not medical approval.",
      price=150, conf=CF.MODERATE),
    R("proc-cryotherapy", "jur-de", LS.UNREGULATED_PERMITTED, AP.LICENSED_PROVIDER_REGIME, OQ.MEDIUM,
      "Common in European sports medicine/physio and spa settings.",
      "Screening questionnaires.", "Physio clinics, sports centers.", "Commercial safety standards.",
      "€40–120/session", "Often cheaper than US boutiques.", "Domestic EU.", "Standard cryo risks.",
      "Germany: established sports/wellness cryo.",
      price=80, conf=CF.MODERATE),
    R("proc-cryotherapy", "jur-po", LS.UNREGULATED_PERMITTED, AP.MEDICAL_TOURISM_CASH, OQ.MEDIUM,
      "Dense cryochamber infrastructure in Polish rehab clinics; regional wellness tourism.",
      "Rehab referral or walk-in.", "Rehabilitation centers.", "Medical rehab culture stronger than pure spa.",
      "€20–60/session", "Among lowest EU prices.", "Warsaw/Krakow.", "Standard risks.",
      "Poland: cost-effective EU cryotherapy.",
      price=40, conf=CF.MODERATE),
    R("proc-cryotherapy", "jur-jp", LS.UNREGULATED_PERMITTED, AP.LICENSED_PROVIDER_REGIME, OQ.MEDIUM,
      "Sports/recovery facilities offer cryotherapy as wellness.",
      "Facility screening.", "Sports clinics, hotels.", "Commercial standards.",
      "$80–200/session", "Urban premium.", "Domestic/tourism.", "Standard.",
      "Japan: available recovery wellness service.",
      price=120, conf=CF.LOW),
    R("proc-cryotherapy", "jur-uae", LS.UNREGULATED_PERMITTED, AP.LICENSED_PROVIDER_REGIME, OQ.MEDIUM,
      "Dubai luxury recovery centers widely offer WBC.",
      "Membership/spa intake.", "Luxury gyms/clinics.", "DHA facility licensing where clinic-based.",
      "$100–250/session", "Premium.", "Tourism-friendly.", "Standard.",
      "UAE: luxury cryo widely marketed.",
      price=180, conf=CF.MODERATE),

    # ── PRP ───────────────────────────────────────────────────────────────
    R("proc-prp-therapy", "jur-us-federal", LS.PHYSICIAN_DISCRETION_GRAY, AP.OFF_LABEL_PRESCRIPTION, OQ.MEDIUM,
      "Autologous PRP common in ortho/sports/aesthetics; device kits 510(k). Not drug-approved for OA claims.",
      "Clinic eval; avoid active infection at site.", "Ortho, sports med, derm, PM&R.", "FDA devices + medical boards.",
      "$500–2,000/injection", "Rarely insured elective uses.", "Nationwide.", "Pain, infection; mixed evidence by indication.",
      "US: ubiquitous cash-pay PRP.",
      price=1000, conf=CF.HIGH),
    R("proc-prp-therapy", "jur-de", LS.FULLY_APPROVED, AP.LICENSED_PROVIDER_REGIME, OQ.HIGH,
      "PRP/ACP established in German orthopedics; often private pay.",
      "Specialist assessment.", "Orthopedic clinics.", "High clinical standards.",
      "€300–800/injection", "Often self-pay.", "Domestic EU.", "Standard procedural.",
      "Germany: mainstream orthopedic PRP.",
      price=550, conf=CF.MODERATE),
    R("proc-prp-therapy", "jur-kr", LS.FULLY_APPROVED, AP.LICENSED_PROVIDER_REGIME, OQ.HIGH,
      "Widely used in Korean sports med and aesthetics under medical practice regulation.",
      "Clinic evaluation.", "Hospitals and specialty clinics.", "MFDS/medical law.",
      "$400–1,500/session", "Aesthetics packages common.", "Tourism-ready.", "Standard.",
      "Korea: high-volume quality PRP market.",
      price=800, conf=CF.MODERATE),
    R("proc-prp-therapy", "jur-mx", LS.PHYSICIAN_DISCRETION_GRAY, AP.MEDICAL_TOURISM_CASH, OQ.LOW,
      "Common in Mexican ortho/aesthetic tourism at lower prices.",
      "Cash-pay screening.", "Private clinics.", "Variable sterility.",
      "$200–800/injection", "Savings vs US.", "Border/coastal hubs.", "Infection if technique weak.",
      "Mexico: lower-cost PRP — verify clinic quality.",
      price=400, conf=CF.LOW),
    R("proc-prp-therapy", "jur-th", LS.PHYSICIAN_DISCRETION_GRAY, AP.MEDICAL_TOURISM_CASH, OQ.MEDIUM,
      "Major private hospitals offer PRP for joints/aesthetics.",
      "Hospital evaluation.", "JCI hospitals and clinics.", "Accreditation helps.",
      "$300–1,000", "Package tourism.", "Bangkok connectivity.", "Choose accredited hospitals.",
      "Thailand: PRP in accredited private hospitals.",
      price=550, conf=CF.MODERATE),
    R("proc-prp-therapy", "jur-jp", LS.PHYSICIAN_DISCRETION_GRAY, AP.LICENSED_PROVIDER_REGIME, OQ.HIGH,
      "PRP under Japanese regenerative medicine law depending on processing; many orthopedic clinics offer it.",
      "Clinic protocols per safety act where applicable.", "Licensed clinics/hospitals.", "Structured reporting for some processed products.",
      "$600–2,000", "Higher domestic pricing.", "Primarily domestic.", "Standard.",
      "Japan: regulated clinical environment for PRP-type procedures.",
      price=1200, conf=CF.MODERATE),

    # ── NMN/NR ────────────────────────────────────────────────────────────
    R("proc-nmn-nmad", "jur-us-federal", LS.PHYSICIAN_DISCRETION_GRAY, AP.PERSONAL_IMPORT, OQ.LOW,
      "NR widely sold as dietary supplement. NMN faced FDA exclusion from supplements after drug investigations — market still in flux with ongoing online sales.",
      "Consumer purchase; no disease claims.", "Retailers; some longevity clinics.", "DSHEA vs drug exclusion tension for NMN.",
      "$30–100/month", "Consumer pricing.", "N/A oral.", "Quality variability; limited hard longevity endpoints.",
      "US: NR easy; NMN status turbulent — skepticism warranted.",
      price=60, conf=CF.MODERATE, vol=VL.ACTIVE_FLUX),
    R("proc-nmn-nmad", "jur-jp", LS.UNREGULATED_PERMITTED, AP.STANDARD_PRESCRIPTION, OQ.MEDIUM,
      "Major NMN consumer market with domestic manufacturers; sold as foods/supplements with constrained claims.",
      "Consumer purchase.", "Drugstores and specialty brands.", "MHLW food rules.",
      "$40–120/month", "Premium brands cost more.", "Easy visitor purchase.", "Still limited outcome data.",
      "Japan: mature consumer NMN market.",
      price=70, conf=CF.MODERATE),
    R("proc-nmn-nmad", "jur-de", LS.UNREGULATED_PERMITTED, AP.PERSONAL_IMPORT, OQ.MEDIUM,
      "NAD precursors sold as food supplements; novel-food rules can limit some ingredients by member-state listing.",
      "Consumer purchase where marketed.", "Supplement retail.", "EFSA novel food framework.",
      "€30–100/month", "Brand and compliance dependent.", "EU goods movement where legal.", "Label accuracy; evidence limits.",
      "Germany/EU: supplement channel with novel-food caveats.",
      price=55, conf=CF.LOW),
    R("proc-nmn-nmad", "jur-sg", LS.UNREGULATED_PERMITTED, AP.PERSONAL_IMPORT, OQ.MEDIUM,
      "NAD precursor supplements via regulated retail/import; HSA restricts disease claims.",
      "Consumer.", "Pharmacies and specialty stores.", "HSA advertising rules.",
      "$40–110/month", "Import premiums possible.", "City retail.", "Standard supplement risks.",
      "Singapore: premium supplements available.",
      price=70, conf=CF.LOW),
    R("proc-nmn-nmad", "jur-au", LS.UNREGULATED_PERMITTED, AP.PERSONAL_IMPORT, OQ.MEDIUM,
      "NAD precursors as listed complementary medicines/supplements where ARTG-listed.",
      "Consumer.", "Pharmacies, health stores.", "TGA complementary medicines.",
      "AUD $40–120/month", "Listed products preferred.", "Domestic retail.", "Anti-aging claim limits.",
      "Australia: retail NAD precursors with TGA listing culture.",
      price=55, conf=CF.MODERATE),

    # ── Ayahuasca ─────────────────────────────────────────────────────────
    R("proc-ayahuasca", "jur-br", LS.REGULATED_THERAPY, AP.LICENSED_PROVIDER_REGIME, OQ.MEDIUM,
      "Religious ayahuasca use protected for recognized churches (UDV, Santo Daime, etc.); retreat tourism also exists. Not a medical marketing authorization for depression.",
      "Church membership or retreat screening; psychiatric contraindications apply.", "Religious centers; retreat operators.",
      "Religious freedom framework; not ANVISA drug approval for therapy.",
      "$1,500–5,000 retreats", "Ceremony packages vary.", "Amazon/São Paulo regions; tourism common.",
      "MAOI food/drug interactions; cardiac/psych risk; facilitator quality variable.",
      "Brazil: strongest lawful ceremonial framework globally.",
      price=2500, conf=CF.MODERATE),
    R("proc-ayahuasca", "jur-us-federal", LS.PROHIBITED, AP.NONE, OQ.HIGH,
      "DMT Schedule I federally. Limited RFRA exemptions for specific churches (UDV, Santo Daime branches) — not general public therapy.",
      "Church membership under court-recognized exemptions only.", "Exempt churches only.", "DEA Schedule I + RFRA case law.",
      "N/A general public", "Retreat tourism abroad common among seekers.", "N/A for non-members.",
      "Federal criminal risk outside exemptions.",
      "US federal: prohibited except narrow religious exemptions.",
      price=None, conf=CF.HIGH, vol=VL.STABLE),
    R("proc-ayahuasca", "jur-us-co", LS.DECRIMINALIZED, AP.NONE, OQ.LOW,
      "Prop 122 decriminalized personal possession/use/growing of DMT and listed natural medicines for adults 21+ — not a licensed ayahuasca therapy program or commercial supply.",
      "21+ personal use only; no commercial sales.", "No licensed ceremony centers for ayahuasca under state program (psilocybin centers are separate track).",
      "Decrim without regulated supply chain.",
      "Personal cultivation minimal cost; underground ceremonies variable", "No licensed price discovery.",
      "Any adult in state borders.", "No quality control or medical screening mandate.",
      "Colorado: decrim personal DMT plants — not regulated therapy supply.",
      price=None, conf=CF.MODERATE, vol=VL.ACTIVE_FLUX),
    R("proc-ayahuasca", "jur-nl", LS.PROHIBITED, AP.NONE, OQ.MEDIUM,
      "DMT controlled; ayahuasca ceremonies have faced prosecutions. Not a lawful commercial therapy pathway comparable to truffles.",
      "No licensed pathway.", "Underground risk.", "Opium Act scheduling.",
      "N/A legal market", "Do not confuse with legal psilocybin truffles.", "N/A", "Legal risk.",
      "Netherlands: ayahuasca not a legal therapy market (unlike truffles).",
      price=None, conf=CF.MODERATE),
    R("proc-ayahuasca", "jur-pt", LS.DECRIMINALIZED, AP.NONE, OQ.LOW,
      "Personal drug use decriminalized (administrative), but DMT supply remains controlled — no licensed ayahuasca therapy regime.",
      "Personal use decrim ≠ legal ceremony tourism framework.", "No state licensing for ayahuasca therapy.",
      "Decrim model without medical supply chain.",
      "Underground variable", "Not a regulated product.", "Tourism for 'legal' ayahuasca is misleading.",
      "Still supply-side legal risk; safety unregulated.",
      "Portugal: decrim consumption, not a legal ayahuasca therapy program.",
      price=None, conf=CF.LOW),
    R("proc-ayahuasca", "jur-pe",  # Peru not in list - use Costa Rica / Chile / MX instead
      LS.PHYSICIAN_DISCRETION_GRAY, AP.MEDICAL_TOURISM_CASH, OQ.MINIMAL,
      "placeholder", "x", "x", "x", "x", "x", "x", "x", "x"),
]

# Remove accidental Peru placeholder and wrong entries - rebuild tail cleanly
ACCESS_EXPANSION = [r for r in ACCESS_EXPANSION if r["jurisdiction_id"] != "jur-pe" and r.get("access_pathway_details") != "placeholder"]

ACCESS_EXPANSION += [
    R("proc-ayahuasca", "jur-cr", LS.PHYSICIAN_DISCRETION_GRAY, AP.MEDICAL_TOURISM_CASH, OQ.MINIMAL,
      "Retreat industry operates in gray/informal zones; not a formal medical approval. Facilitator quality highly variable.",
      "Retreat screening variable.", "Retreat operators.", "Little government therapy licensing.",
      "$1,500–4,000", "All-inclusive retreats.", "Tourism-friendly country.", "Drug interactions; remote emergency care.",
      "Costa Rica: retreat tourism exists; unregulated quality.",
      price=2200, conf=CF.LOW),
    R("proc-ayahuasca", "jur-mx", LS.PHYSICIAN_DISCRETION_GRAY, AP.MEDICAL_TOURISM_CASH, OQ.MINIMAL,
      "Some ceremonial retreats operate; federal controlled-substance posture creates legal gray zone for DMT ceremonies.",
      "Retreat screening.", "Retreat operators.", "Inconsistent enforcement.",
      "$1,500–4,500", "Variable.", "Easy US travel.", "Legal + medical risk.",
      "Mexico: retreats exist in gray zone — high diligence required.",
      price=2500, conf=CF.LOW),
    R("proc-ayahuasca", "jur-cl", LS.PHYSICIAN_DISCRETION_GRAY, AP.MEDICAL_TOURISM_CASH, OQ.MINIMAL,
      "Occasional retreat offerings; not a formal approved medical therapy pathway.",
      "Variable.", "Retreat operators.", "Limited formal framework.",
      "$1,500–4,000", "Variable.", "Santiago + south.", "Unregulated facilitation.",
      "Chile: limited retreat presence; not regulated medicine.",
      price=2200, conf=CF.LOW),

    # ── Medical cannabis ──────────────────────────────────────────────────
    R("proc-medical-cannabis", "jur-ca", LS.FULLY_APPROVED, AP.STANDARD_PRESCRIPTION, OQ.HIGH,
      "Federal medical cannabis framework since 2001; adult-use legal 2018. Medical channel via licensed producers and authorized healthcare practitioners.",
      "Medical document from authorized clinician for medical channel; adult-use via retail 18/19+.",
      "Licensed producers; authorized retailers.", "Health Canada Cannabis Act.",
      "$100–300/month medical", "Medical vs recreational pricing differs; insurance rare.",
      "Residents; some visitors use adult-use retail where legal.", "Psychosis risk; impairment; quality better in legal market.",
      "Canada: full federal legal medical + adult-use framework.",
      price=180, conf=CF.HIGH, sources=[S["cannabis"]]),
    R("proc-medical-cannabis", "jur-us-federal", LS.PROHIBITED, AP.NONE, OQ.HIGH,
      "Cannabis Schedule I federally (except hemp ≤0.3% THC and FDA products Epidiolex/Marinol/Syndros). State medical programs conflict with federal law.",
      "State programs only; federal employees/safety-sensitive roles constrained.", "State-licensed dispensaries where legal.",
      "DEA Schedule I vs state laws; 2018 Farm Bill hemp.",
      "$150–400/month state medical", "Federal prohibition blocks many research/banking pathways.",
      "State residency often required for medical cards.", "Federal criminal risk residual; product safer in legal states.",
      "US federal: prohibited — access is state-level only.",
      price=None, conf=CF.HIGH, vol=VL.ACTIVE_FLUX, sources=[S["cannabis"]]),
    R("proc-medical-cannabis", "jur-us-ca", LS.FULLY_APPROVED, AP.LICENSED_PROVIDER_REGIME, OQ.MEDIUM,
      "California medical cannabis long-standing; adult-use Prop 64. Licensed dispensaries under DCC.",
      "21+ adult-use; medical recommendations for tax/possession benefits.", "Licensed dispensaries.", "State DCC; federal conflict remains.",
      "$100–350/month", "Legal market tax-heavy.", "Open to visitors 21+ adult-use.", "Impairment; product labeling helps.",
      "California: mature licensed medical/adult-use market.",
      price=200, conf=CF.HIGH, sources=[S["cannabis"]]),
    R("proc-medical-cannabis", "jur-us-or", LS.FULLY_APPROVED, AP.LICENSED_PROVIDER_REGIME, OQ.MEDIUM,
      "Oregon medical + adult-use licensed system; OLCC regulation.",
      "21+ adult-use; medical card optional benefits.", "Licensed retailers.", "OLCC + OHA medical.",
      "$80–250/month", "Competitive pricing historically.", "Visitors 21+ adult-use.", "Standard cannabis risks.",
      "Oregon: licensed access, relatively low prices.",
      price=150, conf=CF.HIGH, sources=[S["cannabis"]]),
    R("proc-medical-cannabis", "jur-de", LS.FULLY_APPROVED, AP.STANDARD_PRESCRIPTION, OQ.HIGH,
      "Medical cannabis prescription since 2017; 2024 Cannabis Act eased medical prescribing (removed narcotic bureau hurdles) and legalized limited adult home grow/clubs.",
      "Physician prescription for medical; adult rules for personal cultivation/clubs.", "Pharmacies for medical cannabis.",
      "BfArM/medical law + 2024 CanG.",
      "€50–300/month medical", "Insurance may cover severe cases.", "Residents primary.", "Medical product quality high.",
      "Germany: strong medical cannabis pathway; expanding adult rules.",
      price=180, conf=CF.HIGH, vol=VL.ACTIVE_FLUX, sources=[S["cannabis"]]),
    R("proc-medical-cannabis", "jur-uk", LS.FULLY_APPROVED, AP.STANDARD_PRESCRIPTION, OQ.HIGH,
      "Medical cannabis legal since Nov 2018 on specialist prescription; adult-use illegal. Private clinics drive most access.",
      "Specialist Rx after other treatments considered.", "Specialist clinicians; licensed pharmacies.", "MHRA + Home Office.",
      "£150–400/month private", "NHS prescriptions rare; private dominant.", "Residents; private clinics.", "Cost barrier.",
      "UK: medical legal via specialists; NHS access limited.",
      price=280, conf=CF.HIGH, sources=[S["cannabis"]]),
    R("proc-medical-cannabis", "jur-au", LS.FULLY_APPROVED, AP.STANDARD_PRESCRIPTION, OQ.HIGH,
      "Medicinal cannabis via SAS/Authorized Prescriber pathways; pharmacy supply of approved products.",
      "Prescriber authorization; clinical justification.", "Authorized prescribers + pharmacies.", "TGA.",
      "AUD $150–400/month", "Mostly private pay.", "Residents.", "Product regulated.",
      "Australia: regulated medicinal cannabis access.",
      price=220, conf=CF.HIGH, sources=[S["cannabis"]]),
    R("proc-medical-cannabis", "jur-il", LS.FULLY_APPROVED, AP.STANDARD_PRESCRIPTION, OQ.HIGH,
      "Long-standing medical cannabis program with IMCA licenses and pharmacy reform modernization.",
      "Indications list / physician approval.", "Licensed suppliers/pharmacies.", "Ministry of Health.",
      "$100–300/month est.", "Program maturing toward pharmacy model.", "Residents.", "Regulated product.",
      "Israel: mature medical cannabis program.",
      price=180, conf=CF.MODERATE, sources=[S["cannabis"]]),
    R("proc-medical-cannabis", "jur-th", LS.FULLY_APPROVED, AP.LICENSED_PROVIDER_REGIME, OQ.MEDIUM,
      "First Asian medical cannabis legalization; policy has oscillated on recreational vs medical focus — medical pathway remains but rules evolve.",
      "Medical indications under Thai FDA rules; tourist access limited/changing.", "Licensed clinics/hospitals.",
      "Thai FDA; active policy flux.",
      "$80–250/month est.", "Policy changes affect retail.", "Tourism rules unstable.", "Verify current possession rules before travel.",
      "Thailand: medical pathway exists; rules in flux — verify before travel.",
      price=150, conf=CF.LOW, vol=VL.ACTIVE_FLUX, sources=[S["cannabis"]]),
    R("proc-medical-cannabis", "jur-nl", LS.FULLY_APPROVED, AP.STANDARD_PRESCRIPTION, OQ.MEDIUM,
      "Pharmacy medical cannabis (Bedrocan etc.) on prescription; coffee-shop cannabis is tolerated retail for adults, not medical system.",
      "Physician Rx for pharmacy medical cannabis.", "Pharmacies for medical; coffee shops for recreational tolerance.",
      "OPM/IGJ medical; gedoogbeleid recreational.",
      "€50–200/month medical", "Medical quality standardized via pharmacy channel.", "Residents for medical Rx.", "Don't conflate coffee shop with medical.",
      "Netherlands: true medical pharmacy pathway + separate tolerance retail.",
      price=120, conf=CF.HIGH, sources=[S["cannabis"]]),
    R("proc-medical-cannabis", "jur-es", LS.PHYSICIAN_DISCRETION_GRAY, AP.OFF_LABEL_PRESCRIPTION, OQ.MEDIUM,
      "Cannabinoid medicines limited; private consumption clubs in some regions; full medical program less developed than DE/UK.",
      "Specialist situations; regional variation.", "Limited pharmacy products; clubs informal.", "Regional enforcement varies.",
      "Variable", "Clubs not equivalent to medical program.", "Tourism to clubs carries legal nuance.", "Legal uncertainty outside clubs/private use.",
      "Spain: private use/clubs culture; weaker formal medical program.",
      price=None, conf=CF.LOW, sources=[S["cannabis"]]),
    R("proc-medical-cannabis", "jur-sg", LS.PROHIBITED, AP.NONE, OQ.HIGH,
      "Strict drug laws; cannabis possession harshly penalized. No medical cannabis program for general patients.",
      "None.", "None.", "Misuse of Drugs Act — severe penalties.",
      "N/A", "N/A", "Do not travel with cannabis products.", "Severe legal risk.",
      "Singapore: prohibited — zero practical access.",
      price=None, conf=CF.HIGH, sources=[S["cannabis"]]),

    # ── Ozone ─────────────────────────────────────────────────────────────
    R("proc-ozone-therapy", "jur-us-federal", LS.PROHIBITED, AP.NONE, OQ.HIGH,
      "FDA has stated ozone is a toxic gas with no known useful medical application in specific therapy and has taken action against fraudulent ozone devices/claims.",
      "No approved medical ozone therapy pathway.", "Not legitimate standard care.", "FDA enforcement against medical ozone claims.",
      "N/A legitimate", "Cash clinics still advertise illicitly.", "N/A", "Pulmonary toxicity, embolism risk with direct IV ozone.",
      "US: FDA-hostile — not a legitimate approved therapy.",
      price=None, conf=CF.HIGH),
    R("proc-ozone-therapy", "jur-de", LS.PHYSICIAN_DISCRETION_GRAY, AP.OFF_LABEL_PRESCRIPTION, OQ.MEDIUM,
      "Ozone therapy has a longer complementary-medicine tradition in German-speaking countries under physician practice; not equivalent to mainstream guideline care.",
      "Physician discretion; not standard insurance benefit usually.", "Some complementary MDs.", "Medical practice acts; evidence contested.",
      "€50–150/session", "Usually self-pay.", "Domestic.", "Embolism risk if improperly administered; oxidative injury.",
      "Germany: complementary physician practice exists; evidence remains contested.",
      price=100, conf=CF.MODERATE),
    R("proc-ozone-therapy", "jur-ch", LS.PHYSICIAN_DISCRETION_GRAY, AP.OFF_LABEL_PRESCRIPTION, OQ.MEDIUM,
      "Complementary/integrative clinics may offer ozone under medical practice rules.",
      "Private pay.", "Integrative physicians.", "Cantonal medical oversight.",
      "CHF 80–200/session", "Self-pay.", "Residency not required for private care.", "Technique-dependent risks.",
      "Switzerland: private complementary ozone available.",
      price=140, conf=CF.LOW),
    R("proc-ozone-therapy", "jur-mx", LS.PHYSICIAN_DISCRETION_GRAY, AP.MEDICAL_TOURISM_CASH, OQ.MINIMAL,
      "Common in Mexican alternative clinics; quality and sterility highly variable.",
      "Cash-pay.", "Alternative clinics.", "Minimal standards.",
      "$50–150/session", "Cheap packages.", "Tourism.", "High technique risk.",
      "Mexico: widely offered alternative therapy — high risk of poor technique.",
      price=90, conf=CF.LOW),
    R("proc-ozone-therapy", "jur-tu", LS.PHYSICIAN_DISCRETION_GRAY, AP.MEDICAL_TOURISM_CASH, OQ.LOW,
      "Offered in some Turkish complementary/medical tourism packages.",
      "Clinic packages.", "Private clinics.", "Variable.",
      "$40–120/session", "Tourism pricing.", "Istanbul medical tourism.", "Technique risk.",
      "Turkey: available in tourism clinics; diligence required.",
      price=70, conf=CF.LOW),

    # ── Neural stem cells ─────────────────────────────────────────────────
    R("proc-stem-nsc", "jur-us-federal", LS.CLINICAL_TRIAL_ONLY, AP.CLINICAL_TRIAL_ENROLLMENT, OQ.HIGH,
      "No FDA-approved NSC therapy for Parkinson's/ALS/SCI routine care. Access via registered clinical trials only.",
      "Trial inclusion criteria.", "Academic trial sites.", "FDA IND framework.",
      "Trial may cover costs; offshore $50k–200k+", "Offshore is not FDA-approved care.", "Trial travel.",
      "Tumorigenicity, immune rejection, procedure risk.",
      "US: clinical trials only for NSC therapies.",
      price=None, conf=CF.HIGH),
    R("proc-stem-nsc", "jur-jp", LS.CLINICAL_TRIAL_ONLY, AP.CLINICAL_TRIAL_ENROLLMENT, OQ.HIGH,
      "Japan's regenerative medicine law enables conditional approval pathways and hospital-based regenerative offerings; true NSC products remain largely investigational/conditional.",
      "Protocol eligibility under regenerative medicine act.", "Licensed regenerative hospitals.", "PMDA + regenerative act.",
      "$50,000–200,000+ if private regenerative protocols", "Not standard insurance for experimental NSC.", "Medical travel possible to research hospitals.",
      "Experimental risks.",
      "Japan: structured regenerative framework but NSC still largely experimental.",
      price=100000, conf=CF.LOW, vol=VL.ACTIVE_FLUX),
    R("proc-stem-nsc", "jur-mx", LS.PHYSICIAN_DISCRETION_GRAY, AP.MEDICAL_TOURISM_CASH, OQ.MINIMAL,
      "Some clinics market 'neural stem cell' packages with weak characterization — high scam risk.",
      "Cash-pay nearly open.", "Private clinics.", "Minimal verification of cell identity.",
      "$15,000–80,000 marketed", "Marketing claims often unsupported.", "Tourism.", "Very high risk of unproven product.",
      "Mexico: marketed NSC tourism is high-risk — prefer trials.",
      price=40000, conf=CF.LOW),
    R("proc-stem-nsc", "jur-cn",  # China not in list - skip
      LS.CLINICAL_TRIAL_ONLY, AP.CLINICAL_TRIAL_ENROLLMENT, OQ.MEDIUM,
      "placeholder", "x", "x", "x", "x", "x", "x", "x", "x"),
]

ACCESS_EXPANSION = [r for r in ACCESS_EXPANSION if r["jurisdiction_id"] != "jur-cn" and r.get("access_pathway_details") != "placeholder"]

ACCESS_EXPANSION += [
    R("proc-stem-nsc", "jur-kr", LS.CLINICAL_TRIAL_ONLY, AP.CLINICAL_TRIAL_ENROLLMENT, OQ.HIGH,
      "Advanced regenerative research; patient access mainly via trials/hospital protocols under MFDS.",
      "Protocol eligibility.", "Research hospitals.", "MFDS.",
      "Trial or high private cost", "Not routine care.", "Seoul research hospitals.", "Experimental risks.",
      "Korea: research/trial pathway, not routine NSC therapy.",
      price=None, conf=CF.MODERATE),
    R("proc-stem-nsc", "jur-hn-prospera", LS.UNREGULATED_PERMITTED, AP.MEDICAL_TOURISM_CASH, OQ.LOW,
      "ZEDE could host experimental neural regenerative protocols under informed consent.",
      "Consent + pay.", "ZEDE clinics.", "Minimal external review.",
      "$50,000–150,000 est.", "Experimental pricing.", "Roatán.", "Extreme uncertainty.",
      "Próspera: theoretical experimental access only — extreme caution.",
      price=80000, conf=CF.LOW, vol=VL.ACTIVE_FLUX),

    # ── Proton therapy ────────────────────────────────────────────────────
    R("proc-proton-therapy", "jur-us-federal", LS.FULLY_APPROVED, AP.STANDARD_PRESCRIPTION, OQ.HIGH,
      "FDA-cleared proton systems; ~40+ US centers. Insurance coverage indication-dependent (pediatric, certain CNS/base-of-skull favored).",
      "Oncology referral; insurance prior auth often required.", "PTCOG-listed proton centers.", "FDA devices + ASTRO/payer policies.",
      "$50,000–300,000+/course", "Insured when authorized; cash extreme.", "Multi-week stay near center.", "Radiation toxicities lower for some OARs but not risk-free.",
      "US: approved, limited centers, insurance-gated.",
      price=120000, basis="insured", conf=CF.HIGH, sources=[S["ptcog"]]),
    R("proc-proton-therapy", "jur-de", LS.FULLY_APPROVED, AP.STANDARD_PRESCRIPTION, OQ.HIGH,
      "Multiple German proton/particle centers; statutory insurance for accepted indications.",
      "Multidisciplinary tumor board.", "Particle therapy centers.", "G-BA/indication rules.",
      "Public cover when indicated; private otherwise high", "Indication list matters.", "EU patients via referral.", "Standard RT risks reduced for some sites.",
      "Germany: strong European particle-therapy capacity.",
      price=100000, basis="insured", conf=CF.HIGH, sources=[S["ptcog"]]),
    R("proc-proton-therapy", "jur-jp", LS.FULLY_APPROVED, AP.STANDARD_PRESCRIPTION, OQ.HIGH,
      "Japan among world leaders in particle therapy center density; national insurance for selected indications.",
      "Oncology referral; indication criteria.", "Hospital proton/carbon centers.", "MHLW.",
      "Insurance for approved indications; private higher", "High technology access.", "Domestic/medical travel.", "Standard.",
      "Japan: excellent particle therapy infrastructure.",
      price=90000, basis="insured", conf=CF.HIGH, sources=[S["ptcog"]]),
    R("proc-proton-therapy", "jur-kr", LS.FULLY_APPROVED, AP.STANDARD_PRESCRIPTION, OQ.HIGH,
      "Korean proton centers (e.g. NCC, major hospitals) with national insurance for selected cancers.",
      "Oncology referral.", "Hospital proton facilities.", "MFDS/HIRA.",
      "Insurance-eligible cases lower OOP", "Medical tourism for some indications.", "Seoul hubs.", "Standard.",
      "Korea: approved proton capacity with insurance pathways.",
      price=85000, basis="insured", conf=CF.MODERATE, sources=[S["ptcog"]]),
    R("proc-proton-therapy", "jur-uk", LS.FULLY_APPROVED, AP.STANDARD_PRESCRIPTION, OQ.HIGH,
      "NHS proton centers (e.g. Christie, UCLH) for approved indications especially pediatric; private options limited.",
      "NHS national MDT selection.", "NHS proton centers.", "NICE/NHSE commissioning.",
      "NHS covered when selected; private very high", "Capacity constrained.", "UK residents primary.", "Standard.",
      "UK: NHS proton for selected cases — capacity-limited.",
      price=0, basis="insured", pconf=PC.ESTIMATED, conf=CF.HIGH, sources=[S["ptcog"]]),
    R("proc-proton-therapy", "jur-ch", LS.FULLY_APPROVED, AP.STANDARD_PRESCRIPTION, OQ.HIGH,
      "Paul Scherrer Institute and other Swiss particle expertise; insurance for accepted indications.",
      "Specialist referral.", "PSI/hospital centers.", "Swissmedic/cantonal.",
      "High if private/out-of-network", "Premium system.", "Some international referrals.", "Standard.",
      "Switzerland: high-quality particle therapy access.",
      price=110000, basis="insured", conf=CF.MODERATE, sources=[S["ptcog"]]),

    # ── Senolytics D+Q ────────────────────────────────────────────────────
    R("proc-senolytics", "jur-us-federal", LS.APPROVED_OFF_LABEL, AP.OFF_LABEL_PRESCRIPTION, OQ.MEDIUM,
      "Dasatinib FDA-approved for CML; quercetin OTC. Combined intermittent 'D+Q' senolytic protocols are off-label longevity clinic practice; not an approved aging indication.",
      "Physician screening; avoid active infection/surgery windows; cancer history caution.",
      "Longevity/functional clinicians; oncology awareness for dasatinib.", "Off-label prescribing of approved drug + supplement.",
      "$50–150/course drug cost", "Clinic fees extra $200–500.", "Domestic telehealth longevity platforms.",
      "Cytopenias, bleeding, infection risk from dasatinib; drug interactions.",
      "US: off-label D+Q via longevity clinics — experimental intent.",
      price=100, conf=CF.MODERATE, vol=VL.ACTIVE_FLUX),
    R("proc-senolytics", "jur-uk", LS.APPROVED_OFF_LABEL, AP.OFF_LABEL_PRESCRIPTION, OQ.MEDIUM,
      "Dasatinib licensed for oncology; private off-label senolytic use uncommon/not NHS.",
      "Private specialist only if at all.", "Private clinicians.", "MHRA licensed dasatinib; off-label private.",
      "$80–200/course est.", "Not standard care.", "Domestic private.", "Oncology-drug risks.",
      "UK: possible private off-label only; not established pathway.",
      price=120, conf=CF.LOW),
    R("proc-senolytics", "jur-ca", LS.APPROVED_OFF_LABEL, AP.OFF_LABEL_PRESCRIPTION, OQ.MEDIUM,
      "Dasatinib available; off-label longevity D+Q via private clinics/telehealth similar to US.",
      "Physician screening.", "Private longevity clinicians.", "Provincial practice standards.",
      "CAD $50–180/course", "Clinic fees extra.", "Domestic.", "Dasatinib risks.",
      "Canada: off-label private longevity use possible.",
      price=100, conf=CF.LOW),
    R("proc-senolytics", "jur-mx", LS.PHYSICIAN_DISCRETION_GRAY, AP.MEDICAL_TOURISM_CASH, OQ.LOW,
      "Longevity clinics may offer senolytic packages including dasatinib combinations.",
      "Cash-pay screening variable.", "Private clinics.", "Variable monitoring.",
      "$100–400/package", "Monitoring may be inadequate.", "Tourism.", "Insufficient labs/follow-up risk.",
      "Mexico: cash longevity packages — ensure lab monitoring.",
      price=200, conf=CF.LOW),

    # ── Chelation ─────────────────────────────────────────────────────────
    R("proc-chelation", "jur-us-federal", LS.APPROVED_OFF_LABEL, AP.OFF_LABEL_PRESCRIPTION, OQ.MEDIUM,
      "EDTA/others FDA-approved for heavy metal poisoning. Off-label 'detox'/CVD chelation is controversial; TACT trial mixed; cardiology societies caution.",
      "Documented metal toxicity for labeled use; off-label requires informed consent.",
      "Medical toxicology for labeled; some integrative clinics off-label.", "FDA labels vs off-label practice.",
      "$100–300/infusion; courses $2k–10k+", "Insurance for labeled toxicity only.", "Domestic.",
      "Hypocalcemia, renal injury, arrhythmia — must monitor electrolytes.",
      "US: approved for metal poisoning; off-label detox controversial.",
      price=200, conf=CF.MODERATE),
    R("proc-chelation", "jur-mx", LS.PHYSICIAN_DISCRETION_GRAY, AP.MEDICAL_TOURISM_CASH, OQ.MINIMAL,
      "Alternative clinics market chelation for many unproven indications.",
      "Cash-pay; indication gating weak.", "Alternative clinics.", "Minimal.",
      "$80–200/infusion", "Cheap packages.", "Tourism.", "Electrolyte catastrophe if poorly monitored.",
      "Mexico: widely marketed — high risk if not medically supervised for true toxicity.",
      price=120, conf=CF.LOW),
    R("proc-chelation", "jur-de", LS.APPROVED_OFF_LABEL, AP.OFF_LABEL_PRESCRIPTION, OQ.HIGH,
      "Chelators available for documented metal intoxication in medical settings; off-label CVD use less mainstream than US integrative clinics.",
      "Laboratory-confirmed toxicity preferred.", "Hospitals/toxicology.", "High medical standards.",
      "€100–250/session when used", "Insurance for true poisoning.", "Domestic.", "Requires monitoring.",
      "Germany: legitimate toxicology use; off-label less promoted.",
      price=180, conf=CF.MODERATE),
    R("proc-chelation", "jur-th", LS.PHYSICIAN_DISCRETION_GRAY, AP.MEDICAL_TOURISM_CASH, OQ.LOW,
      "Wellness hospitals may offer chelation packages.",
      "Package screening.", "Private hospitals.", "Variable indication discipline.",
      "$80–220/session", "Tourism packages.", "Bangkok.", "Monitoring quality varies.",
      "Thailand: available in wellness packages — insist on labs.",
      price=140, conf=CF.LOW),

    # ── Metformin longevity ───────────────────────────────────────────────
    R("proc-metformin-longevity", "jur-us-federal", LS.APPROVED_OFF_LABEL, AP.OFF_LABEL_PRESCRIPTION, OQ.MEDIUM,
      "Metformin FDA-approved for T2D; longevity/off-label metabolic use common via primary care and longevity clinics. TAME trial designed to test aging outcomes.",
      "eGFR checks; B12 monitoring; not for advanced CKD.", "Any licensed prescriber.", "Standard off-label of approved drug.",
      "$10–30/month generic", "Extremely cheap; sometimes insurance only for diabetes.", "Domestic/telehealth.",
      "GI effects; rare lactic acidosis; hold for contrast procedures.",
      "US: easiest cheap off-label longevity small molecule.",
      price=20, conf=CF.HIGH, sources=[S["tame"]]),
    R("proc-metformin-longevity", "jur-uk", LS.APPROVED_OFF_LABEL, AP.OFF_LABEL_PRESCRIPTION, OQ.MEDIUM,
      "Licensed for diabetes; private off-label longevity prescribing possible; NHS primarily diabetes.",
      "Private GP/specialist for non-diabetes use.", "GPs; private clinics.", "MHRA licensed drug.",
      "$10–25/month", "NHS for diabetes; private for longevity intent.", "Domestic.", "Standard metformin risks.",
      "UK: drug available; longevity use mostly private.",
      price=18, conf=CF.MODERATE, sources=[S["tame"]]),
    R("proc-metformin-longevity", "jur-ca", LS.APPROVED_OFF_LABEL, AP.OFF_LABEL_PRESCRIPTION, OQ.MEDIUM,
      "Widely prescribed diabetes drug; off-label longevity via physicians.",
      "Renal function screening.", "Family physicians.", "Provincial formularies for diabetes.",
      "CAD $10–25/month", "Covered for diabetes; OOP possible off-label.", "Domestic.", "Standard risks.",
      "Canada: easy access, cheap generic.",
      price=15, conf=CF.HIGH, sources=[S["tame"]]),
    R("proc-metformin-longevity", "jur-de", LS.APPROVED_OFF_LABEL, AP.OFF_LABEL_PRESCRIPTION, OQ.HIGH,
      "Metformin standard diabetes therapy; off-label preventive use is physician discretion, less consumer-longevity-marketed than US.",
      "Physician assessment; renal function.", "Hausarzt/specialist.", "AMG; high standards.",
      "€5–20/month", "Very cheap generic.", "Domestic.", "Standard risks.",
      "Germany: ubiquitous diabetes drug; off-label prevention possible.",
      price=12, conf=CF.HIGH, sources=[S["tame"]]),
    R("proc-metformin-longevity", "jur-au", LS.APPROVED_OFF_LABEL, AP.OFF_LABEL_PRESCRIPTION, OQ.MEDIUM,
      "PBS-listed for diabetes; private off-label longevity scripts available.",
      "Prescriber assessment.", "GPs.", "TGA/PBS.",
      "AUD $10–25/month", "PBS for diabetes indications.", "Domestic.", "Standard risks.",
      "Australia: cheap access via GP.",
      price=15, conf=CF.HIGH, sources=[S["tame"]]),
    R("proc-metformin-longevity", "jur-in", LS.APPROVED_OFF_LABEL, AP.STANDARD_PRESCRIPTION, OQ.MEDIUM,
      "Metformin widely manufactured/available for diabetes; off-label easy and very low cost.",
      "Basic clinical screening recommended.", "Any physician; pharmacies.", "CDSCO generics market.",
      "$3–10/month", "Among world's lowest prices.", "Easy visitor pharmacy access with Rx norms varying.", "Quality: prefer known manufacturers.",
      "India: ultra-low-cost metformin access.",
      price=5, conf=CF.HIGH, sources=[S["tame"]]),
    R("proc-metformin-longevity", "jur-mx", LS.APPROVED_OFF_LABEL, AP.STANDARD_PRESCRIPTION, OQ.MEDIUM,
      "Metformin widely available for diabetes; pharmacies accessible; off-label longevity use possible.",
      "Basic screening advised.", "Physicians; farmacias.", "COFEPRIS generics.",
      "$5–15/month", "Very cheap.", "Border pharmacy tourism common.", "Prefer reputable pharmacies.",
      "Mexico: cheap generic access.",
      price=8, conf=CF.HIGH, sources=[S["tame"]]),
]


def all_expansion_records():
    """Return expansion list (deduped by procedure×jurisdiction)."""
    seen = set()
    out = []
    for r in ACCESS_EXPANSION:
        key = (r["procedure_id"], r["jurisdiction_id"])
        if key in seen:
            continue
        seen.add(key)
        out.append(r)
    return out
