"""Additional therapies + disease labels + starter access rows.

Keeps the main seed.py list stable while growing coverage. Seed inserts any
missing procedure IDs without wiping existing data.
"""
from datetime import date

from .models import (
    Modality,
    RegulatoryModality,
    RestrictionDriver,
    LegalStatus as LS,
    OversightQuality as OQ,
    AccessPathway as AP,
    PriceConfidence as PC,
    Confidence as CF,
    Volatility as VL,
    EvidenceGrade,
)

LV = date(2026, 7, 1)


def R(proc, jur, legal, pathway, oversight, details, eligibility, providers,
      oversight_notes, cost_range, cost_notes, travel, risks, summary,
      price=None, basis="cash_pay", pconf=PC.ESTIMATED, conf=CF.MODERATE,
      vol=VL.STABLE, sources=None):
    return {
        "procedure_id": proc,
        "jurisdiction_id": jur,
        "legal_status": legal,
        "access_pathway": pathway,
        "oversight_quality": oversight,
        "access_pathway_details": details,
        "eligibility_requirements": eligibility,
        "provider_requirements": providers,
        "oversight_notes": oversight_notes,
        "estimated_cost_range_usd": cost_range,
        "cost_notes": cost_notes,
        "residency_travel_notes": travel,
        "risk_notes": risks,
        "arbitrage_summary": summary,
        "price_usd": price,
        "price_basis": basis,
        "price_confidence": pconf if price is not None else PC.UNKNOWN,
        "total_access_cost_usd": price,
        "confidence": conf,
        "volatility": vol,
        "verified_by": "seed_therapies_expansion_v1",
        "last_verified": LV,
        "sources": sources or [],
    }


# ── New procedures ──────────────────────────────────────────────────────────

PROCEDURES_EXPANSION = [
    {
        "id": "proc-tms-depression",
        "name": "Transcranial Magnetic Stimulation (TMS) for Depression",
        "modality": Modality.REPURPOSED,
        "subcategory": "Neuromodulation",
        "therapeutic_areas": ["Mental_Health", "Depression"],
        "description": "Noninvasive repetitive TMS (including deep TMS, iTBS) for treatment-resistant depression. FDA-cleared devices; widely covered when criteria met. Expanding off-label: OCD, smoking cessation, anxiety.",
        "typical_us_cost_range": "$6,000–15,000 per acute course (often insured)",
        "indications": "TRD after failed antidepressants; device-specific labels for OCD and other indications.",
        "sources": [{"title": "FDA TMS devices", "url": "https://www.fda.gov"}],
    },
    {
        "id": "proc-tms-ocd",
        "name": "Deep TMS / TMS for Obsessive-Compulsive Disorder",
        "modality": Modality.REPURPOSED,
        "subcategory": "Neuromodulation",
        "therapeutic_areas": ["Mental_Health", "OCD"],
        "description": "TMS protocols cleared for OCD (e.g. deep TMS H7 coil). Adjunct when SSRIs/ERP incomplete.",
        "typical_us_cost_range": "$8,000–18,000 per course",
        "indications": "OCD with inadequate response to standard care.",
        "sources": [{"title": "FDA OCD TMS clearance", "url": "https://www.fda.gov"}],
    },
    {
        "id": "proc-vns-depression",
        "name": "Vagus Nerve Stimulation (VNS) for Depression",
        "modality": Modality.REPURPOSED,
        "subcategory": "Neuromodulation Implant",
        "therapeutic_areas": ["Mental_Health", "Depression"],
        "description": "Implanted or transcutaneous VNS for chronic TRD. Implantable VNS has long FDA history for epilepsy and depression; noninvasive tVNS growing.",
        "typical_us_cost_range": "$20,000–40,000 implant pathway; tVNS devices lower",
        "indications": "Chronic TRD; epilepsy (separate labels).",
        "sources": [{"title": "FDA VNS depression", "url": "https://www.fda.gov"}],
    },
    {
        "id": "proc-dbs-parkinson",
        "name": "Deep Brain Stimulation (DBS) for Parkinson's Disease",
        "modality": Modality.REPURPOSED,
        "subcategory": "Neuromodulation Implant",
        "therapeutic_areas": ["Neurology", "Movement_Disorders"],
        "description": "Stereotactic implantation of electrodes in STN/GPi for advanced Parkinson's motor complications. Established in high-income systems; access limited by neurosurgery capacity and cost.",
        "typical_us_cost_range": "$50,000–100,000+ (device + surgery + programming)",
        "indications": "Idiopathic PD with motor fluctuations/dyskinesia on optimized meds; screening for cognitive/psych exclusions.",
        "sources": [{"title": "AAN DBS guidance", "url": "https://www.aan.com"}],
    },
    {
        "id": "proc-fus-tremor",
        "name": "MR-Guided Focused Ultrasound for Essential Tremor / PD Tremor",
        "modality": Modality.REPURPOSED,
        "subcategory": "Incisionless Ablation",
        "therapeutic_areas": ["Neurology", "Movement_Disorders"],
        "description": "Incisionless thalamotomy using high-intensity focused ultrasound under MRI guidance. FDA-approved for essential tremor and PD tremor in selected patients.",
        "typical_us_cost_range": "$30,000–60,000",
        "indications": "Medication-refractory essential tremor or PD tremor; unilateral typical first treatment.",
        "sources": [{"title": "FDA MRgFUS", "url": "https://www.fda.gov"}],
    },
    {
        "id": "proc-til-melanoma",
        "name": "Tumor-Infiltrating Lymphocyte (TIL) Therapy for Melanoma",
        "modality": Modality.ONCOLOGY,
        "regulatory_modality": RegulatoryModality.CELL_THERAPY_AUTOLOGOUS,
        "restriction_driver": RestrictionDriver.COST_OR_LICENSING,
        "subcategory": "Cell Therapy Autologous",
        "therapeutic_areas": ["Oncology", "Melanoma"],
        "description": "Autologous TILs expanded ex vivo then reinfused after lymphodepletion (e.g. lifileucel/Amtagvi). One-time cellular immunotherapy for advanced melanoma after checkpoint failure.",
        "typical_us_cost_range": "$500,000+ (product + hospitalization)",
        "indications": "Unresectable/metastatic melanoma after anti-PD-1 (label-specific).",
        "sources": [{"title": "Amtagvi FDA", "url": "https://www.fda.gov"}],
    },
    {
        "id": "proc-car-t-solid",
        "name": "Experimental CAR-T / TCR Therapy for Solid Tumors",
        "modality": Modality.ONCOLOGY,
        "regulatory_modality": RegulatoryModality.CELL_THERAPY_AUTOLOGOUS,
        "restriction_driver": RestrictionDriver.SAFETY_UNPROVEN,
        "subcategory": "Cell Therapy Experimental",
        "therapeutic_areas": ["Oncology"],
        "description": "Investigational CAR-T/TCR products targeting solid tumors (e.g. Claudin18.2, GD2, mesothelin). Almost exclusively clinical trial or limited special-access pathways.",
        "typical_us_cost_range": "Trial (often free drug) or $100,000–500,000+ private",
        "indications": "Advanced solid tumors on trial protocols only in most jurisdictions.",
        "sources": [{"title": "ClinicalTrials.gov CAR-T solid", "url": "https://clinicaltrials.gov"}],
    },
    {
        "id": "proc-dendritic-vaccine",
        "name": "Dendritic Cell Cancer Vaccines (Personalized)",
        "modality": Modality.ONCOLOGY,
        "regulatory_modality": RegulatoryModality.CELL_THERAPY_AUTOLOGOUS,
        "restriction_driver": RestrictionDriver.SAFETY_UNPROVEN,
        "subcategory": "Cellular Immunotherapy",
        "therapeutic_areas": ["Oncology"],
        "description": "Autologous dendritic cells pulsed with tumor antigens. Sipuleucel-T is approved for prostate; many other DC vaccines marketed in less regulated clinics (quality highly variable).",
        "typical_us_cost_range": "$50,000–150,000+ (clinic packages vary widely)",
        "indications": "Sipuleucel-T: mCRPC. Off-label/clinic DC vaccines: various solid tumors (evidence variable).",
        "sources": [{"title": "Provenge FDA", "url": "https://www.fda.gov"}],
    },
    {
        "id": "proc-apheresis-longcovid",
        "name": "Therapeutic Apheresis / HELP Apheresis for Long COVID & Microclot Protocols",
        "modality": Modality.CELLULAR,
        "subcategory": "Blood Product Apheresis",
        "therapeutic_areas": ["Long_COVID", "Cardiovascular"],
        "description": "Plasmapheresis, immunoadsorption, or heparin-induced extracorporeal LDL precipitation (HELP) used experimentally for post-acute COVID syndromes and microclot hypotheses. Evidence still evolving; not standard of care in most systems.",
        "typical_us_cost_range": "$2,000–8,000 per session; courses $10,000–40,000",
        "indications": "Investigational long COVID / ME-like syndromes; established uses exist for other apheresis indications (e.g. hyperviscosity, autoimmune).",
        "sources": [{"title": "ASFA apheresis guidelines", "url": "https://www.apheresis.org"}],
    },
    {
        "id": "proc-ivig",
        "name": "Intravenous Immunoglobulin (IVIG) for Autoimmune / Neuroimmune Disease",
        "modality": Modality.REPURPOSED,
        "subcategory": "Blood Product",
        "therapeutic_areas": ["Autoimmune", "Neurology", "Immunology"],
        "description": "Pooled IgG replacement/immunomodulation. Labeled for PID, ITP, CIDP, Kawasaki, etc.; widely used off-label (myositis, stiff-person, some long COVID clinics).",
        "typical_us_cost_range": "$5,000–15,000 per infusion cycle (weight-based)",
        "indications": "Labeled immunodeficiency and selected autoimmune neuropathies; extensive off-label neuroimmune use.",
        "sources": [{"title": "FDA IVIG products", "url": "https://www.fda.gov"}],
    },
    {
        "id": "proc-sglt2-hf",
        "name": "SGLT2 Inhibitors for Heart Failure & CKD Beyond Diabetes",
        "modality": Modality.REPURPOSED,
        "subcategory": "Metabolic / Cardiorenal",
        "therapeutic_areas": ["Cardiovascular", "Kidney"],
        "description": "Dapagliflozin, empagliflozin and related SGLT2i with strong HF and CKD outcome data independent of diabetes status. Access friction is mainly formulary/price, not legality.",
        "typical_us_cost_range": "$400–700/month brand; lower with coverage/coupons",
        "indications": "HFrEF, HFpEF (agent-specific), CKD, T2D.",
        "sources": [{"title": "DAPA-HF / EMPEROR trials", "url": "https://pubmed.ncbi.nlm.nih.gov"}],
    },
    {
        "id": "proc-glp1-addiction",
        "name": "GLP-1 Agonists for Alcohol / Substance Use Disorder (Emerging)",
        "modality": Modality.REPURPOSED,
        "subcategory": "Metabolic Hormone Off-Label",
        "therapeutic_areas": ["Addiction", "Mental_Health"],
        "description": "Semaglutide/tirzepatide prescribed off-label or studied for alcohol use disorder and other addictions. Evidence emerging; not a labeled SUD indication in most markets.",
        "typical_us_cost_range": "$200–1,400/month depending on brand vs compounded",
        "indications": "Investigational/off-label for AUD and other SUD; labeled for T2D/obesity.",
        "sources": [{"title": "GLP-1 addiction evidence review", "url": "https://pubmed.ncbi.nlm.nih.gov"}],
    },
    {
        "id": "proc-prazosin-ptsd",
        "name": "Prazosin for PTSD Nightmares",
        "modality": Modality.REPURPOSED,
        "subcategory": "Alpha-1 Blocker Off-Label",
        "therapeutic_areas": ["Mental_Health", "PTSD"],
        "description": "Alpha-1 antagonist used off-label for trauma-related nightmares. Inexpensive generic; evidence mixed across trials but widely used in veterans' care.",
        "typical_us_cost_range": "$5–30/month",
        "indications": "PTSD-associated nightmares; labeled for hypertension.",
        "sources": [{"title": "VA prazosin PTSD practice", "url": "https://www.va.gov"}],
    },
    {
        "id": "proc-baclofen-aud",
        "name": "High-Dose Baclofen for Alcohol Use Disorder",
        "modality": Modality.REPURPOSED,
        "subcategory": "GABA-B Agonist Off-Label",
        "therapeutic_areas": ["Addiction"],
        "description": "Baclofen used off-label (sometimes high-dose protocols popularized in Europe) for alcohol dependence. France has had specific regulatory history; other countries physician discretion.",
        "typical_us_cost_range": "$20–80/month",
        "indications": "Alcohol use disorder (off-label in most places).",
        "sources": [{"title": "Baclofen AUD literature", "url": "https://pubmed.ncbi.nlm.nih.gov"}],
    },
    {
        "id": "proc-peptide-cjc-ipa",
        "name": "CJC-1295 / Ipamorelin Growth Hormone Secretagogue Peptides",
        "modality": Modality.PEPTIDE,
        "subcategory": "GHRH / GHRP Analog",
        "therapeutic_areas": ["Anti_Aging", "Performance"],
        "description": "Peptide secretagogues used in wellness/anti-aging clinics to raise GH/IGF-1. Not FDA-approved for these uses; compounding status restricted for many related peptides.",
        "typical_us_cost_range": "$150–500/month",
        "indications": "Off-label wellness, body composition, recovery — limited high-quality RCTs.",
        "sources": [{"title": "FDA peptide compounding notes", "url": "https://www.fda.gov"}],
    },
    {
        "id": "proc-peptide-tesamorelin",
        "name": "Tesamorelin (Egrifta) for HIV Lipodystrophy / Off-Label Visceral Fat",
        "modality": Modality.PEPTIDE,
        "subcategory": "GHRH Analog Approved",
        "therapeutic_areas": ["Metabolic_Health", "HIV"],
        "description": "FDA-approved GHRH analog for reduction of excess abdominal fat in HIV-associated lipodystrophy. Off-label interest for visceral adiposity outside HIV.",
        "typical_us_cost_range": "$3,000–6,000/month list (assistance programs exist)",
        "indications": "HIV lipodystrophy (labeled); off-label visceral fat reduction.",
        "sources": [{"title": "Egrifta FDA label", "url": "https://www.accessdata.fda.gov"}],
    },
    {
        "id": "proc-mito-replacement",
        "name": "Mitochondrial Replacement Therapy (MRT / Three-Person IVF)",
        "modality": Modality.REPRODUCTIVE,
        "subcategory": "Mitochondrial Donation",
        "therapeutic_areas": ["Reproductive_Health", "Genetics"],
        "description": "Pronuclear or spindle transfer to prevent transmission of pathogenic mtDNA disease. Legal under regulated pathway in UK; largely prohibited or unregulated elsewhere.",
        "typical_us_cost_range": "$50,000–100,000+ estimated full pathway",
        "indications": "Women at risk of transmitting serious mitochondrial DNA disease.",
        "sources": [{"title": "UK HFEA mitochondrial donation", "url": "https://www.hfea.gov.uk"}],
    },
    {
        "id": "proc-egg-freezing",
        "name": "Elective Oocyte Cryopreservation (Social Egg Freezing)",
        "modality": Modality.REPRODUCTIVE,
        "subcategory": "Fertility Preservation",
        "therapeutic_areas": ["Reproductive_Health"],
        "description": "Planned oocyte freezing without medical indication (career/age planning). Legal in most developed markets; some jurisdictions restrict non-medical freezing or limit storage duration.",
        "typical_us_cost_range": "$8,000–15,000 cycle + $500–1,000/year storage (US)",
        "indications": "Elective fertility preservation; also medical oncofertility (separate pathway).",
        "sources": [{"title": "ASRM egg freezing opinion", "url": "https://www.asrm.org"}],
    },
    {
        "id": "proc-uterine-transplant",
        "name": "Uterus Transplantation for Absolute Uterine Factor Infertility",
        "modality": Modality.REPRODUCTIVE,
        "subcategory": "Transplant Reproduction",
        "therapeutic_areas": ["Reproductive_Health"],
        "description": "Living or deceased donor uterus transplant enabling pregnancy in AUFI (e.g. MRKH). Available only at specialized programs; high cost and ethical oversight.",
        "typical_us_cost_range": "$200,000–500,000+ program costs",
        "indications": "Absolute uterine factor infertility; extensive screening.",
        "sources": [{"title": "Uterus transplant clinical programs", "url": "https://pubmed.ncbi.nlm.nih.gov"}],
    },
    {
        "id": "proc-5meo-dmt",
        "name": "5-MeO-DMT Assisted Therapy",
        "modality": Modality.PSYCHEDELICS,
        "subcategory": "Tryptamine",
        "therapeutic_areas": ["Mental_Health", "Spirituality"],
        "description": "Short-acting intense psychedelic (synthetic or Bufo alvarius–derived). Clinical development emerging; ceremonial/retreat use in gray markets. High psychological intensity; toad-sourced product raises conservation/ethics issues.",
        "typical_us_cost_range": "$500–3,000 (retreat/session estimates)",
        "indications": "Investigational depression/anxiety/addiction; not approved medicines in major markets.",
        "sources": [{"title": "5-MeO-DMT research reviews", "url": "https://pubmed.ncbi.nlm.nih.gov"}],
    },
    {
        "id": "proc-ketamine-assisted-psychotherapy",
        "name": "Ketamine-Assisted Psychotherapy (KAP)",
        "modality": Modality.PSYCHEDELICS,
        "subcategory": "Dissociative + Therapy",
        "therapeutic_areas": ["Mental_Health", "Depression", "PTSD"],
        "description": "Structured psychotherapy wrapped around ketamine dosing sessions (distinct from infusion-only clinics). Practice standards vary; not a separate FDA approval from ketamine/esketamine.",
        "typical_us_cost_range": "$300–800/session; courses $3,000–12,000",
        "indications": "TRD, PTSD, anxiety — off-label ketamine with therapy model.",
        "sources": [{"title": "ASKP / KAP practice guidance", "url": "https://askp.org"}],
    },
    {
        "id": "proc-pef-ablation",
        "name": "Pulsed Field Ablation (PFA) for Atrial Fibrillation",
        "modality": Modality.REPURPOSED,
        "subcategory": "Cardiac Electrophysiology",
        "therapeutic_areas": ["Cardiovascular"],
        "description": "Nonthermal irreversible electroporation ablation for AF. Rapidly expanding after FDA clearances of PFA systems; availability lags in lower-resource systems.",
        "typical_us_cost_range": "$25,000–50,000 episode of care",
        "indications": "Paroxysmal/persistent AF per device labels and guidelines.",
        "sources": [{"title": "FDA PFA systems", "url": "https://www.fda.gov"}],
    },
    {
        "id": "proc-lecanemab",
        "name": "Anti-Amyloid Monoclonal Antibodies (Lecanemab / Donanemab) for Early Alzheimer's",
        "modality": Modality.REPURPOSED,
        "subcategory": "Disease-Modifying Biologic",
        "therapeutic_areas": ["Neurology", "Dementia"],
        "description": "IV anti-amyloid mAbs for early AD with confirmed amyloid. Require APOE testing, MRI monitoring for ARIA. Coverage and capacity constrain access even where approved.",
        "typical_us_cost_range": "$26,000–32,000/year drug + imaging/infusion costs",
        "indications": "MCI due to AD or mild AD dementia with amyloid confirmation.",
        "sources": [{"title": "Leqembi FDA", "url": "https://www.fda.gov"}],
    },
    {
        "id": "proc-trt",
        "name": "Testosterone Replacement Therapy (TRT) for Hypogonadism",
        "modality": Modality.REPURPOSED,
        "subcategory": "Hormone Replacement",
        "therapeutic_areas": ["Endocrinology", "Men's_Health"],
        "description": "Testosterone for clinical hypogonadism. Legal with prescription in most countries; telehealth and compounding gray markets common. Controlled substance in US (Schedule III).",
        "typical_us_cost_range": "$30–200/month (generic injections); clinics $100–400/month",
        "indications": "Documented hypogonadism; not approved as general 'anti-aging' in most labels.",
        "sources": [{"title": "Endocrine Society testosterone guideline", "url": "https://www.endocrine.org"}],
    },
    {
        "id": "proc-peptide-ss31",
        "name": "Elamipretide / Mitochondrial-Targeted Peptides (SS-31 Class)",
        "modality": Modality.PEPTIDE,
        "subcategory": "Mitochondrial Peptide",
        "therapeutic_areas": ["Mitochondrial_Health", "Cardiology", "Ophthalmology"],
        "description": "Mitochondria-targeted peptides (elamipretide and analogs) in development for Barth syndrome, mitochondrial myopathy, dry AMD, etc. Limited approved access; mostly trials/expanded access.",
        "typical_us_cost_range": "Trial or expanded access; commercial TBD",
        "indications": "Rare mitochondrial disease / investigational ophthalmology indications.",
        "sources": [{"title": "Elamipretide clinical programs", "url": "https://clinicaltrials.gov"}],
    },
    {
        "id": "proc-ecmo-bridge",
        "name": "Elective / Bridge ECMO and Advanced Cardiac Support Tourism Pathways",
        "modality": Modality.REPURPOSED,
        "subcategory": "Critical Care Technology",
        "therapeutic_areas": ["Cardiovascular", "Critical_Care"],
        "description": "ECMO is standard in major ICUs for severe cardiopulmonary failure. 'Tourism' angle is limited; arbitrage is capacity/expertise at high-volume centers rather than legality.",
        "typical_us_cost_range": "$100,000–500,000+ per run",
        "indications": "Refractory cardiogenic shock, severe ARDS, bridge to transplant/decision.",
        "sources": [{"title": "ELSO ECMO guidelines", "url": "https://www.elso.org"}],
    },
    {
        "id": "proc-fecal-sibo",
        "name": "Elemental Diet / Rifaximin Protocols for SIBO (Access Friction Map)",
        "modality": Modality.REPURPOSED,
        "subcategory": "GI Antimicrobial / Diet",
        "therapeutic_areas": ["Gastrointestinal"],
        "description": "Rifaximin (and combination protocols) plus elemental diets for small intestinal bacterial overgrowth. Drug access and insurance denials create practical arbitrage more than legality.",
        "typical_us_cost_range": "$1,000–2,500 for brand rifaximin course; elemental diet $500–1,000",
        "indications": "SIBO / IBS-D related overgrowth syndromes (rifaximin labeled for IBS-D/hepatic encephalopathy in some markets).",
        "sources": [{"title": "ACG SIBO guidance", "url": "https://gi.org"}],
    },
    {
        "id": "proc-low-dose-lithium",
        "name": "Low-Dose Lithium for Neuroprotection / Mood",
        "modality": Modality.REPURPOSED,
        "subcategory": "Mineral / Mood Stabilizer Microdose",
        "therapeutic_areas": ["Mental_Health", "Neurology"],
        "description": "Sub-psychiatric doses of lithium (often lithium orotate OTC or low-dose carbonate) used for mood stability and putative dementia risk reduction. Full-dose lithium is prescription; microdose market is supplement/gray.",
        "typical_us_cost_range": "$10–40/month",
        "indications": "Off-label/neuroprotective interest; full-dose labeled for bipolar disorder.",
        "sources": [{"title": "Lithium neuroprotection literature", "url": "https://pubmed.ncbi.nlm.nih.gov"}],
    },
    {
        "id": "proc-psilocybin-microdose",
        "name": "Psilocybin Microdosing Protocols",
        "modality": Modality.PSYCHEDELICS,
        "subcategory": "Classical Psychedelic Microdose",
        "therapeutic_areas": ["Mental_Health", "Cognition"],
        "description": "Sub-perceptual repeated dosing of psilocybin. Distinct from full-dose assisted therapy. Legal only where psilocybin is decriminalized/regulated; clinical evidence mixed.",
        "typical_us_cost_range": "$20–200/month (gray/decrim supply)",
        "indications": "Self-experimentation for mood/focus; not an approved medical protocol in major regulators.",
        "sources": [{"title": "Microdosing trial literature", "url": "https://pubmed.ncbi.nlm.nih.gov"}],
    },
    {
        "id": "proc-cord-blood",
        "name": "Umbilical Cord Blood / Perinatal Cell Therapies",
        "modality": Modality.STEM_CELL,
        "subcategory": "Allogeneic Perinatal Cells",
        "therapeutic_areas": ["Hematology", "Regeneration"],
        "description": "Banked cord blood for approved hematopoietic transplants; also marketed unproven perinatal cell infusions in regenerative clinics abroad.",
        "typical_us_cost_range": "Transplant standard of care (insured when indicated); clinic infusions $5,000–25,000",
        "indications": "Approved: selected hematologic diseases. Clinic marketing: autism, CP, anti-aging (evidence often weak).",
        "sources": [{"title": "FDA cord blood guidance", "url": "https://www.fda.gov"}],
    },
    {
        "id": "proc-photoimmunotherapy",
        "name": "Near-Infrared Photoimmunotherapy for Head & Neck Cancer",
        "modality": Modality.ONCOLOGY,
        "subcategory": "Targeted Light-Activated Therapy",
        "therapeutic_areas": ["Oncology"],
        "description": "Antibody-IR700 conjugate activated by near-infrared light (e.g. Japan-approved ASP-1929/Akalux pathway). Geographic access currently skewed to Japan and trial sites.",
        "typical_us_cost_range": "Country-specific; specialty oncology pricing",
        "indications": "Unresectable locally advanced/recurrent head and neck cancer (label/jurisdiction-specific).",
        "sources": [{"title": "Japan PMDA photoimmunotherapy", "url": "https://www.pmda.go.jp"}],
    },
]


PROCEDURE_DISEASES_EXPANSION = {
    "proc-tms-depression": ["Treatment-Resistant Depression", "Major Depressive Disorder"],
    "proc-tms-ocd": ["Obsessive-Compulsive Disorder"],
    "proc-vns-depression": ["Treatment-Resistant Depression", "Epilepsy"],
    "proc-dbs-parkinson": ["Parkinson's Disease", "Essential Tremor (selected targets)"],
    "proc-fus-tremor": ["Essential Tremor", "Parkinson's Disease Tremor"],
    "proc-til-melanoma": ["Advanced Melanoma", "Metastatic Melanoma"],
    "proc-car-t-solid": ["Advanced Solid Tumors", "Gastric Cancer (trial)", "Neuroblastoma (trial)"],
    "proc-dendritic-vaccine": ["Metastatic Castration-Resistant Prostate Cancer", "Solid Tumors (clinic variable)"],
    "proc-apheresis-longcovid": ["Long COVID", "ME/CFS-like Post-Viral Syndrome", "Hyperviscosity Syndromes (labeled apheresis)"],
    "proc-ivig": ["Primary Immunodeficiency", "CIDP", "ITP", "Autoimmune Encephalitis (off-label)", "Long COVID (off-label)"],
    "proc-sglt2-hf": ["Heart Failure", "Chronic Kidney Disease", "Type 2 Diabetes"],
    "proc-glp1-addiction": ["Alcohol Use Disorder", "Obesity", "Type 2 Diabetes"],
    "proc-prazosin-ptsd": ["PTSD Nightmares", "Hypertension (labeled)"],
    "proc-baclofen-aud": ["Alcohol Use Disorder"],
    "proc-peptide-cjc-ipa": ["Age-Related Sarcopenia", "Growth Hormone Deficiency (not labeled for secretagogues)"],
    "proc-peptide-tesamorelin": ["HIV-Associated Lipodystrophy", "Visceral Adiposity (off-label)"],
    "proc-mito-replacement": ["Mitochondrial DNA Disease", "Leigh Syndrome Risk", "Mitochondrial Inheritance Risk"],
    "proc-egg-freezing": ["Age-Related Fertility Decline", "Oncofertility", "Elective Fertility Preservation"],
    "proc-uterine-transplant": ["Absolute Uterine Factor Infertility", "MRKH Syndrome"],
    "proc-5meo-dmt": ["Depression", "Anxiety", "Substance Use Disorder", "Existential Distress"],
    "proc-ketamine-assisted-psychotherapy": ["Treatment-Resistant Depression", "PTSD", "Anxiety Disorders"],
    "proc-pef-ablation": ["Atrial Fibrillation"],
    "proc-lecanemab": ["Early Alzheimer's Disease", "Mild Cognitive Impairment due to AD"],
    "proc-trt": ["Male Hypogonadism", "Testosterone Deficiency"],
    "proc-peptide-ss31": ["Barth Syndrome", "Mitochondrial Myopathy", "Dry AMD (investigational)"],
    "proc-ecmo-bridge": ["Cardiogenic Shock", "Severe ARDS", "Bridge to Transplant"],
    "proc-fecal-sibo": ["SIBO", "IBS-D", "Hepatic Encephalopathy (rifaximin labeled)"],
    "proc-low-dose-lithium": ["Bipolar Disorder (full-dose labeled)", "Mood Instability", "Dementia Risk Reduction (investigational)"],
    "proc-psilocybin-microdose": ["Depression", "Anxiety", "ADHD Symptoms (self-report)"],
    "proc-cord-blood": ["Leukemia (transplant)", "Lymphoma (transplant)", "Cerebral Palsy (investigational clinics)"],
    "proc-photoimmunotherapy": ["Head and Neck Squamous Cell Carcinoma"],
}


CONDITIONS_EXPANSION = [
    {"id": "cond-ocd", "name": "Obsessive-Compulsive Disorder", "icd_code": "F42",
     "description": "OCD with intrusive obsessions and compulsions; target for deep TMS and other neuromodulation."},
    {"id": "cond-pd", "name": "Parkinson's Disease", "icd_code": "G20",
     "description": "Neurodegenerative movement disorder; DBS and focused ultrasound for motor complications."},
    {"id": "cond-et", "name": "Essential Tremor", "icd_code": "G25.0",
     "description": "Action tremor syndrome; MRgFUS thalamotomy indication."},
    {"id": "cond-melanoma", "name": "Advanced / Metastatic Melanoma", "icd_code": "C43",
     "description": "Advanced cutaneous melanoma after checkpoint therapy — TIL therapy population."},
    {"id": "cond-long-covid", "name": "Long COVID / PASC", "icd_code": "U09.9",
     "description": "Post-acute sequelae of SARS-CoV-2; experimental apheresis and other investigational pathways."},
    {"id": "cond-hf", "name": "Heart Failure", "icd_code": "I50",
     "description": "HFrEF/HFpEF populations for SGLT2 inhibitors and advanced cardiac support."},
    {"id": "cond-aud", "name": "Alcohol Use Disorder", "icd_code": "F10.2",
     "description": "Alcohol dependence; baclofen and emerging GLP-1 off-label interest."},
    {"id": "cond-afib", "name": "Atrial Fibrillation", "icd_code": "I48",
     "description": "Supraventricular arrhythmia treated with catheter ablation including PFA."},
    {"id": "cond-alz", "name": "Early Alzheimer's Disease", "icd_code": "G30",
     "description": "MCI due to AD or mild AD dementia with amyloid pathology — anti-amyloid mAb population."},
    {"id": "cond-hypogonadism", "name": "Male Hypogonadism", "icd_code": "E29.1",
     "description": "Clinically confirmed testosterone deficiency."},
    {"id": "cond-mtdna", "name": "Pathogenic mtDNA Disease Risk", "icd_code": "E88.4",
     "description": "Women at risk of transmitting serious mitochondrial DNA disease — MRT candidates."},
    {"id": "cond-aufi", "name": "Absolute Uterine Factor Infertility", "icd_code": "N97.8",
     "description": "Absence or nonfunctioning uterus; uterus transplant indication."},
    {"id": "cond-sibo", "name": "Small Intestinal Bacterial Overgrowth", "icd_code": "K63.821",
     "description": "SIBO syndromes treated with rifaximin/elemental diet protocols."},
    {"id": "cond-hnc", "name": "Head and Neck Cancer", "icd_code": "C14.8",
     "description": "Locally advanced/recurrent head and neck squamous cell carcinoma."},
]


PROCEDURE_INDICATIONS_EXPANSION = [
    {"id": "pi-tms-trd", "procedure_id": "proc-tms-depression", "condition_id": "cond-trd",
     "evidence_grade": EvidenceGrade.E1,
     "evidence_summary": "Multiple RCTs and meta-analyses support rTMS/iTBS for TRD; FDA-cleared devices. E1."},
    {"id": "pi-tms-ocd", "procedure_id": "proc-tms-ocd", "condition_id": "cond-ocd",
     "evidence_grade": EvidenceGrade.E2,
     "evidence_summary": "Pivotal deep TMS trials for OCD led to device clearance; fewer trials than depression TMS. E2."},
    {"id": "pi-dbs-pd", "procedure_id": "proc-dbs-parkinson", "condition_id": "cond-pd",
     "evidence_grade": EvidenceGrade.E1,
     "evidence_summary": "Decades of RCTs for STN/GPi DBS in advanced PD motor complications. E1."},
    {"id": "pi-fus-et", "procedure_id": "proc-fus-tremor", "condition_id": "cond-et",
     "evidence_grade": EvidenceGrade.E1,
     "evidence_summary": "RCTs of MRgFUS thalamotomy for essential tremor with durable tremor reduction. E1."},
    {"id": "pi-til-mel", "procedure_id": "proc-til-melanoma", "condition_id": "cond-melanoma",
     "evidence_grade": EvidenceGrade.E2,
     "evidence_summary": "Lifileucel pivotal program in advanced melanoma after anti-PD-1; regulatory-grade data. E2."},
    {"id": "pi-sglt2-hf", "procedure_id": "proc-sglt2-hf", "condition_id": "cond-hf",
     "evidence_grade": EvidenceGrade.E1,
     "evidence_summary": "DAPA-HF, EMPEROR, DELIVER and related outcome trials — multi-RCT HF benefit. E1."},
    {"id": "pi-lecanemab-alz", "procedure_id": "proc-lecanemab", "condition_id": "cond-alz",
     "evidence_grade": EvidenceGrade.E2,
     "evidence_summary": "CLARITY-AD and related trials show modest clinical slowing with ARIA risk; approved early AD pathway. E2."},
    {"id": "pi-pfa-afib", "procedure_id": "proc-pef-ablation", "condition_id": "cond-afib",
     "evidence_grade": EvidenceGrade.E1,
     "evidence_summary": "Pivotal PFA trials (e.g. ADVENT) show noninferior efficacy vs thermal ablation with safety profile advantages. E1."},
    {"id": "pi-kap-trd", "procedure_id": "proc-ketamine-assisted-psychotherapy", "condition_id": "cond-trd",
     "evidence_grade": EvidenceGrade.E2,
     "evidence_summary": "Ketamine has E1 pharmacologic evidence; KAP as a packaged psychotherapy model has fewer standardized RCTs than infusion-only. E2 for the combined model."},
    {"id": "pi-mrt-mtdna", "procedure_id": "proc-mito-replacement", "condition_id": "cond-mtdna",
     "evidence_grade": EvidenceGrade.E4,
     "evidence_summary": "UK program data and case series; not classic multi-RCT drug evidence. E4 clinical program evidence."},
    {"id": "pi-baclofen-aud", "procedure_id": "proc-baclofen-aud", "condition_id": "cond-aud",
     "evidence_grade": EvidenceGrade.E3,
     "evidence_summary": "Mixed RCTs for baclofen in AUD (dose and population heterogeneity). E3."},
    {"id": "pi-photo-hnc", "procedure_id": "proc-photoimmunotherapy", "condition_id": "cond-hnc",
     "evidence_grade": EvidenceGrade.E2,
     "evidence_summary": "Japan approval pathway and clinical studies for ASP-1929 photoimmunotherapy in HNSCC. E2."},
]


# ── Access rows (key jurisdictions per new therapy) ─────────────────────────

ACCESS_THERAPIES_EXPANSION = [
    # TMS depression
    R("proc-tms-depression", "jur-us-federal", LS.FULLY_APPROVED, AP.STANDARD_PRESCRIPTION, OQ.HIGH,
      "FDA-cleared TMS devices for MDD/TRD; widely available outpatient centers; often insurance-covered when criteria met.",
      "Failed antidepressant trials per payer policy; psychiatric evaluation.", "Psychiatrists / TMS-certified clinics.",
      "FDA device clearance + payer policies.", "$6k–15k/course", "Often insured after prior auth.",
      "Nationwide outpatient.", "Seizure rare; scalp discomfort; hearing protection needed.",
      "US: mature covered neuromodulation pathway for TRD.",
      price=10000, basis="insured", conf=CF.HIGH),
    R("proc-tms-depression", "jur-de", LS.FULLY_APPROVED, AP.STANDARD_PRESCRIPTION, OQ.HIGH,
      "rTMS available in German psychiatry; statutory insurance for selected TRD protocols at qualified centers.",
      "Specialist referral; failed meds.", "Krankenhaus/outpatient neurostimulation units.", "G-BA/device rules.",
      "€5k–12k if private; insured when approved", "Indication review for public cover.",
      "Domestic EU.", "Standard TMS risks.",
      "Germany: regulated clinical TMS access.",
      price=8000, basis="insured", conf=CF.MODERATE),
    R("proc-tms-depression", "jur-uk", LS.FULLY_APPROVED, AP.STANDARD_PRESCRIPTION, OQ.HIGH,
      "NICE-supported rTMS for depression in selected pathways; NHS capacity limited; private sector common.",
      "Specialist assessment.", "NHS/private neurostimulation clinics.", "NICE + CQC.",
      "£6k–12k private", "NHS waiting lists variable.", "Domestic.", "Standard risks.",
      "UK: approved technology; private often faster than NHS.",
      price=9000, conf=CF.MODERATE),
    R("proc-tms-depression", "jur-au", LS.FULLY_APPROVED, AP.STANDARD_PRESCRIPTION, OQ.HIGH,
      "TMS widely practiced; Medicare items for eligible TRD in Australia.",
      "Psychiatrist referral; Medicare criteria.", "Private psychiatry clinics.", "TGA devices + Medicare.",
      "AUD $6k–12k", "Rebates reduce OOP when eligible.", "Domestic.", "Standard risks.",
      "Australia: funded pathway for eligible TRD.",
      price=7000, basis="insured", conf=CF.HIGH),
    R("proc-tms-depression", "jur-ca", LS.FULLY_APPROVED, AP.STANDARD_PRESCRIPTION, OQ.HIGH,
      "rTMS available provincially; coverage varies by province and indication.",
      "Specialist referral.", "Hospital/clinic TMS programs.", "Health Canada devices.",
      "CAD $5k–12k", "Provincial cover uneven.", "Domestic.", "Standard risks.",
      "Canada: available; funding patchwork by province.",
      price=7500, conf=CF.MODERATE),

    # DBS PD
    R("proc-dbs-parkinson", "jur-us-federal", LS.FULLY_APPROVED, AP.STANDARD_PRESCRIPTION, OQ.HIGH,
      "FDA-approved DBS systems for PD; major academic centers; typically insured when criteria met.",
      "Advanced PD motor complications; multidisciplinary screening.", "Functional neurosurgery centers.",
      "FDA + hospital credentialing.", "$50k–100k+", "Insurance common for labeled PD.",
      "Center-of-excellence travel common.", "Surgical/hardware infection; stimulation side effects.",
      "US: standard advanced-PD option at high-volume centers.",
      price=75000, basis="insured", conf=CF.HIGH),
    R("proc-dbs-parkinson", "jur-de", LS.FULLY_APPROVED, AP.STANDARD_PRESCRIPTION, OQ.HIGH,
      "DBS standard in German neurosurgery for PD; statutory insurance when indicated.",
      "Movement-disorder board.", "University neurosurgery.", "G-BA.",
      "Public cover when indicated", "High capacity in EU terms.", "EU referral possible.", "Surgical risks.",
      "Germany: strong public DBS access for PD.",
      price=60000, basis="insured", conf=CF.HIGH),
    R("proc-dbs-parkinson", "jur-jp", LS.FULLY_APPROVED, AP.STANDARD_PRESCRIPTION, OQ.HIGH,
      "DBS established under Japanese insurance for selected PD patients.",
      "Specialist criteria.", "Neurosurgery hospitals.", "MHLW.",
      "Insurance-eligible cases", "Domestic primarily.", "Domestic.", "Surgical risks.",
      "Japan: regulated insured DBS pathway.",
      price=55000, basis="insured", conf=CF.MODERATE),
    R("proc-dbs-parkinson", "jur-in", LS.FULLY_APPROVED, AP.MEDICAL_TOURISM_CASH, OQ.MEDIUM,
      "DBS offered at major Indian neurosurgery centers at lower cash prices; quality varies by hospital.",
      "Clinical PD criteria; ability to pay/travel.", "Tertiary private hospitals.", "CDSCO devices + hospital standards.",
      "$20k–40k cash packages", "Significant savings vs US if reputable center.", "Medical tourism hubs.", "Verify surgeon volume.",
      "India: cost arbitrage for DBS at selected centers.",
      price=28000, conf=CF.MODERATE),

    # FUS tremor
    R("proc-fus-tremor", "jur-us-federal", LS.FULLY_APPROVED, AP.STANDARD_PRESCRIPTION, OQ.HIGH,
      "FDA-approved MRgFUS for essential tremor and PD tremor at equipped centers.",
      "Medication-refractory tremor; skull density ratio screening.", "Focused ultrasound centers.",
      "FDA device + specialty centers.", "$30k–60k", "Insurance improving but variable.",
      "Limited center map.", "Sensory/gait side effects; unilateral first.",
      "US: approved incisionless option; center-limited.",
      price=45000, basis="insured", conf=CF.HIGH),
    R("proc-fus-tremor", "jur-jp", LS.FULLY_APPROVED, AP.STANDARD_PRESCRIPTION, OQ.HIGH,
      "Japan early adopter of clinical focused ultrasound for tremor.",
      "Specialist selection.", "Equipped hospitals.", "PMDA.",
      "Insurance/private mix", "High-tech access.", "Domestic/medical travel.", "Standard FUS risks.",
      "Japan: strong FUS clinical availability.",
      price=40000, conf=CF.MODERATE),
    R("proc-fus-tremor", "jur-il", LS.FULLY_APPROVED, AP.STANDARD_PRESCRIPTION, OQ.HIGH,
      "Israeli centers historically prominent in MRgFUS clinical development/care.",
      "Specialist referral.", "Hospital programs.", "Ministry of Health.",
      "$25k–50k est.", "Some medical travel.", "Tel Aviv/Haifa hubs.", "Standard risks.",
      "Israel: notable FUS clinical experience.",
      price=35000, conf=CF.MODERATE),

    # TIL melanoma
    R("proc-til-melanoma", "jur-us-federal", LS.FULLY_APPROVED, AP.STANDARD_PRESCRIPTION, OQ.HIGH,
      "Lifileucel (Amtagvi) FDA-approved for advanced melanoma after anti-PD-1; specialized treatment centers.",
      "Label criteria; adequate organ function; resectable tumor for TIL harvest.", "Authorized treatment centers.",
      "FDA REMS-like center model.", "$500k+ total episode", "Insurance evolving for labeled use.",
      "Must treat at authorized US centers.", "Lymphodepletion toxicity; ICU-level risks.",
      "US: first approved TIL product pathway.",
      price=515000, basis="insured", pconf=PC.QUOTED, conf=CF.HIGH),
    R("proc-til-melanoma", "jur-de", LS.CLINICAL_TRIAL_ONLY, AP.CLINICAL_TRIAL_ENROLLMENT, OQ.HIGH,
      "TIL programs historically academic/trial in Europe; commercial availability lags US approval timelines.",
      "Trial criteria.", "Academic oncology centers.", "EMA/national trial oversight.",
      "Trial pathway", "Watch EMA commercial status.", "EU academic travel.", "Trial toxicities.",
      "Germany/EU: primarily trial/academic until broader authorization.",
      price=None, conf=CF.MODERATE, vol=VL.ACTIVE_FLUX),

    # Apheresis long COVID
    R("proc-apheresis-longcovid", "jur-de", LS.PHYSICIAN_DISCRETION_GRAY, AP.OFF_LABEL_PRESCRIPTION, OQ.MEDIUM,
      "German/Swiss clinics popularized HELP/immunoadsorption for long COVID; not guideline standard of care; cash-pay common.",
      "Clinical evaluation; exclude contraindications to apheresis.", "Specialized apheresis clinics.",
      "Medical practice; evidence contested.", "€2k–6k/session", "Multi-session courses expensive.",
      "Medical travel common.", "Line infection, bleeding, unproven benefit for many.",
      "Germany: available experimental clinic pathway — evidence still evolving.",
      price=3500, conf=CF.LOW, vol=VL.ACTIVE_FLUX),
    R("proc-apheresis-longcovid", "jur-ch", LS.PHYSICIAN_DISCRETION_GRAY, AP.OFF_LABEL_PRESCRIPTION, OQ.MEDIUM,
      "Swiss private clinics offer apheresis protocols for post-COVID syndromes.",
      "Private evaluation.", "Private clinics.", "Cantonal medical oversight.",
      "CHF 2.5k–7k/session", "Premium pricing.", "Open to internationals privately.", "Unproven for many phenotypes.",
      "Switzerland: private experimental apheresis access.",
      price=4500, conf=CF.LOW),
    R("proc-apheresis-longcovid", "jur-us-federal", LS.CLINICAL_TRIAL_ONLY, AP.CLINICAL_TRIAL_ENROLLMENT, OQ.HIGH,
      "Apheresis for long COVID not FDA-approved as a labeled PASC therapy; available for other indications; PASC use mainly trial/off-label rare.",
      "Trial or exceptional off-label.", "Academic centers.", "FDA device/procedure context for apheresis machines.",
      "Variable", "Insurance unlikely for PASC-only.", "Domestic trials.", "Procedure risks without proven benefit.",
      "US: not a standard long-COVID therapy — prefer trials.",
      price=None, conf=CF.MODERATE),

    # IVIG
    R("proc-ivig", "jur-us-federal", LS.FULLY_APPROVED, AP.STANDARD_PRESCRIPTION, OQ.HIGH,
      "Multiple FDA-licensed IVIG products; labeled indications insured; off-label requires payer battle.",
      "Labeled disease or strong specialty justification.", "Infusion centers; immunology/neuro.",
      "FDA biologics + REMS-free but specialty pharmacy.", "$5k–15k/cycle", "Coverage indication-dependent.",
      "Nationwide infusion infrastructure.", "Thrombosis, aseptic meningitis, renal risk — product-specific.",
      "US: excellent labeled access; off-label friction is payer not legality.",
      price=10000, basis="insured", conf=CF.HIGH),
    R("proc-ivig", "jur-de", LS.FULLY_APPROVED, AP.STANDARD_PRESCRIPTION, OQ.HIGH,
      "IVIG standard in German immunology/neurology; G-BA indication rules for reimbursement.",
      "Specialist indication.", "Hospital/outpatient infusion.", "PEI/G-BA.",
      "Public cover when indicated", "Off-label harder.", "Domestic.", "Product risks managed.",
      "Germany: strong labeled IVIG access.",
      price=9000, basis="insured", conf=CF.HIGH),
    R("proc-ivig", "jur-in", LS.FULLY_APPROVED, AP.STANDARD_PRESCRIPTION, OQ.MEDIUM,
      "IVIG available; cost still high relative to incomes; some domestic manufacturers.",
      "Specialist prescription.", "Hospital pharmacies.", "CDSCO.",
      "$1.5k–5k/cycle est.", "Cheaper than US list but still expensive.", "Medical travel sometimes.", "Quality brand selection matters.",
      "India: lower-cost IVIG market vs US list prices.",
      price=3000, conf=CF.MODERATE),

    # SGLT2 HF
    R("proc-sglt2-hf", "jur-us-federal", LS.FULLY_APPROVED, AP.STANDARD_PRESCRIPTION, OQ.HIGH,
      "Dapagliflozin/empagliflozin labeled for HF and CKD independent of diabetes; primary care + cardiology prescribing.",
      "HF or CKD label criteria; eGFR floors.", "Any licensed prescriber.", "FDA labels.",
      "$400–700/mo brand", "Insurance/coupons critical.", "Domestic telehealth common.", "Genital infections, rare DKA.",
      "US: approved cardiorenal drugs — access is cost/formulary.",
      price=550, conf=CF.HIGH),
    R("proc-sglt2-hf", "jur-uk", LS.FULLY_APPROVED, AP.STANDARD_PRESCRIPTION, OQ.HIGH,
      "NICE-recommended SGLT2i in HF/CKD pathways; NHS formulary access.",
      "Guideline-eligible HF/CKD.", "GPs/specialists.", "MHRA + NICE.",
      "NHS covered when indicated", "Low OOP.", "Domestic.", "Class risks.",
      "UK: strong NHS access for labeled HF/CKD.",
      price=0, basis="insured", conf=CF.HIGH),
    R("proc-sglt2-hf", "jur-de", LS.FULLY_APPROVED, AP.STANDARD_PRESCRIPTION, OQ.HIGH,
      "SGLT2i reimbursed for HF/CKD per German label extensions.",
      "Label criteria.", "Hausarzt/cardiology.", "G-BA.",
      "Statutory insurance", "Low OOP typical.", "Domestic.", "Class risks.",
      "Germany: routine reimbursed SGLT2i for HF/CKD.",
      price=40, basis="insured", conf=CF.HIGH),
    R("proc-sglt2-hf", "jur-in", LS.FULLY_APPROVED, AP.STANDARD_PRESCRIPTION, OQ.MEDIUM,
      "SGLT2i widely available as generics/brands at low cost.",
      "Clinical indication.", "Any physician.", "CDSCO.",
      "$10–40/month", "Major price arbitrage vs US.", "Easy pharmacy access.", "Counsel on side effects.",
      "India: low-cost SGLT2i access.",
      price=20, conf=CF.HIGH),

    # Lecanemab
    R("proc-lecanemab", "jur-us-federal", LS.FULLY_APPROVED, AP.STANDARD_PRESCRIPTION, OQ.HIGH,
      "Lecanemab (Leqembi) FDA-approved for early AD; CMS coverage with registry requirements; infusion + MRI monitoring capacity limited.",
      "MCI/mild AD + amyloid confirmation; APOE counseling; MRI schedule.", "Alzheimer's specialty centers.",
      "FDA + CMS CED.", "~$26k/year drug", "Coverage with conditions; imaging costs extra.",
      "Center capacity bottleneck.", "ARIA (edema/hemorrhage) risk — higher in APOE4.",
      "US: approved but capacity and monitoring constrained.",
      price=26500, basis="insured", pconf=PC.QUOTED, conf=CF.HIGH, vol=VL.ACTIVE_FLUX),
    R("proc-lecanemab", "jur-jp", LS.FULLY_APPROVED, AP.STANDARD_PRESCRIPTION, OQ.HIGH,
      "Japan approved lecanemab; rollout via specialty neurology with imaging requirements.",
      "Early AD criteria + amyloid.", "Specialist hospitals.", "PMDA.",
      "National pricing/insurance mix", "Capacity building.", "Domestic primarily.", "ARIA monitoring mandatory.",
      "Japan: approved early, structured rollout.",
      price=20000, basis="insured", conf=CF.MODERATE, vol=VL.ACTIVE_FLUX),
    R("proc-lecanemab", "jur-uk", LS.CLINICAL_TRIAL_ONLY, AP.CLINICAL_TRIAL_ENROLLMENT, OQ.HIGH,
      "NICE/MHRA pathway has been restrictive vs US for anti-amyloid mAbs; access often trial or limited managed access — verify current NICE status.",
      "NICE criteria if any; else trials.", "Specialist centers.", "NICE + MHRA.",
      "If NHS — covered when approved pathway exists", "Policy flux.", "Domestic.", "ARIA risks.",
      "UK: tighter access than US historically — check current NICE.",
      price=None, conf=CF.LOW, vol=VL.ACTIVE_FLUX),

    # MRT UK
    R("proc-mito-replacement", "jur-uk", LS.FULLY_APPROVED, AP.LICENSED_PROVIDER_REGIME, OQ.HIGH,
      "UK is the primary regulated jurisdiction for mitochondrial donation under HFEA licenses (Newcastle program and successors).",
      "Serious mtDNA disease risk; HFEA license criteria; counseling.", "HFEA-licensed clinics only.",
      "HFEA Act framework — unique globally.", "$50k–100k+ est. full pathway", "NHS/research mix historically.",
      "UK residency/pathway rules apply.", "Embryo micromanipulation risks; long-term follow-up ongoing.",
      "UK: world reference regulated MRT access.",
      price=75000, conf=CF.HIGH),
    R("proc-mito-replacement", "jur-us-federal", LS.PROHIBITED, AP.NONE, OQ.HIGH,
      "FDA/Congressional rider has blocked clinical mitochondrial replacement in the US; research restrictions apply.",
      "No clinical pathway.", "None clinical.", "FDA ban on heritable mitochondrial manipulation clinical use.",
      "N/A", "Patients may seek UK.", "N/A domestic.", "Legal prohibition.",
      "US: clinical MRT prohibited.",
      price=None, conf=CF.HIGH),
    R("proc-mito-replacement", "jur-au", LS.CLINICAL_TRIAL_ONLY, AP.CLINICAL_TRIAL_ENROLLMENT, OQ.HIGH,
      "Australia debated/legalized mitochondrial donation frameworks more recently than UK; implementation limited — verify current clinic licenses.",
      "Legislative criteria when operational.", "Licensed clinics if any.", "NHMRC/legislative framework.",
      "TBD", "Early implementation phase.", "Domestic.", "Experimental oversight.",
      "Australia: legal framework evolving; limited operational access.",
      price=None, conf=CF.LOW, vol=VL.PENDING_LEGISLATION),

    # Egg freezing
    R("proc-egg-freezing", "jur-us-federal", LS.FULLY_APPROVED, AP.LICENSED_PROVIDER_REGIME, OQ.HIGH,
      "Elective oocyte cryopreservation widely available at US fertility clinics; employer benefits common in tech.",
      "Adult women; clinic counseling on success rates by age.", "SART clinics.", "CDC/SART reporting; state embryo laws vary.",
      "$8k–15k/cycle + storage", "Often cash or employer benefit.", "Domestic.", "OHSS; no pregnancy guarantee.",
      "US: open elective egg freezing market.",
      price=12000, conf=CF.HIGH),
    R("proc-egg-freezing", "jur-es", LS.FULLY_APPROVED, AP.MEDICAL_TOURISM_CASH, OQ.HIGH,
      "Spain major fertility tourism destination; elective freezing common with strong clinic infrastructure.",
      "Clinic criteria; age limits vary.", "IVF clinics Barcelona/Madrid/Valencia.", "Spanish ART law.",
      "$4k–8k/cycle est.", "Lower than US.", "Popular for EU/UK patients.", "Standard IVF risks.",
      "Spain: cost-effective EU egg freezing destination.",
      price=5500, conf=CF.HIGH),
    R("proc-egg-freezing", "jur-de", LS.PHYSICIAN_DISCRETION_GRAY, AP.LICENSED_PROVIDER_REGIME, OQ.HIGH,
      "Social egg freezing legally nuanced in Germany historically more restrictive than Spain; medical freezing clearer — verify current clinic offerings.",
      "Clinic legal counseling essential.", "Fertility centers.", "Embryo protection law context.",
      "€4k–8k", "Policy sensitivity higher than Spain.", "Domestic.", "Legal counseling advised.",
      "Germany: more constrained elective pathway than Spain/US.",
      price=6000, conf=CF.MODERATE, vol=VL.PENDING_LEGISLATION),
    R("proc-egg-freezing", "jur-jp", LS.FULLY_APPROVED, AP.LICENSED_PROVIDER_REGIME, OQ.HIGH,
      "Egg freezing available; some municipal subsidy programs (e.g. Tokyo historically) for elective preservation.",
      "Age/clinic criteria.", "Registered ART clinics.", "JSAR/MHLW context.",
      "$5k–10k", "Subsidies variable by city.", "Domestic.", "Standard risks.",
      "Japan: available with occasional public subsidies.",
      price=7000, conf=CF.MODERATE),

    # 5-MeO-DMT
    R("proc-5meo-dmt", "jur-mx", LS.PHYSICIAN_DISCRETION_GRAY, AP.MEDICAL_TOURISM_CASH, OQ.MINIMAL,
      "Retreat/ceremonial 5-MeO offerings in Mexico; legal status gray; Bufo conservation concerns for toad-derived product.",
      "Retreat screening variable.", "Retreat facilitators.", "Minimal formal medical regulation.",
      "$800–3,000", "Ceremony packages.", "Tourism.", "Intense psychological risk; cardiac caution; ethics of toad sourcing.",
      "Mexico: retreat market exists — high risk/variable quality.",
      price=1500, conf=CF.LOW),
    R("proc-5meo-dmt", "jur-us-federal", LS.PROHIBITED, AP.CLINICAL_TRIAL_ENROLLMENT, OQ.HIGH,
      "5-MeO-DMT Schedule I federally; clinical trials only for synthetic product development.",
      "Trial criteria.", "Trial sites.", "DEA Schedule I.",
      "Trial only", "N/A retail.", "Domestic trials rare.", "Legal risk outside trials.",
      "US: prohibited outside research.",
      price=None, conf=CF.HIGH),
    R("proc-5meo-dmt", "jur-us-co", LS.DECRIMINALIZED, AP.NONE, OQ.LOW,
      "Prop 122 natural medicine decrim may include related tryptamines for personal use — not a commercial therapy framework for 5-MeO.",
      "21+ personal possession rules; no licensed 5-MeO centers.", "None licensed commercial.", "State decrim vs federal Schedule I tension.",
      "Personal/underground only", "No regulated price.", "State borders.", "No product testing; federal risk remains.",
      "Colorado: decrim personal natural meds — not regulated 5-MeO therapy.",
      price=None, conf=CF.LOW, vol=VL.ACTIVE_FLUX),

    # KAP
    R("proc-ketamine-assisted-psychotherapy", "jur-us-federal", LS.APPROVED_OFF_LABEL, AP.OFF_LABEL_PRESCRIPTION, OQ.MEDIUM,
      "KAP clinics combine ketamine with psychotherapy; ketamine off-label (Spravato separate REMS pathway). Standards vary widely.",
      "Psychiatric screening; BP check.", "Prescriber + therapist team.", "State medical boards; ASKP voluntary standards.",
      "$300–800/session", "Cash-pay dominant for KAP model.", "Nationwide growth.", "Dissociation; BP; therapy boundary risks.",
      "US: widely available KAP; quality varies by clinic.",
      price=500, conf=CF.HIGH),
    R("proc-ketamine-assisted-psychotherapy", "jur-ca", LS.APPROVED_OFF_LABEL, AP.OFF_LABEL_PRESCRIPTION, OQ.MEDIUM,
      "Ketamine clinics and KAP models expanding in Canada under provincial medical practice.",
      "Physician assessment.", "Medical clinics.", "Provincial colleges.",
      "CAD $400–900/session", "Mostly private pay.", "Domestic.", "Standard ketamine risks.",
      "Canada: private KAP growing.",
      price=550, conf=CF.MODERATE),
    R("proc-ketamine-assisted-psychotherapy", "jur-au", LS.APPROVED_OFF_LABEL, AP.OFF_LABEL_PRESCRIPTION, OQ.MEDIUM,
      "Ketamine therapy clinics operate under medical frameworks; psychotherapy integration variable.",
      "Specialist assessment.", "Private psychiatry clinics.", "AHPRA + TGA ketamine scheduling.",
      "AUD $400–900/session", "Private.", "Domestic.", "Standard risks.",
      "Australia: private medical ketamine/KAP available.",
      price=550, conf=CF.MODERATE),

    # PFA
    R("proc-pef-ablation", "jur-us-federal", LS.FULLY_APPROVED, AP.STANDARD_PRESCRIPTION, OQ.HIGH,
      "FDA-cleared PFA systems for AF; rapidly adopted at EP centers; insurance for AF ablation pathways.",
      "Symptomatic AF; EP evaluation.", "Cardiac electrophysiology labs.", "FDA devices + hospital privileges.",
      "$25k–50k episode", "Typically insured when ablation indicated.", "Center availability growing fast.", "Stroke/vascular risks lower thermal injury profile claimed.",
      "US: fast-growing standard AF ablation technology.",
      price=35000, basis="insured", conf=CF.HIGH),
    R("proc-pef-ablation", "jur-de", LS.FULLY_APPROVED, AP.STANDARD_PRESCRIPTION, OQ.HIGH,
      "PFA rolling out in European EP centers; reimbursement evolving with device approvals.",
      "AF ablation criteria.", "EP centers.", "EU MDR + national payers.",
      "Public/private mix", "Center-dependent.", "EU.", "Procedural risks.",
      "Germany: early European PFA adoption hubs.",
      price=30000, basis="insured", conf=CF.MODERATE, vol=VL.ACTIVE_FLUX),
    R("proc-pef-ablation", "jur-jp", LS.FULLY_APPROVED, AP.STANDARD_PRESCRIPTION, OQ.HIGH,
      "Japan approving/adopting PFA systems through PMDA and hospital rollout.",
      "Specialist EP criteria.", "Advanced cardiac centers.", "PMDA.",
      "Insurance pathways developing", "Domestic.", "Domestic.", "Procedural risks.",
      "Japan: advanced EP access including PFA rollout.",
      price=32000, conf=CF.MODERATE, vol=VL.ACTIVE_FLUX),

    # TRT
    R("proc-trt", "jur-us-federal", LS.FULLY_APPROVED, AP.STANDARD_PRESCRIPTION, OQ.MEDIUM,
      "Testosterone is Schedule III; legitimate TRT requires documented hypogonadism. Large telehealth/clinic market; FDA has warned about over-prescribing and compounded products.",
      "Two morning low-T labs + symptoms ideally; clinic standards vary.", "Endocrinology, urology, men's clinics.",
      "DEA Schedule III + FDA.", "$30–200/mo meds", "Clinic memberships add cost.", "Domestic.", "Erythrocytosis, fertility suppression, CV uncertainty if misused.",
      "US: easy access but quality of diagnostic rigor varies.",
      price=100, conf=CF.HIGH, vol=VL.ACTIVE_FLUX),
    R("proc-trt", "jur-uk", LS.FULLY_APPROVED, AP.STANDARD_PRESCRIPTION, OQ.HIGH,
      "TRT via NHS for confirmed hypogonadism or private men's clinics; tighter diagnostic culture than US cash clinics.",
      "Confirmed hypogonadism.", "Endocrinology/private clinics.", "MHRA + GMC.",
      "£30–100/mo private meds", "NHS if criteria met.", "Domestic.", "Monitoring required.",
      "UK: legitimate TRT available; less direct-to-consumer than US.",
      price=60, conf=CF.HIGH),
    R("proc-trt", "jur-mx", LS.FULLY_APPROVED, AP.MEDICAL_TOURISM_CASH, OQ.LOW,
      "Testosterone easily obtained via private clinics/pharmacies; monitoring quality variable.",
      "Often minimal labs at tourism clinics.", "Private clinics.", "COFEPRIS pharmacy channel.",
      "$20–80/mo", "Cheap; quality of care variable.", "Border tourism.", "Unmonitored TRT risks.",
      "Mexico: low-cost TRT with variable medical oversight.",
      price=40, conf=CF.LOW),

    # Photoimmunotherapy Japan
    R("proc-photoimmunotherapy", "jur-jp", LS.FULLY_APPROVED, AP.STANDARD_PRESCRIPTION, OQ.HIGH,
      "Near-infrared photoimmunotherapy (ASP-1929/Akalux pathway) approved in Japan for unresectable locally advanced/recurrent HNSCC.",
      "Label criteria; specialist head & neck oncology.", "Approved Japanese centers.", "PMDA.",
      "Specialty oncology pricing", "National system pathways.", "Medical travel possible to Japan.", "Local tissue damage; photosensitivity protocols.",
      "Japan: primary approved geography for this modality.",
      price=50000, conf=CF.MODERATE),
    R("proc-photoimmunotherapy", "jur-us-federal", LS.CLINICAL_TRIAL_ONLY, AP.CLINICAL_TRIAL_ENROLLMENT, OQ.HIGH,
      "US access primarily via clinical trials; not a broad commercial standard-of-care pathway yet.",
      "Trial eligibility.", "Trial oncology sites.", "FDA IND.",
      "Trial", "Watch BLA status.", "Domestic trials.", "Trial toxicities.",
      "US: trial pathway for photoimmunotherapy.",
      price=None, conf=CF.MODERATE, vol=VL.ACTIVE_FLUX),

    # Microdose psilocybin
    R("proc-psilocybin-microdose", "jur-us-or", LS.REGULATED_THERAPY, AP.LICENSED_PROVIDER_REGIME, OQ.HIGH,
      "Oregon licensed psilocybin services are full-dose facilitation model — not a formal microdose pharmacy. Personal microdosing still sits in gray/federal-illegal space outside service centers.",
      "Service centers for facilitated sessions; microdose retail not the OPS model.", "Licensed facilitators for sessions.", "OHA OPS.",
      "Service sessions $1.5k–3.5k; microdose supply not licensed retail", "Don't confuse OPS with microdose scripts.", "Open to non-residents for services.", "Federal Schedule I remains.",
      "Oregon: regulated full-dose services — not a microdose prescription market.",
      price=None, conf=CF.MODERATE, vol=VL.ACTIVE_FLUX),
    R("proc-psilocybin-microdose", "jur-nl", LS.UNREGULATED_PERMITTED, AP.PERSONAL_IMPORT, OQ.LOW,
      "Psilocybin truffles legal in NL smart shops — common microdose source for visitors/residents.",
      "Adult purchase of truffles.", "Smart shops.", "Dutch opium law truffle exception.",
      "$20–60/week truffles", "Legal truffle retail.", "Tourism-friendly.", "Variable dose; mental health risks if unscreened.",
      "Netherlands: easiest legal microdose-adjacent supply via truffles.",
      price=40, conf=CF.HIGH),
    R("proc-psilocybin-microdose", "jur-jm", LS.UNREGULATED_PERMITTED, AP.MEDICAL_TOURISM_CASH, OQ.MINIMAL,
      "Psilocybin mushrooms never scheduled; retreats may support microdose/ retreat hybrid models without medical licensing.",
      "Retreat screening variable.", "Retreat operators.", "No medical regulator for therapy.",
      "$20–100/week equivalent", "Often bundled in retreats.", "Tourism.", "No product testing mandate.",
      "Jamaica: unregulated legal mushrooms enable microdose access.",
      price=50, conf=CF.LOW),
    R("proc-psilocybin-microdose", "jur-us-federal", LS.PROHIBITED, AP.NONE, OQ.HIGH,
      "Psilocybin Schedule I federally; microdosing is illegal under federal law despite state/city reforms.",
      "None federally.", "None.", "DEA Schedule I.",
      "N/A legal market", "Underground only.", "N/A", "Federal criminal risk.",
      "US federal: microdosing prohibited.",
      price=None, conf=CF.HIGH),

    # Cord blood
    R("proc-cord-blood", "jur-us-federal", LS.FULLY_APPROVED, AP.STANDARD_PRESCRIPTION, OQ.HIGH,
      "FDA-regulated cord blood for approved hematopoietic transplants; unproven perinatal clinic infusions are enforcement targets.",
      "Transplant indications via transplant centers; avoid unproven autism/anti-aging clinic claims.", "FACT-accredited transplant programs.",
      "FDA BLA/cord blood regulations.", "Transplant insured when indicated; clinic $5k–25k unproven", "Distinguish approved transplant vs clinic marketing.",
      "Domestic transplant centers.", "GVHD/infection for transplants; unproven clinic risks.",
      "US: approved for transplant; unproven regenerative marketing is risky/illegal.",
      price=None, conf=CF.HIGH),
    R("proc-cord-blood", "jur-mx", LS.PHYSICIAN_DISCRETION_GRAY, AP.MEDICAL_TOURISM_CASH, OQ.MINIMAL,
      "Perinatal cell clinics market cord/Wharton's jelly products for many unproven indications.",
      "Cash-pay.", "Private regenerative clinics.", "Variable COFEPRIS enforcement.",
      "$5k–20k", "Quality opaque.", "Tourism.", "Unproven claims; infection risk.",
      "Mexico: regenerative cord-cell tourism — high diligence required.",
      price=10000, conf=CF.LOW),
    R("proc-cord-blood", "jur-sg", LS.FULLY_APPROVED, AP.STANDARD_PRESCRIPTION, OQ.HIGH,
      "Singapore high-standard transplant medicine; strict limits on unproven cell therapies.",
      "Transplant criteria.", "Academic hospitals.", "HSA.",
      "Hospital pricing / insurance", "Not a gray regenerative tourism hub.", "Regional referrals.", "Transplant risks managed.",
      "Singapore: legitimate transplant pathway; low tolerance for unproven clinics.",
      price=None, conf=CF.HIGH),

    # Tesamorelin
    R("proc-peptide-tesamorelin", "jur-us-federal", LS.FULLY_APPROVED, AP.STANDARD_PRESCRIPTION, OQ.HIGH,
      "Egrifta (tesamorelin) FDA-approved for HIV-associated lipodystrophy; specialty pharmacy; patient assistance important.",
      "HIV + excess abdominal fat per label.", "HIV specialists.", "FDA label.",
      "$3k–6k/mo list", "Assistance programs may reduce cost.", "Domestic.", "Glucose elevations; injection site reactions.",
      "US: labeled peptide drug for HIV lipodystrophy.",
      price=4500, basis="insured", conf=CF.HIGH),
    R("proc-peptide-tesamorelin", "jur-ca", LS.FULLY_APPROVED, AP.STANDARD_PRESCRIPTION, OQ.HIGH,
      "Tesamorelin available via Canadian specialty pathways for labeled HIV lipodystrophy where marketed.",
      "HIV specialist criteria.", "Specialty pharmacies.", "Health Canada.",
      "CAD high list", "Public/private coverage variable.", "Domestic.", "Metabolic monitoring.",
      "Canada: labeled access pathway where listed.",
      price=4000, conf=CF.MODERATE),

    # Baclofen AUD
    R("proc-baclofen-aud", "jur-fr", LS.APPROVED_OFF_LABEL, AP.OFF_LABEL_PRESCRIPTION, OQ.MEDIUM,
      "France has the most publicized high-dose baclofen AUD practice history (temporary recommendations/RTU-type pathways evolved over time).",
      "AUD diagnosis; specialist/addiction physician.", "Addiction medicine.", "ANSM history of baclofen AUD rules.",
      "€20–60/mo", "Mostly low drug cost.", "Domestic.", "Sedation, withdrawal if stopped abruptly.",
      "France: most established baclofen-AUD clinical culture.",
      price=35, conf=CF.MODERATE, vol=VL.ACTIVE_FLUX),
    R("proc-baclofen-aud", "jur-us-federal", LS.APPROVED_OFF_LABEL, AP.OFF_LABEL_PRESCRIPTION, OQ.MEDIUM,
      "Baclofen off-label for AUD used by some addiction clinicians; not first-line per US guidelines (naltrexone/acamprosate preferred).",
      "AUD; caution in renal impairment.", "Addiction medicine / primary care.", "FDA labeled for spasticity.",
      "$20–60/mo", "Cheap generic.", "Domestic.", "Sedation; abuse potential lower than many agents.",
      "US: off-label possible; not guideline first-line.",
      price=30, conf=CF.MODERATE),
    R("proc-baclofen-aud", "jur-de", LS.APPROVED_OFF_LABEL, AP.OFF_LABEL_PRESCRIPTION, OQ.MEDIUM,
      "Off-label baclofen for AUD under physician responsibility; specialty addiction care preferred.",
      "AUD assessment.", "Suchtmedizin / GP.", "Off-label AMG practice.",
      "€15–50/mo", "Low cost.", "Domestic.", "Class risks.",
      "Germany: off-label baclofen AUD possible in specialist hands.",
      price=25, conf=CF.MODERATE),

    # CJC/Ipa peptides
    R("proc-peptide-cjc-ipa", "jur-us-federal", LS.PHYSICIAN_DISCRETION_GRAY, AP.NONE, OQ.LOW,
      "Not FDA-approved for anti-aging. Many related secretagogue peptides face compounding restrictions; research chemical market is not medical care.",
      "No approved indication for wellness.", "Gray clinics / research vendors.", "FDA compounding enforcement flux.",
      "$150–500/mo gray market", "Quality unknown.", "Domestic gray.", "IGF-1 elevation risks; product authenticity.",
      "US: no clear lawful medical pathway for wellness secretagogues.",
      price=None, conf=CF.MODERATE, vol=VL.ACTIVE_FLUX),
    R("proc-peptide-cjc-ipa", "jur-mx", LS.PHYSICIAN_DISCRETION_GRAY, AP.MEDICAL_TOURISM_CASH, OQ.MINIMAL,
      "Peptide clinics commonly market CJC/ipa stacks cash-pay.",
      "Cash-pay.", "Wellness clinics.", "Minimal.",
      "$100–300/mo", "Cheap; quality risk.", "Tourism.", "Unverified products.",
      "Mexico: easy peptide clinic access — buyer beware.",
      price=200, conf=CF.LOW),
    R("proc-peptide-cjc-ipa", "jur-th", LS.PHYSICIAN_DISCRETION_GRAY, AP.MEDICAL_TOURISM_CASH, OQ.MINIMAL,
      "Anti-aging clinics in Thailand market GH secretagogue peptides.",
      "Tourist packages.", "Private clinics.", "Variable.",
      "$120–350/mo", "Tourism pricing.", "Bangkok etc.", "Authenticity risk.",
      "Thailand: wellness peptide tourism market.",
      price=220, conf=CF.LOW),

    # Prazosin
    R("proc-prazosin-ptsd", "jur-us-federal", LS.APPROVED_OFF_LABEL, AP.OFF_LABEL_PRESCRIPTION, OQ.HIGH,
      "Prazosin inexpensive generic; widely used off-label for PTSD nightmares including VA practice despite mixed large-trial results.",
      "PTSD with nightmares; BP monitoring.", "Primary care, psych, VA.", "FDA HTN label; off-label PTSD use.",
      "$5–30/mo", "Very cheap.", "Domestic.", "Orthostatic hypotension first doses.",
      "US: easy cheap off-label access.",
      price=15, conf=CF.HIGH),
    R("proc-prazosin-ptsd", "jur-uk", LS.APPROVED_OFF_LABEL, AP.OFF_LABEL_PRESCRIPTION, OQ.HIGH,
      "Prazosin available; PTSD nightmare use off-label under specialist/GP judgment.",
      "Clinical PTSD.", "GPs/specialists.", "MHRA.",
      "$10–25/mo", "NHS possible.", "Domestic.", "Hypotension.",
      "UK: inexpensive off-label option.",
      price=15, conf=CF.MODERATE),
    R("proc-prazosin-ptsd", "jur-ca", LS.APPROVED_OFF_LABEL, AP.OFF_LABEL_PRESCRIPTION, OQ.HIGH,
      "Common off-label PTSD nightmare treatment; covered when prescribed.",
      "PTSD symptoms.", "Family/specialty physicians.", "Health Canada drug.",
      "CAD $10–30/mo", "Formulary cheap.", "Domestic.", "Hypotension.",
      "Canada: easy access, low cost.",
      price=12, conf=CF.HIGH),

    # Low-dose lithium
    R("proc-low-dose-lithium", "jur-us-federal", LS.PHYSICIAN_DISCRETION_GRAY, AP.COMPOUNDING, OQ.MEDIUM,
      "Prescription lithium carbonate is FDA-approved for bipolar; low-dose protocols may use compounded microdoses. OTC lithium orotate is a supplement gray area with weak regulation.",
      "Baseline renal/thyroid labs advised even at low dose.", "Prescriber for carbonate; OTC orotate unsupervised risk.",
      "FDA drug vs DSHEA supplement split.", "$10–40/mo", "Labs extra.", "Domestic.", "Thyroid/renal effects still possible.",
      "US: microdose via Rx compounding or unregulated orotate supplements.",
      price=20, conf=CF.MODERATE),
    R("proc-low-dose-lithium", "jur-de", LS.APPROVED_OFF_LABEL, AP.OFF_LABEL_PRESCRIPTION, OQ.HIGH,
      "Pharmaceutical lithium under prescription; low-dose neuroprotective use is off-label physician practice — not OTC culture like US orotate.",
      "Labs monitoring.", "Physicians.", "High pharmacy standards.",
      "€10–30/mo", "Rx only.", "Domestic.", "Monitoring still wise.",
      "Germany: Rx lithium only; off-label microdose clinician-led.",
      price=18, conf=CF.MODERATE),

    # SIBO rifaximin
    R("proc-fecal-sibo", "jur-us-federal", LS.FULLY_APPROVED, AP.STANDARD_PRESCRIPTION, OQ.HIGH,
      "Rifaximin FDA-approved for IBS-D and HE; used for SIBO off-label. Price is the main US friction (brand Xifaxan).",
      "IBS-D label or SIBO clinical diagnosis.", "GI / primary care.", "FDA.",
      "$1k–2.5k/course brand", "Insurance often fails for SIBO specifically.", "Domestic.", "C. diff rare; resistance concerns.",
      "US: legal access easy; cost is the arbitrage.",
      price=1800, conf=CF.HIGH),
    R("proc-fecal-sibo", "jur-in", LS.FULLY_APPROVED, AP.STANDARD_PRESCRIPTION, OQ.MEDIUM,
      "Rifaximin generics widely available at far lower cost.",
      "Physician Rx.", "Pharmacies.", "CDSCO.",
      "$30–100/course", "Major price arbitrage vs US brand.", "Easy access.", "Prefer known manufacturers.",
      "India: low-cost rifaximin for SIBO protocols.",
      price=50, conf=CF.HIGH),
    R("proc-fecal-sibo", "jur-mx", LS.FULLY_APPROVED, AP.STANDARD_PRESCRIPTION, OQ.MEDIUM,
      "Rifaximin available in Mexican pharmacies cheaper than US brand cash price.",
      "Physician Rx norms.", "Farmacias.", "COFEPRIS.",
      "$50–150/course", "Border pharmacy tourism common.", "Tourism.", "Confirm product authenticity.",
      "Mexico: cheaper rifaximin access for SIBO protocols.",
      price=80, conf=CF.MODERATE),

    # GLP-1 addiction emerging
    R("proc-glp1-addiction", "jur-us-federal", LS.APPROVED_OFF_LABEL, AP.OFF_LABEL_PRESCRIPTION, OQ.MEDIUM,
      "Semaglutide/tirzepatide prescribed off-label by some addiction/psych clinics for AUD interest; labeled for T2D/obesity only.",
      "Obesity/T2D labels easier for coverage; pure AUD off-label cash-pay.", "Prescribers + specialty pharmacy.",
      "FDA labels don't include SUD.", "$200–1,400/mo", "Coverage rare for pure AUD.", "Domestic.", "GI side effects; thyroid boxed warning class.",
      "US: emerging off-label; evidence still maturing.",
      price=900, conf=CF.MODERATE, vol=VL.ACTIVE_FLUX),
    R("proc-glp1-addiction", "jur-uk", LS.APPROVED_OFF_LABEL, AP.OFF_LABEL_PRESCRIPTION, OQ.MEDIUM,
      "GLP-1s NHS-restricted mainly for obesity/diabetes criteria; pure addiction use private off-label if at all.",
      "NHS obesity/diabetes pathways or private.", "Specialists/private.", "MHRA + NICE obesity rules.",
      "Private high / NHS if obesity criteria", "Addiction-only unlikely NHS.", "Domestic.", "Class risks.",
      "UK: obesity/diabetes pathway first; addiction off-label private only.",
      price=300, conf=CF.LOW, vol=VL.ACTIVE_FLUX),

    # Dendritic vaccines
    R("proc-dendritic-vaccine", "jur-us-federal", LS.FULLY_APPROVED, AP.STANDARD_PRESCRIPTION, OQ.HIGH,
      "Sipuleucel-T (Provenge) FDA-approved for mCRPC. Other personalized DC vaccines mostly trial or unproven clinic products.",
      "mCRPC label for Provenge; others trial.", "Authorized infusion centers for Provenge.", "FDA.",
      "$100k+ for Provenge course historical", "Insurance for labeled use.", "Domestic specialty.", "Infusion reactions.",
      "US: one approved DC vaccine (prostate); beware unproven DC clinics.",
      price=100000, basis="insured", conf=CF.HIGH),
    R("proc-dendritic-vaccine", "jur-mx", LS.PHYSICIAN_DISCRETION_GRAY, AP.MEDICAL_TOURISM_CASH, OQ.MINIMAL,
      "Cancer clinics market personalized DC vaccines with variable science and quality control.",
      "Cash-pay oncology tourism.", "Private clinics.", "Minimal outcome transparency.",
      "$20k–80k packages", "Claims often exceed evidence.", "Tourism.", "Delay of proven care risk.",
      "Mexico: DC vaccine tourism — high scrutiny required.",
      price=40000, conf=CF.LOW),
    R("proc-dendritic-vaccine", "jur-de", LS.CLINICAL_TRIAL_ONLY, AP.CLINICAL_TRIAL_ENROLLMENT, OQ.HIGH,
      "Academic DC vaccine research; commercial unproven clinics less tolerated than in tourism markets.",
      "Trial criteria.", "University oncology.", "PEI/EMA trial rules.",
      "Trial", "Prefer academic trials.", "Domestic EU.", "Trial risks.",
      "Germany: trial/academic pathway preferred.",
      price=None, conf=CF.MODERATE),

    # Uterine transplant
    R("proc-uterine-transplant", "jur-us-federal", LS.CLINICAL_TRIAL_ONLY, AP.CLINICAL_TRIAL_ENROLLMENT, OQ.HIGH,
      "Uterus transplant available only at select US research/clinical programs (not routine care).",
      "AUFI; extensive medical/psych screening; research protocols often.", "Transplant + REI programs (e.g. select academic centers).",
      "IRB/transplant regulation.", "$200k–500k+", "Rarely fully insured.", "Must relocate near center months.", "Immunosuppression; surgical morbidity.",
      "US: highly limited specialized programs only.",
      price=300000, conf=CF.MODERATE),
    R("proc-uterine-transplant", "jur-se", LS.CLINICAL_TRIAL_ONLY, AP.CLINICAL_TRIAL_ENROLLMENT, OQ.HIGH,
      "Sweden pioneered clinical uterus transplantation research (Gothenburg).",
      "Research criteria.", "Academic transplant programs.", "MPA/ethical boards.",
      "Research pathway", "Not general medical tourism product.", "Limited slots.", "Major surgery risks.",
      "Sweden: historic research leadership; not open tourism.",
      price=None, conf=CF.MODERATE),

    # VNS
    R("proc-vns-depression", "jur-us-federal", LS.FULLY_APPROVED, AP.STANDARD_PRESCRIPTION, OQ.HIGH,
      "Implantable VNS FDA-approved for chronic TRD (and epilepsy). Requires surgical implant; payer hurdles common for depression indication.",
      "Chronic TRD criteria; surgical clearance.", "Neurosurgery + psychiatry programs.", "FDA PMA devices.",
      "$20k–40k implant pathway", "Insurance denials common for depression indication.", "Specialty centers.", "Surgical infection; voice changes; battery replacement.",
      "US: approved but access friction for depression VNS.",
      price=30000, basis="insured", conf=CF.MODERATE),
    R("proc-vns-depression", "jur-de", LS.FULLY_APPROVED, AP.STANDARD_PRESCRIPTION, OQ.HIGH,
      "VNS available for epilepsy widely; depression indication more selective with specialist centers.",
      "Specialist criteria.", "Neurosurgery centers.", "G-BA device context.",
      "Public cover more for epilepsy than depression", "Indication matters.", "Domestic.", "Surgical risks.",
      "Germany: strong epilepsy VNS; depression more selective.",
      price=25000, conf=CF.MODERATE),

    # ECMO - limited rows
    R("proc-ecmo-bridge", "jur-us-federal", LS.FULLY_APPROVED, AP.STANDARD_PRESCRIPTION, OQ.HIGH,
      "ECMO standard at high-volume US centers for refractory shock/ARDS; not elective tourism.",
      "Critical illness criteria; center capability.", "ELSO centers.", "Hospital credentialing.",
      "$100k–500k+/run", "Insured in acute care when indicated.", "Transfer to ECMO center.", "Bleeding, thrombosis, infection.",
      "US: capacity/expertise arbitrage between hospitals — not legal gray market.",
      price=250000, basis="insured", conf=CF.HIGH),
    R("proc-ecmo-bridge", "jur-de", LS.FULLY_APPROVED, AP.STANDARD_PRESCRIPTION, OQ.HIGH,
      "High ECMO capacity in German tertiary hospitals; regional transfer networks.",
      "Critical care criteria.", "University ICUs.", "Hospital standards.",
      "Public acute care", "Not tourism product.", "Domestic/EU transfer.", "ECMO complications.",
      "Germany: high-capacity legitimate ECMO centers.",
      price=200000, basis="insured", conf=CF.HIGH),

    # SS-31
    R("proc-peptide-ss31", "jur-us-federal", LS.CLINICAL_TRIAL_ONLY, AP.CLINICAL_TRIAL_ENROLLMENT, OQ.HIGH,
      "Elamipretide and related mitochondrial peptides primarily clinical trial / expanded access; not general wellness peptides.",
      "Trial or expanded access criteria for rare disease.", "Trial sites.", "FDA IND.",
      "Trial", "Commercial approval pending indications.", "Domestic trials.", "Investigational risks.",
      "US: trial/expanded access — not anti-aging clinic standard.",
      price=None, conf=CF.MODERATE, vol=VL.ACTIVE_FLUX),
    R("proc-peptide-ss31", "jur-eu",  # invalid - use de
      LS.CLINICAL_TRIAL_ONLY, AP.CLINICAL_TRIAL_ENROLLMENT, OQ.HIGH,
      "placeholder", "x", "x", "x", "x", "x", "x", "x", "x"),
]

ACCESS_THERAPIES_EXPANSION = [
    r for r in ACCESS_THERAPIES_EXPANSION
    if r.get("jurisdiction_id") != "jur-eu" and r.get("access_pathway_details") != "placeholder"
]

ACCESS_THERAPIES_EXPANSION += [
    R("proc-peptide-ss31", "jur-de", LS.CLINICAL_TRIAL_ONLY, AP.CLINICAL_TRIAL_ENROLLMENT, OQ.HIGH,
      "European mitochondrial peptide programs mainly via clinical trials.",
      "Trial criteria.", "Academic centers.", "EMA/national trial oversight.",
      "Trial", "Not commercial wellness.", "EU trials.", "Investigational.",
      "Germany/EU: trial pathway for mitochondrial peptides.",
      price=None, conf=CF.MODERATE),
    R("proc-car-t-solid", "jur-us-federal", LS.CLINICAL_TRIAL_ONLY, AP.CLINICAL_TRIAL_ENROLLMENT, OQ.HIGH,
      "Solid-tumor CAR-T/TCR almost entirely clinical trials at major US centers.",
      "Trial inclusion.", "Academic cellular therapy centers.", "FDA IND.",
      "Trial (drug often free; care costs may apply)", "Not commercial SOC.", "Center travel.", "CRS/ICANS risk class.",
      "US: trials only for solid-tumor CAR-T.",
      price=None, conf=CF.HIGH),
    R("proc-car-t-solid", "jur-cn",  # no china - use kr/jp
      LS.CLINICAL_TRIAL_ONLY, AP.CLINICAL_TRIAL_ENROLLMENT, OQ.MEDIUM,
      "placeholder", "x", "x", "x", "x", "x", "x", "x", "x"),
]

ACCESS_THERAPIES_EXPANSION = [
    r for r in ACCESS_THERAPIES_EXPANSION
    if r.get("jurisdiction_id") != "jur-cn" and r.get("access_pathway_details") != "placeholder"
]

ACCESS_THERAPIES_EXPANSION += [
    R("proc-car-t-solid", "jur-kr", LS.CLINICAL_TRIAL_ONLY, AP.CLINICAL_TRIAL_ENROLLMENT, OQ.HIGH,
      "Active cellular therapy trial ecosystem; solid-tumor CAR programs at research hospitals.",
      "Trial criteria.", "Research hospitals.", "MFDS trials.",
      "Trial", "Some medical travel for trials.", "Seoul research hubs.", "Cellular therapy toxicities.",
      "Korea: strong trial infrastructure for experimental cellular therapy.",
      price=None, conf=CF.MODERATE),
    R("proc-car-t-solid", "jur-jp", LS.CLINICAL_TRIAL_ONLY, AP.CLINICAL_TRIAL_ENROLLMENT, OQ.HIGH,
      "Japan regenerative/cell therapy trial framework for solid tumors.",
      "Trial protocols.", "Academic hospitals.", "PMDA.",
      "Trial", "Regenerative act may enable conditional paths later.", "Domestic.", "Trial risks.",
      "Japan: trial/conditional regenerative pathways possible.",
      price=None, conf=CF.MODERATE, vol=VL.ACTIVE_FLUX),
    R("proc-tms-ocd", "jur-us-federal", LS.FULLY_APPROVED, AP.STANDARD_PRESCRIPTION, OQ.HIGH,
      "Deep TMS FDA-cleared for OCD; specialty clinics.",
      "OCD diagnosis; failed standard treatments often required by payers.", "TMS clinics / psychiatry.",
      "FDA device clearance.", "$8k–18k/course", "Prior auth common.", "Domestic.", "Standard TMS risks.",
      "US: device-cleared OCD TMS pathway.",
      price=12000, basis="insured", conf=CF.HIGH),
    R("proc-tms-ocd", "jur-il", LS.FULLY_APPROVED, AP.STANDARD_PRESCRIPTION, OQ.HIGH,
      "Israeli deep TMS development heritage; clinical availability for OCD/depression protocols.",
      "Specialist assessment.", "Psychiatry clinics.", "Ministry of Health devices.",
      "$6k–14k est.", "Regional expertise.", "Medical travel possible.", "Standard risks.",
      "Israel: notable TMS clinical ecosystem.",
      price=9000, conf=CF.MODERATE),
]


def all_procedures_expansion():
    return list(PROCEDURES_EXPANSION)


def all_access_therapies_expansion():
    seen = set()
    out = []
    for r in ACCESS_THERAPIES_EXPANSION:
        key = (r["procedure_id"], r["jurisdiction_id"])
        if key in seen:
            continue
        seen.add(key)
        out.append(r)
    return out
