"""Practitioner-side setup requirements: what it takes to offer a therapy.

Defaults are procedure-level (modality baseline). Jurisdiction-specific rows
override/enrich for known regulated programs (Oregon OPS, TGA AP, REMS, etc.).
Informational only — not legal advice.
"""


def S(
    summary,
    *,
    licenses=None,
    facility=None,
    training=None,
    staffing=None,
    product_source=None,
    regulatory_steps=None,
    capital_notes=None,
    ongoing_compliance=None,
    difficulty="Moderate",
    notes=None,
):
    return {
        "summary": summary,
        "difficulty": difficulty,  # Low | Moderate | High | Extreme
        "licenses": licenses or [],
        "facility": facility or [],
        "training": training or [],
        "staffing": staffing or [],
        "product_source": product_source or [],
        "regulatory_steps": regulatory_steps or [],
        "capital_notes": capital_notes,
        "ongoing_compliance": ongoing_compliance or [],
        "notes": notes,
    }


# ── Procedure-level defaults (any jurisdiction starting point) ───────────────

PROCEDURE_SETUP_DEFAULTS = {
    "proc-psilocybin-trd": S(
        "Requires a jurisdiction that permits facilitated psilocybin services or medical prescribing — cannot lawfully open a US federal retail program.",
        difficulty="High",
        licenses=["Local service-center / facilitator license where a program exists", "Business entity registration"],
        facility=["Dedicated administration space for multi-hour sessions", "Emergency protocols / first aid"],
        training=["Approved facilitator training (jurisdiction-specific hours + practicum)"],
        staffing=["Licensed facilitators; medical consultation pathway for screening"],
        product_source=["Licensed manufacturer / testing lab product only (regulated markets)"],
        regulatory_steps=["Apply for service-center + facilitator licenses", "SOPs for preparation, administration, integration"],
        capital_notes="Oregon-class programs: license fees, security, testing, and staffing are substantial fixed costs.",
        ongoing_compliance=["Client data reporting where required", "Adverse event logs", "Product chain-of-custody"],
    ),
    "proc-psilocybin-eol": S(
        "Same regulated facilitator model as other psilocybin services; palliative specialization is clinical, not always a separate license.",
        difficulty="High",
        licenses=["Facilitator / service-center license in regulated states"],
        facility=["Quiet administration rooms; medical clearance pathway for frail clients"],
        training=["Facilitator training + recommended palliative/end-of-life competency"],
        staffing=["Facilitators; optional nursing backup"],
        product_source=["Licensed tested product"],
        regulatory_steps=["State program licensure"],
        capital_notes="Similar to general OPS centers.",
        ongoing_compliance=["Screening for medical stability", "Informed consent"],
    ),
    "proc-mdma-ptsd": S(
        "Where not approved, only trial or special-access medical frameworks apply; requires psychiatrist-led controlled-substance infrastructure.",
        difficulty="Extreme",
        licenses=["Medical license (psychiatry preferred)", "Controlled-substance prescribing authority", "Ethics / special-access authorization where required"],
        facility=["Medical monitoring capability; crash cart; quiet therapy rooms"],
        training=["MDMA-AT protocol training (MAPS-style or jurisdiction equivalent)"],
        staffing=["Two therapists per dosing session typical; medical coverage"],
        product_source=["GMP MDMA from authorized supplier — not street product"],
        regulatory_steps=["Special access / authorized prescriber / IND trial as applicable"],
        capital_notes="High: medical staff, monitoring, GMP product, multi-session therapy model.",
        ongoing_compliance=["Controlled-drug logs", "Adverse event reporting"],
    ),
    "proc-ketamine-depression": S(
        "US pathway: medical license + controlled-substance registration; Spravato needs REMS site certification; IV is off-label clinic model.",
        difficulty="Moderate",
        licenses=["MD/DO/NP (state-dependent) medical license", "DEA registration (Schedule III)"],
        facility=["Monitoring chairs/beds; BP/SpO2; emergency equipment; private recovery space"],
        training=["Ketamine clinic protocols; ACLS recommended", "Spravato REMS training if offering esketamine"],
        staffing=["Prescriber + monitoring staff for 1–2 hours post-dose"],
        product_source=["Licensed pharmacy ketamine; Spravato via specialty pharmacy/REMS"],
        regulatory_steps=["State medical board compliance", "REMS enrollment for Spravato"],
        capital_notes="Lower than inpatient psych; build-out for monitoring rooms and staffing is main cost.",
        ongoing_compliance=["Controlled-substance inventory", "Vitals documentation", "Informed consent for off-label IV"],
    ),
    "proc-ketamine-assisted-psychotherapy": S(
        "Same controlled-substance base as ketamine clinics plus integrated psychotherapy model and dual clinical governance.",
        difficulty="Moderate",
        licenses=["Prescriber with controlled-substance authority", "Therapist licensure (LCSW/LMFT/psychologist) as applicable"],
        facility=["Therapy rooms suitable for dosing + integration"],
        training=["KAP model training; preparation/integration competency"],
        staffing=["Prescriber + therapist(s); clear scope boundaries"],
        product_source=["Pharmacy ketamine"],
        regulatory_steps=["Clinic protocols; telehealth rules if hybrid"],
        capital_notes="Similar to ketamine clinic + therapy staffing overhead.",
        ongoing_compliance=["Dual charting of medical + therapy notes", "Boundary/ethics policies"],
    ),
    "proc-ibogaine-addiction": S(
        "Not a standard US medical pathway; where offered, cardiac-capable medical detox infrastructure is non-negotiable.",
        difficulty="Extreme",
        licenses=["Local medical facility authorization", "Physician on staff"],
        facility=["Continuous cardiac monitoring (telemetry)", "Defibrillator/crash cart", "Ability to transfer to hospital"],
        training=["Ibogaine-specific protocols; emergency cardiac response"],
        staffing=["MD present during peak risk window; nursing 24h"],
        product_source=["Pharmaceutical-grade alkaloid sourcing with QC"],
        regulatory_steps=["Local health authority registration; informed consent frameworks"],
        capital_notes="High medical infrastructure relative to 'retreat' marketing claims.",
        ongoing_compliance=["Pre-treatment ECG/QTc/labs mandatory", "Mortality risk disclosure"],
        notes="Many jurisdictions prohibit or leave in gray zone — legal setup may be impossible.",
    ),
    "proc-gene-crispr": S(
        "Only as authorized gene-therapy center or trial site — not a private outpatient startup.",
        difficulty="Extreme",
        licenses=["Hospital institutional license", "Manufacturer-authorized treatment center status"],
        facility=["Apheresis", "Cell processing coordination", "Inpatient/ICU for conditioning complications"],
        training=["Manufacturer REMS/center training", "Transplant/cell therapy competency"],
        staffing=["Hematology, ICU, pharmacy, cell lab coordination"],
        product_source=["Manufacturer (e.g. Casgevy) only"],
        regulatory_steps=["Center certification with manufacturer", "IRB if trial", "Payer contracts"],
        capital_notes="Multi-million infrastructure; usually existing academic/transplant centers only.",
        ongoing_compliance=["Long-term follow-up registries", "Adverse event reporting to manufacturer/FDA"],
    ),
    "proc-gene-aa9": S(
        "Specialized pediatric/gene-therapy center with manufacturer network membership.",
        difficulty="Extreme",
        licenses=["Hospital + specialty pharmacy agreements"],
        facility=["Infusion capability; PICU backup; isolation as required"],
        training=["Zolgensma/AAV administration training", "Liver toxicity monitoring protocols"],
        staffing=["Pediatric neurology/genetics + nursing + pharmacy"],
        product_source=["Manufacturer cold-chain only"],
        regulatory_steps=["Become authorized treatment center", "Payer prior auth infrastructure"],
        capital_notes="Only viable inside tertiary children's hospitals.",
        ongoing_compliance=["Steroid protocols", "Long-term follow-up"],
    ),
    "proc-stem-car-t": S(
        "FACT/JACIE-level cell therapy center with REMS certification per product.",
        difficulty="Extreme",
        licenses=["Hospital", "REMS-certified CAR-T center per product"],
        facility=["Apheresis", "Inpatient beds", "ICU", "tocilizumab stocked"],
        training=["CRS/ICANS management training for entire team"],
        staffing=["Cellular therapy MD, APPs, ICU, neurology on-call, pharmacy"],
        product_source=["Commercial CAR-T manufacturers only"],
        regulatory_steps=["REMS enrollment", "Payer contracts", "Data reporting"],
        capital_notes="Only existing transplant/cell therapy programs; nine-figure system investments.",
        ongoing_compliance=["15-year follow-up commitments", "Secondary malignancy monitoring"],
    ),
    "proc-stem-msc": S(
        "In strict jurisdictions: IND/trial or approved product only. In gray markets: local clinic license + informed consent — quality bar is the risk.",
        difficulty="High",
        licenses=["Medical license", "Facility registration (varies wildly by country)"],
        facility=["Sterile procedure rooms; cell processing if point-of-care"],
        training=["Regenerative procedure training; infection control"],
        staffing=["Physician + nursing"],
        product_source=["cGMP characterized product preferred; avoid uncharacterized vials"],
        regulatory_steps=["Confirm local cell-therapy rules before marketing claims"],
        capital_notes="Gray clinics underinvest in QC — legitimate setup costs more.",
        ongoing_compliance=["No unproven disease claims in regulated markets", "Traceability of cell lots"],
    ),
    "proc-stem-exosome": S(
        "US: generally not a lawful commercial therapeutic pathway outside trials; marketing unapproved exosomes is an FDA enforcement target.",
        difficulty="Extreme",
        licenses=["Would require IND/BLA path for therapeutic claims in US"],
        facility=["cGMP manufacturing if developing a product"],
        training=["Cell/EV science; regulatory affairs"],
        staffing=["Scientific + clinical team for trials"],
        product_source=["Investigational product under IND"],
        regulatory_steps=["FDA IND or foreign equivalent", "IRB"],
        capital_notes="Real therapeutic path is biotech-scale, not med-spa scale.",
        ongoing_compliance=["No disease claims without approval"],
        notes="Aesthetic gray markets exist but are high enforcement/liability risk in US.",
    ),
    "proc-stem-nsc": S(
        "Investigational only in almost all places — hospital trial infrastructure required.",
        difficulty="Extreme",
        licenses=["Trial site authorization", "Neurosurgery privileges"],
        facility=["OR/neurosurgery + ICU", "Cell processing under trial protocol"],
        training=["Protocol-specific investigator training"],
        staffing=["Neurosurgery, neurology, research coordinators"],
        product_source=["Trial sponsor product"],
        regulatory_steps=["IND/CTA + IRB/ethics"],
        capital_notes="Academic medical center only.",
        ongoing_compliance=["GCP, DSMB reporting"],
    ),
    "proc-cord-blood": S(
        "Approved transplant: FACT-accredited program. Unproven clinic infusions: usually unlawful disease claims in US.",
        difficulty="Extreme",
        licenses=["Transplant program accreditation for legitimate HCT"],
        facility=["BMT unit standards"],
        training=["Transplant fellowships / FACT standards"],
        staffing=["Transplant team"],
        product_source=["Licensed cord blood banks for HCT"],
        regulatory_steps=["FACT/JACIE; FDA cord blood regs"],
        capital_notes="Hospital transplant program economics.",
        ongoing_compliance=["Outcome reporting"],
    ),
    "proc-maid": S(
        "Only in jurisdictions with explicit statutes; requires dual assessments and reporting — not a private 'clinic product' in isolation.",
        difficulty="High",
        licenses=["Medical or NP license as statute allows", "Often institutional privileging"],
        facility=["Clinical setting capable of IV or oral self-administration protocols"],
        training=["MAID assessment competency; capacity evaluation"],
        staffing=["Two independent assessors typical", "Pharmacy for meds"],
        product_source=["Regulated lethal medication supply under protocol"],
        regulatory_steps=["Statute-mandated forms, waiting periods, reporting to ministry/registry"],
        capital_notes="Low capital vs high legal/process burden; often public system integrated.",
        ongoing_compliance=["Mandatory case reporting", "Conscientious objection referral rules"],
    ),
    "proc-repro-ivf": S(
        "Licensed fertility clinic with embryology lab meeting national ART standards.",
        difficulty="High",
        licenses=["Medical (REI preferred)", "Lab CLIA/equivalent", "ART clinic registration"],
        facility=["IVF lab (culture, cryo)", "Procedure rooms", "Andrology"],
        training=["REI / embryologist certification"],
        staffing=["REI, embryologists, nurses, counselors"],
        product_source=["Meds via specialty pharmacy; lab consumables"],
        regulatory_steps=["CDC/SART reporting in US; national ART registers elsewhere"],
        capital_notes="Multi-million lab build-out typical.",
        ongoing_compliance=["Success-rate reporting", "Tissue storage rules", "Embryo disposition law compliance"],
    ),
    "proc-repro-surrogacy": S(
        "Requires fertility clinic + independent legal counsel framework; commercial vs altruistic rules dominate setup.",
        difficulty="High",
        licenses=["ART clinic license", "Agency licensing where required"],
        facility=["IVF partner clinic"],
        training=["Third-party reproduction coordination"],
        staffing=["Clinic + agency case managers + counsel"],
        product_source=["N/A (service coordination)"],
        regulatory_steps=["Parentage order pathway", "Expense reimbursement compliance (altruistic models)"],
        capital_notes="Legal and agency infrastructure more than hardware.",
        ongoing_compliance=["Independent counsel for surrogate", "Escrow for expenses"],
    ),
    "proc-egg-freezing": S(
        "Same ART clinic infrastructure as IVF with vitrification capability.",
        difficulty="High",
        licenses=["ART clinic + lab"],
        facility=["Stim monitoring + egg retrieval OR + cryo storage"],
        training=["Embryology vitrification competency"],
        staffing=["REI + embryology"],
        product_source=["Stim meds; cryo tanks monitored"],
        regulatory_steps=["Storage duration rules; consent for gametes"],
        capital_notes="Add-on to existing IVF lab most common.",
        ongoing_compliance=["Tank alarm systems", "Long-term storage contracts"],
    ),
    "proc-mito-replacement": S(
        "Only viable under explicit statute (e.g. UK HFEA license) — not a general IVF add-on elsewhere.",
        difficulty="Extreme",
        licenses=["HFEA (or equivalent) mitochondrial donation license"],
        facility=["Advanced embryology micromanipulation lab"],
        training=["Specialist mitochondrial donation techniques"],
        staffing=["Highly specialized embryologists + genetics counseling"],
        product_source=["Donor oocytes under licensed pathway"],
        regulatory_steps=["License application with outcome follow-up plan"],
        capital_notes="Only a few centers globally.",
        ongoing_compliance=["Long-term child follow-up commitments"],
    ),
    "proc-uterine-transplant": S(
        "Transplant + REI joint program; research or highly specialized clinical program only.",
        difficulty="Extreme",
        licenses=["Transplant center + IRB/ethics"],
        facility=["Transplant OR, immunosuppression clinic, high-risk OB"],
        training=["Uterus transplant surgical protocols"],
        staffing=["Transplant surgery, REI, maternal-fetal medicine, psych"],
        product_source=["Living/deceased donor organ pathway"],
        regulatory_steps=["Protocol approval; often research initially"],
        capital_notes="Academic transplant center only.",
        ongoing_compliance=["Immunosuppression monitoring; graft explant planning"],
    ),
    "proc-tms-depression": S(
        "Outpatient neurostimulation clinic under physician oversight with device clearance compliance.",
        difficulty="Moderate",
        licenses=["Physician medical license; device operator under supervision rules"],
        facility=["TMS suite; seizure response plan"],
        training=["Manufacturer device training; TMS fellowship/certificate preferred"],
        staffing=["Psychiatrist + TMS technicians"],
        product_source=["FDA/CE-cleared TMS device purchase/lease"],
        regulatory_steps=["Payer enrollment; prior auth workflows"],
        capital_notes="Device $50k–100k+ class capital; room build-out.",
        ongoing_compliance=["Maintenance calibration", "Outcome tracking for payers"],
    ),
    "proc-tms-ocd": S(
        "Deep TMS / OCD protocols require appropriate coil/system and psychiatric program.",
        difficulty="Moderate",
        licenses=["Medical license"],
        facility=["Deep TMS capable suite"],
        training=["Device-specific OCD protocol training"],
        staffing=["Psychiatrist + techs"],
        product_source=["Cleared deep TMS system"],
        regulatory_steps=["Medical necessity documentation for OCD label"],
        capital_notes="Higher than standard figure-8 TMS if deep system.",
        ongoing_compliance=["Protocol adherence logs"],
    ),
    "proc-dbs-parkinson": S(
        "Functional neurosurgery program inside a hospital — not a standalone clinic.",
        difficulty="Extreme",
        licenses=["Hospital privileges neurosurgery + neurology"],
        facility=["Stereotactic OR, ICU, programming clinic"],
        training=["DBS surgical fellowship-level experience"],
        staffing=["Neurosurgery, movement-disorder neurology, programming team"],
        product_source=["Medtronic/Boston Scientific/Abbott DBS systems"],
        regulatory_steps=["Device center agreements; payer authorization"],
        capital_notes="Hospital capital budget only.",
        ongoing_compliance=["Infection surveillance; long-term programming"],
    ),
    "proc-fus-tremor": S(
        "Requires MRI-guided focused ultrasound suite and neurosurgery/neuroradiology program.",
        difficulty="Extreme",
        licenses=["Hospital imaging + neurosurgery privileges"],
        facility=["MRI-compatible FUS system (e.g. Exablate)"],
        training=["Manufacturer proctoring"],
        staffing=["Neurosurgery, neuroradiology, physics"],
        product_source=["Insightec or equivalent system"],
        regulatory_steps=["Certificate of need / hospital capital approval often"],
        capital_notes="Multi-million device install.",
        ongoing_compliance=["Outcomes registry participation often"],
    ),
    "proc-vns-depression": S(
        "Implanting neurosurgery + psychiatric follow-up program; payer hurdles for depression indication.",
        difficulty="High",
        licenses=["Surgical privileges; device implant training"],
        facility=["OR + outpatient programming"],
        training=["VNS implant and titration training"],
        staffing=["Neurosurgery + psychiatry"],
        product_source=["LivaNova or current approved system"],
        regulatory_steps=["Prior auth infrastructure critical for depression"],
        capital_notes="Surgical program overhead.",
        ongoing_compliance=["Battery replacement pathway"],
    ),
    "proc-pef-ablation": S(
        "Hospital EP lab with PFA-capable capital equipment and trained electrophysiologists.",
        difficulty="Extreme",
        licenses=["Hospital EP privileges"],
        facility=["Cath/EP lab with mapping and PFA generator"],
        training=["PFA proctoring / EP fellowship"],
        staffing=["EP physicians, techs, anesthesia"],
        product_source=["Boston Scientific Farapulse, Medtronic PulseSelect, etc."],
        regulatory_steps=["Hospital value analysis committee for new platform"],
        capital_notes="Hospital-level capital + disposable economics.",
        ongoing_compliance=["Complication reporting; AF outcome tracking"],
    ),
    "proc-lecanemab": S(
        "Infusion + MRI monitoring Alzheimer's program with APOE counseling capacity.",
        difficulty="High",
        licenses=["Medical practice; infusion suite registration as required"],
        facility=["Infusion chairs; rapid MRI access; ARIA management pathway"],
        training=["ARIA recognition; appropriate use criteria"],
        staffing=["Neurology/geriatrics + infusion nursing + radiology partnership"],
        product_source=["Specialty pharmacy / manufacturer distribution"],
        regulatory_steps=["CMS registry / coverage requirements where applicable", "Payer contracts"],
        capital_notes="Imaging partnership is the bottleneck more than drug fridge.",
        ongoing_compliance=["Scheduled safety MRIs", "Registry data submission"],
    ),
    "proc-proton-therapy": S(
        "Particle therapy center — national-scale capital project.",
        difficulty="Extreme",
        licenses=["Radiation oncology facility licenses", "Nuclear/radiation safety"],
        facility=["Cyclotron/synchrotron + gantries + bunkers"],
        training=["Proton-specific physics and RO training"],
        staffing=["Radiation oncologists, physicists, therapists"],
        product_source=["Vendor particle system (IBA, Varian, Hitachi, etc.)"],
        regulatory_steps=["Radiation safety licenses; CON in some US states"],
        capital_notes="Hundreds of millions USD typical.",
        ongoing_compliance=["Radiation safety; outcome reporting"],
    ),
    "proc-til-melanoma": S(
        "Manufacturer-authorized cell therapy center with TIL harvest + inpatient lymphodepletion capability.",
        difficulty="Extreme",
        licenses=["Hospital cell therapy / REMS-style center status"],
        facility=["OR for resection, cell processing logistics, inpatient ward, ICU"],
        training=["Amtagvi/TIL center training"],
        staffing=["Surgical oncology + cell therapy + ICU"],
        product_source=["Iovance / commercial TIL product"],
        regulatory_steps=["Center certification", "Payer negotiation"],
        capital_notes="Existing cellular therapy hospitals only.",
        ongoing_compliance=["Long-term follow-up"],
    ),
    "proc-car-t-solid": S(
        "Clinical trial site only in most cases — sponsor-driven setup.",
        difficulty="Extreme",
        licenses=["IND/CTA trial site"],
        facility=["Cell therapy + ICU"],
        training=["Protocol-specific"],
        staffing=["Investigator team + research coordinators"],
        product_source=["Sponsor product"],
        regulatory_steps=["IRB, contracts, IND compliance"],
        capital_notes="Research hospital.",
        ongoing_compliance=["GCP"],
    ),
    "proc-dendritic-vaccine": S(
        "Provenge: authorized infusion centers. Other DC vaccines: often gray/tourism — high regulatory risk if disease claims made without approval.",
        difficulty="High",
        licenses=["For Provenge: authorized center; otherwise trial or foreign clinic rules"],
        facility=["Apheresis coordination + infusion"],
        training=["Product-specific"],
        staffing=["Oncology infusion team"],
        product_source=["Dendreon network for Provenge"],
        regulatory_steps=["Manufacturer authorization"],
        capital_notes="Legitimate path is oncology center, not boutique vaccine shop.",
        ongoing_compliance=["Traceability"],
    ),
    "proc-photoimmunotherapy": S(
        "Japan-approved pathway needs specialist H&N oncology center with NIR illumination capability.",
        difficulty="High",
        licenses=["Hospital oncology program; product authorization in Japan"],
        facility=["OR/procedure room with NIR light system"],
        training=["ASP-1929 / NIR-PIT protocol training"],
        staffing=["H&N surgical oncology"],
        product_source=["Approved conjugate in Japan"],
        regulatory_steps=["National listing / hospital formulary"],
        capital_notes="Specialist oncology centers.",
        ongoing_compliance=["Phototoxicity precautions"],
    ),
    "proc-fmt": S(
        "GI practice with stool bank / approved microbiota product pathway for rCDI.",
        difficulty="Moderate",
        licenses=["Medical license GI/ID", "Product IND/approval pathway compliance"],
        facility=["Endoscopy or delivery suite; specimen handling"],
        training=["FMT protocols; donor screening knowledge"],
        staffing=["GI + nursing"],
        product_source=["FDA-cleared microbiota products or banked stool under guidance"],
        regulatory_steps=["Stay within rCDI labeled/cleared use or trial for other indications"],
        capital_notes="Lower if using commercial microbiota products vs in-house bank.",
        ongoing_compliance=["Donor/pathogen screening docs", "Infection control"],
    ),
    "proc-hbot": S(
        "UHMS-aligned hyperbaric facility with trained physicians and chamber safety program.",
        difficulty="High",
        licenses=["Facility + physician hyperbaric credentials (varies by state)"],
        facility=["Mono/multiplace chambers meeting safety codes", "Fire safety"],
        training=["Hyperbaric medicine courses; chamber operator training"],
        staffing=["Hyperbaric physician + technicians"],
        product_source=["Medical-grade chamber manufacturer"],
        regulatory_steps=["Certificate of occupancy; payer credentialing for labeled indications"],
        capital_notes="Chamber acquisition and facility modification are major costs.",
        ongoing_compliance=["Chamber maintenance; emergency drills"],
    ),
    "proc-prp-therapy": S(
        "Physician clinic with blood-processing device kit and sterile injection capability.",
        difficulty="Low",
        licenses=["Medical license with injection privileges"],
        facility=["Procedure room; centrifuge/PRP kit area"],
        training=["PRP injection techniques for target joint/tissue"],
        staffing=["Physician ± MA"],
        product_source=["510(k) PRP kits / centrifuge systems"],
        regulatory_steps=["Avoid drug claims beyond procedure; follow device IFU"],
        capital_notes="Low relative to cell therapy — device kits and centrifuge.",
        ongoing_compliance=["Infection control; informed consent on evidence limits"],
    ),
    "proc-ivig": S(
        "Infusion practice with specialty pharmacy channel and payer infrastructure.",
        difficulty="Moderate",
        licenses=["Medical license; infusion center standards"],
        facility=["Infusion chairs; emergency meds for reactions"],
        training=["IVIG reaction management"],
        staffing=["Prescriber + infusion nurses"],
        product_source=["Licensed IVIG brands via specialty pharmacy"],
        regulatory_steps=["Payer medical policy navigation (huge)"],
        capital_notes="Working capital for drug cost is the real barrier.",
        ongoing_compliance=["Lot traceability; reaction reporting"],
    ),
    "proc-apheresis-longcovid": S(
        "Apheresis-capable center (nephrology/transfusion medicine) — experimental PASC use needs careful consent.",
        difficulty="High",
        licenses=["Facility authorized for therapeutic apheresis"],
        facility=["Apheresis machines; nursing station; emergency response"],
        training=["Apheresis nursing certification"],
        staffing=["Nephrology/transfusion MD + apheresis nurses"],
        product_source=["Apheresis systems (Fresenius, etc.)"],
        regulatory_steps=["Hospital privilege; ethics review recommended for PASC protocols"],
        capital_notes="Machine + trained nurses; usually hospital-based.",
        ongoing_compliance=["Indication documentation; adverse events"],
        notes="Marketing unproven PASC cures is high risk.",
    ),
    "proc-repurposed-semaglutide": S(
        "Standard outpatient prescribing with telehealth option; compounding rules apply during shortages only under tight conditions.",
        difficulty="Low",
        licenses=["Prescriptive authority MD/DO/NP/PA as state allows"],
        facility=["Clinic or telehealth compliant with state law"],
        training=["Obesity/diabetes management; side-effect counseling"],
        staffing=["Prescriber + nursing/coaching optional"],
        product_source=["Retail/specialty pharmacy brand; compounding only if lawful"],
        regulatory_steps=["DEA not required (not controlled)", "Document BMI/indication"],
        capital_notes="Low; telehealth stacks common.",
        ongoing_compliance=["Monitor GI effects; avoid unapproved compounded copies when brand available"],
    ),
    "proc-glp1-addiction": S(
        "Off-label use of GLP-1s — same prescribing license as obesity/diabetes, plus addiction-informed consent.",
        difficulty="Moderate",
        licenses=["Prescriptive authority"],
        facility=["Outpatient / telehealth"],
        training=["Addiction medicine collaboration recommended"],
        staffing=["Prescriber ± addiction counselor"],
        product_source=["Pharmacy GLP-1"],
        regulatory_steps=["Clear off-label consent; no false AUD approval claims"],
        capital_notes="Low hardware; high documentation standards.",
        ongoing_compliance=["Evidence-updating consent as literature evolves"],
    ),
    "proc-sglt2-hf": S(
        "Standard cardiology/primary care prescribing under label — formulary is the main 'setup'.",
        difficulty="Low",
        licenses=["Prescriptive authority"],
        facility=["Outpatient clinic"],
        training=["HF/CKD guideline education"],
        staffing=["Prescriber"],
        product_source=["Retail pharmacy"],
        regulatory_steps=["None special beyond medical practice"],
        capital_notes="Negligible.",
        ongoing_compliance=["Renal function monitoring; genital infection counseling"],
    ),
    "proc-repurposed-rapamycin": S(
        "Off-label longevity prescribing via licensed physician + lab monitoring program.",
        difficulty="Moderate",
        licenses=["Medical license"],
        facility=["Clinic or telehealth + lab partnership"],
        training=["mTOR/longevity protocol literacy; transplant-dose knowledge for safety"],
        staffing=["Prescriber + lab follow-up system"],
        product_source=["Generic sirolimus pharmacy"],
        regulatory_steps=["Off-label consent; avoid disease-cure marketing"],
        capital_notes="Low drug cost; telehealth platforms popular.",
        ongoing_compliance=["Lipids, CBC, glucose monitoring"],
    ),
    "proc-metformin-longevity": S(
        "Ordinary outpatient prescribing; off-label aging use needs consent and renal screening.",
        difficulty="Low",
        licenses=["Prescriptive authority"],
        facility=["Clinic/telehealth"],
        training=["Metformin safety (B12, eGFR, lactic acidosis rare)"],
        staffing=["Prescriber"],
        product_source=["Generic pharmacy"],
        regulatory_steps=["Standard practice of medicine"],
        capital_notes="Minimal.",
        ongoing_compliance=["Periodic eGFR/B12"],
    ),
    "proc-repurposed-ldn": S(
        "Prescriber + compounding pharmacy relationship for low-dose naltrexone.",
        difficulty="Low",
        licenses=["Prescriptive authority"],
        facility=["Clinic"],
        training=["LDN dosing/titration knowledge"],
        staffing=["Prescriber"],
        product_source=["503A compounding pharmacy"],
        regulatory_steps=["Compounding prescription compliance"],
        capital_notes="Minimal.",
        ongoing_compliance=["Opioid washout counseling"],
    ),
    "proc-repurposed-methylene": S(
        "Prescriber of pharmaceutical-grade methylene blue; avoid non-medical dye sources.",
        difficulty="Low",
        licenses=["Prescriptive authority"],
        facility=["Clinic"],
        training=["G6PD screening; serotonergic interaction knowledge"],
        staffing=["Prescriber"],
        product_source=["USP/pharmaceutical methylene blue only"],
        regulatory_steps=["Document indication (labeled vs off-label)"],
        capital_notes="Minimal.",
        ongoing_compliance=["Drug interaction checks"],
    ),
    "proc-prazosin-ptsd": S(
        "Standard outpatient prescribing for off-label PTSD nightmares.",
        difficulty="Low",
        licenses=["Prescriptive authority"],
        facility=["Clinic"],
        training=["First-dose hypotension counseling"],
        staffing=["Prescriber"],
        product_source=["Generic pharmacy"],
        regulatory_steps=["None special"],
        capital_notes="None.",
        ongoing_compliance=["BP monitoring"],
    ),
    "proc-baclofen-aud": S(
        "Addiction-capable prescriber; high-dose protocols need closer monitoring.",
        difficulty="Moderate",
        licenses=["Prescriptive authority; addiction clinic preferred"],
        facility=["Outpatient addiction setting"],
        training=["AUD pharmacology; baclofen titration/withdrawal risks"],
        staffing=["Prescriber ± addiction counselor"],
        product_source=["Pharmacy baclofen"],
        regulatory_steps=["Off-label consent; local high-dose rules if any (e.g. France history)"],
        capital_notes="Low.",
        ongoing_compliance=["Sedation monitoring; taper plans"],
    ),
    "proc-trt": S(
        "DEA Schedule III in US — registration and diagnostic rigor required.",
        difficulty="Moderate",
        licenses=["Medical license", "DEA (US) for testosterone"],
        facility=["Clinic capable of injections/monitoring"],
        training=["Endocrine guidelines for hypogonadism diagnosis"],
        staffing=["Prescriber ± nursing"],
        product_source=["Pharmacy testosterone; avoid unregulated research peptides as substitutes"],
        regulatory_steps=["Document two low-T labs + symptoms ideally", "Controlled-substance logs"],
        capital_notes="Low–moderate; telehealth TRT has compliance risk if diagnosis is shoddy.",
        ongoing_compliance=["Hct, PSA as indicated, fertility counseling"],
    ),
    "proc-pt-141": S(
        "For Vyleesi: specialty pharmacy distribution. Compounded PT-141: compounding compliance riskier.",
        difficulty="Moderate",
        licenses=["Prescriptive authority"],
        facility=["Clinic"],
        training=["HSDD diagnosis; BP screening"],
        staffing=["Prescriber"],
        product_source=["Vyleesi specialty pharmacy preferred"],
        regulatory_steps=["Label-aligned prescribing for HSDD"],
        capital_notes="Low.",
        ongoing_compliance=["Nausea/BP counseling"],
    ),
    "proc-peptide-bpc": S(
        "US: no clear lawful compounding pathway currently — do not build a business assuming legal BPC-157 Rx.",
        difficulty="Extreme",
        licenses=["Would require future FDA bulk-substance authorization for compounding"],
        facility=["N/A legitimate"],
        training=["N/A"],
        staffing=["N/A"],
        product_source=["No approved US drug product"],
        regulatory_steps=["Monitor FDA PCAC/bulk list; do not market as FDA-approved"],
        capital_notes="Legal risk dominates.",
        ongoing_compliance=["Avoid research-chemical injection practices"],
        notes="Gray wellness markets exist abroad but are high risk.",
    ),
    "proc-peptide-cjc-ipa": S(
        "Similar peptide compounding restrictions — not a clean US medical business line.",
        difficulty="Extreme",
        licenses=["Unclear/not authorized for many secretagogues"],
        facility=["N/A"],
        training=["N/A"],
        staffing=["N/A"],
        product_source=["Research chemical market is not medical care"],
        regulatory_steps=["FDA enforcement risk"],
        capital_notes="Legal risk.",
        ongoing_compliance=["Do not make disease claims"],
    ),
    "proc-peptide-tesamorelin": S(
        "Specialty HIV clinic with specialty pharmacy for Egrifta.",
        difficulty="Moderate",
        licenses=["Medical license; HIV care experience"],
        facility=["Clinic with injection teaching"],
        training=["Lipodystrophy indication criteria"],
        staffing=["HIV specialist preferred"],
        product_source=["Specialty pharmacy Egrifta"],
        regulatory_steps=["Prior auth / patient assistance"],
        capital_notes="Drug cost management is the hurdle.",
        ongoing_compliance=["Glucose monitoring"],
    ),
    "proc-peptide-thymosin": S(
        "Where Zadaxin is approved: standard specialty Rx. US: compounding/import gray — high uncertainty.",
        difficulty="High",
        licenses=["Local product registration pathway where approved"],
        facility=["Clinic"],
        training=["Indication-specific"],
        staffing=["Prescriber"],
        product_source=["Registered product in approved countries"],
        regulatory_steps=["Import/named-patient rules if cross-border"],
        capital_notes="Varies by country.",
        ongoing_compliance=["Pharmacovigilance where marketed"],
    ),
    "proc-peptide-ss31": S(
        "Trial site or expanded access only until broader approval.",
        difficulty="Extreme",
        licenses=["Clinical trial site"],
        facility=["Research clinic/hospital"],
        training=["Protocol training"],
        staffing=["Investigator team"],
        product_source=["Sponsor"],
        regulatory_steps=["IND/CTA"],
        capital_notes="Research only.",
        ongoing_compliance=["GCP"],
    ),
    "proc-nmn-nmad": S(
        "Supplement retail (where lawful) — not a medical procedure business; disease claims restricted.",
        difficulty="Low",
        licenses=["Business/retail; not medical practice required for supplements"],
        facility=["Retail or e-commerce"],
        training=["Advertising compliance (no disease claims)"],
        staffing=["Retail"],
        product_source=["Supplement manufacturers; novel food rules in EU"],
        regulatory_steps=["DSHEA/food law compliance; NMN status may be contested"],
        capital_notes="Inventory risk.",
        ongoing_compliance=["Label claims review"],
    ),
    "proc-nad-iv": S(
        "IV therapy clinic under medical director; sterile compounding/pharmacy rules apply.",
        difficulty="Moderate",
        licenses=["Medical director license; facility as state requires for IV therapy"],
        facility=["Infusion chairs; emergency kit"],
        training=["IV competency; sterile technique"],
        staffing=["Prescriber + IV nurse"],
        product_source=["Pharmacy-compounded NAD+ with sterility documentation"],
        regulatory_steps=["State medical board IV therapy rules"],
        capital_notes="Moderate clinic build-out.",
        ongoing_compliance=["No unapproved disease claims", "Compounding quality agreements"],
    ),
    "proc-senolytics": S(
        "Off-label oncology drug (dasatinib) + supplement — requires careful oncology-aware prescribing.",
        difficulty="High",
        licenses=["Medical license able to prescribe dasatinib"],
        facility=["Clinic with lab access"],
        training=["Dasatinib toxicity knowledge; senolytic protocol literacy"],
        staffing=["Prescriber"],
        product_source=["Pharmacy dasatinib; OTC quercetin"],
        regulatory_steps=["Off-label consent; avoid anti-aging cure marketing"],
        capital_notes="Low drug cost; high liability if poorly monitored.",
        ongoing_compliance=["CBC monitoring; infection counseling"],
    ),
    "proc-chelation": S(
        "Labeled metal toxicity: medical toxicology setting. Off-label 'detox': high liability.",
        difficulty="High",
        licenses=["Medical license; preferably toxicology expertise for labeled use"],
        facility=["Infusion suite with electrolyte emergency readiness"],
        training=["Chelation protocols; hypocalcemia management"],
        staffing=["MD + infusion nurse"],
        product_source=["Pharmacy EDTA/DMSA"],
        regulatory_steps=["Document confirmed metal toxicity for labeled path"],
        capital_notes="Moderate infusion setup.",
        ongoing_compliance=["Labs before/during; avoid autism/CVD unproven marketing"],
    ),
    "proc-ozone-therapy": S(
        "US: FDA-hostile — not a recommended lawful medical business. Some EU complementary practices under physician rules.",
        difficulty="Extreme",
        licenses=["Often not lawful as medical therapy in US"],
        facility=["N/A recommended US"],
        training=["N/A"],
        staffing=["N/A"],
        product_source=["Medical ozone generators claim scrutiny"],
        regulatory_steps=["High FDA enforcement risk in US"],
        capital_notes="Legal risk dominates.",
        ongoing_compliance=["Do not market as FDA-approved"],
        notes="Complementary markets in DE/CH exist under physician practice — still evidence-contested.",
    ),
    "proc-cryotherapy": S(
        "Commercial wellness facility — not typically a medical license pathway.",
        difficulty="Low",
        licenses=["Business license; local safety codes"],
        facility=["Cryochamber with oxygen monitoring and emergency egress"],
        training=["Operator safety training; client screening for CVD"],
        staffing=["Trained operators"],
        product_source=["Chamber manufacturer"],
        regulatory_steps=["Occupancy/fire/safety inspections"],
        capital_notes="Chamber cost significant but no drug license.",
        ongoing_compliance=["Client waivers; session limits"],
    ),
    "proc-medical-cannabis": S(
        "Highly jurisdiction-specific: medical license + cannabis program registration, or pharmacy channel where prescribed.",
        difficulty="High",
        licenses=["Physician authorization to recommend/prescribe per local law", "Dispensary/pharmacy license for retail supply"],
        facility=["Secured inventory if dispensing"],
        training=["Cannabis medicine CME often required"],
        staffing=["Authorized clinician; pharmacists where dispensed"],
        product_source=["Licensed producers only"],
        regulatory_steps=["State/national cannabis program enrollment", "Seed-to-sale tracking where required"],
        capital_notes="Retail dispensary capital high; pure recommenders lower.",
        ongoing_compliance=["Inventory tracking; advertising limits; patient registry"],
    ),
    "proc-ayahuasca": S(
        "Religious exemption frameworks or gray retreats — not a standard medical clinic license path in most countries.",
        difficulty="Extreme",
        licenses=["Religious organization status where recognized (e.g. Brazil churches)", "Otherwise often unlawful"],
        facility=["Ceremonial space; medical screening recommended"],
        training=["Facilitation tradition; medical emergency plans"],
        staffing=["Facilitators; ideally medical backup"],
        product_source=["Brew preparation quality control"],
        regulatory_steps=["Religious recognition applications where available"],
        capital_notes="Legal risk >> capital.",
        ongoing_compliance=["Drug interaction screening (MAOI)", "Safety"],
    ),
    "proc-5meo-dmt": S(
        "Mostly unlawful or trial-only; ceremonial gray markets high risk.",
        difficulty="Extreme",
        licenses=["Generally no medical license path; trials if any"],
        facility=["Trial site or illegal/gray"],
        training=["N/A medical"],
        staffing=["N/A"],
        product_source=["Synthetic trial material vs toad conservation issues"],
        regulatory_steps=["Schedule I barriers in US"],
        capital_notes="Legal risk.",
        ongoing_compliance=["N/A"],
    ),
    "proc-mescaline-therapy": S(
        "Plant medicine retreat gray markets in some countries; no major medical license product path.",
        difficulty="Extreme",
        licenses=["Typically none medical"],
        facility=["Retreat"],
        training=["Facilitation"],
        staffing=["Facilitators"],
        product_source=["Cactus material potency variable"],
        regulatory_steps=["Local controlled substance law"],
        capital_notes="Legal risk.",
        ongoing_compliance=["Screening"],
    ),
    "proc-dmt-depression": S(
        "Clinical trial or future approved product path; not a clinic you can open today in most places.",
        difficulty="Extreme",
        licenses=["Trial site / future product authorization"],
        facility=["Infusion monitoring for IV DMT studies"],
        training=["Protocol"],
        staffing=["Research psychiatry"],
        product_source=["GMP trial supply"],
        regulatory_steps=["IND"],
        capital_notes="Research hospital.",
        ongoing_compliance=["GCP"],
    ),
    "proc-lsd-anxiety": S(
        "Compassionate use / trial psychiatrist frameworks (e.g. Swiss BAG) — not commercial clinics.",
        difficulty="Extreme",
        licenses=["Physician + exceptional authorization"],
        facility=["Medical psychotherapeutic setting"],
        training=["Psychedelic therapy experience"],
        staffing=["Psychiatrist + therapist"],
        product_source=["Authorized pharmaceutical LSD"],
        regulatory_steps=["Per-patient authorization applications"],
        capital_notes="Low capital, high regulatory friction.",
        ongoing_compliance=["Case reporting to authority"],
    ),
    "proc-psilocybin-microdose": S(
        "Where only full-dose licensed services exist, microdose retail is usually not a licensed product line.",
        difficulty="High",
        licenses=["Often none for commercial microdose"],
        facility=["N/A regulated"],
        training=["N/A"],
        staffing=["N/A"],
        product_source=["Legal truffles (NL) vs illegal mushrooms (US federal)"],
        regulatory_steps=["Check local scheduling"],
        capital_notes="Legal risk in most places.",
        ongoing_compliance=["N/A"],
    ),
    "proc-ecmo-bridge": S(
        "Tertiary ICU program with ELSO-level volume — not private clinic.",
        difficulty="Extreme",
        licenses=["Hospital ICU program"],
        facility=["ECMO circuit, perfusion, 24/7 ICU"],
        training=["ECMO specialist teams"],
        staffing=["Intensivists, perfusionists, ECMO nurses"],
        product_source=["ECMO hardware vendors"],
        regulatory_steps=["Hospital credentialing; transfer networks"],
        capital_notes="Hospital capital + high ongoing staffing cost.",
        ongoing_compliance=["ELSO-style quality metrics"],
    ),
    "proc-fecal-sibo": S(
        "GI practice prescribing rifaximin + diet protocols — standard outpatient.",
        difficulty="Low",
        licenses=["Medical license"],
        facility=["Clinic"],
        training=["SIBO testing/treatment literacy"],
        staffing=["Prescriber ± dietitian"],
        product_source=["Pharmacy rifaximin; elemental diet suppliers"],
        regulatory_steps=["Document indication for prior auth (US cost friction)"],
        capital_notes="Minimal.",
        ongoing_compliance=["Antibiotic stewardship counseling"],
    ),
    "proc-low-dose-lithium": S(
        "Prescription lithium requires monitoring infrastructure; OTC orotate is supplement retail not medical setup.",
        difficulty="Low",
        licenses=["Prescriptive authority for carbonate"],
        facility=["Clinic + lab access"],
        training=["Lithium toxicity knowledge even at low dose"],
        staffing=["Prescriber"],
        product_source=["Pharmacy lithium carbonate or compounded microdose"],
        regulatory_steps=["Baseline renal/thyroid labs"],
        capital_notes="Minimal.",
        ongoing_compliance=["Periodic labs"],
    ),
}

# Alias proton if duplicate key issue - already have proc-proton-therapy once in dict above with full entry
# Wait I duplicated proc-proton-therapy - the second overwrites. Remove the short one - I only have one full entry. Good.

# Fix: I have proc-proton-therapy only once at the end as short - actually looking at the file I have full entry mid-way AND short at end. Need to remove duplicate short one when writing - I'll only keep the full one.

# ── Jurisdiction-specific overrides (merge on top of defaults) ───────────────

ACCESS_SETUP_OVERRIDES = {
    ("proc-psilocybin-trd", "jur-us-or"): S(
        "Oregon: become an OHA-licensed psilocybin service center and/or facilitator under Oregon Psilocybin Services (OPS).",
        difficulty="High",
        licenses=[
            "OHA Psilocybin Service Center license",
            "OHA Facilitator license (for facilitators)",
            "Manufacturer/lab licenses if vertically integrating product",
            "Local business / land-use permits",
        ],
        facility=[
            "Approved administration area (indoor/outdoor rules)",
            "Secure product storage meeting OPS rules",
            "Security and access control",
            "Client preparation/integration spaces",
        ],
        training=[
            "OHA-approved facilitator training (~120+ hours incl. practicum)",
            "Service center SOPs for preparation, administration, integration",
        ],
        staffing=[
            "Licensed facilitators (capacity often 1–2 journeys/week per facilitator)",
            "Administrative staff for SB 303 client data reporting",
        ],
        product_source=[
            "OPS-licensed manufacturer product only",
            "OPS-licensed testing lab results",
        ],
        regulatory_steps=[
            "Apply via Oregon Psilocybin Services Section",
            "Pay annual license fees (historically high — five-figure class for centers)",
            "Implement SB 303 de-identified client data collection/reporting",
            "Informed consent form content per OHA rules",
        ],
        capital_notes="High fixed costs: licensing, security, rent, and limited throughput have contributed to center closures — model cash flow carefully.",
        ongoing_compliance=[
            "Quarterly data reporting",
            "Adverse reaction reporting thresholds",
            "License renewal",
            "Absolute contraindications screening (lithium, active psychosis, harm history)",
        ],
        notes="Clients 21+; no physician prescription required under OPS model. Federal Schedule I risk remains a planning issue for banking/tax.",
    ),
    ("proc-psilocybin-eol", "jur-us-or"): S(
        "Same OPS licensure as general psilocybin services; add clinical competence for medically complex/EOL clients.",
        difficulty="High",
        licenses=["OPS service center + facilitator licenses"],
        facility=["OPS-compliant center; medical clearance partnerships"],
        training=["Facilitator training + palliative literacy"],
        staffing=["Facilitators; medical consult network"],
        product_source=["Licensed manufacturer product"],
        regulatory_steps=["OPS applications and reporting"],
        capital_notes="Same as general OPS centers.",
        ongoing_compliance=["OPS reporting; careful screening for medical stability"],
    ),
    ("proc-psilocybin-trd", "jur-au"): S(
        "Australia: only via TGA Authorized Prescriber / Special Access with psychiatrist leadership — not a wellness center license.",
        difficulty="Extreme",
        licenses=[
            "Specialist psychiatrist registration",
            "TGA Authorized Prescriber approval (or SAS pathway)",
            "Institutional ethics committee approval as required",
        ],
        facility=[
            "Medically controlled administration setting",
            "Emergency medical response capability",
        ],
        training=[
            "Psilocybin-assisted therapy protocol training",
            "RANZCP-aligned clinical governance",
        ],
        staffing=[
            "Authorized psychiatrist",
            "Therapists / nursing as protocol requires",
        ],
        product_source=["GMP psilocybin from TGA-acceptable supply"],
        regulatory_steps=[
            "Secure Authorized Prescriber status for TRD indication",
            "Ethics and site approvals",
            "Pharmacovigilance plan",
        ],
        capital_notes="High medical overhead; multi-disciplinary team costs dominate.",
        ongoing_compliance=["TGA reporting obligations", "Controlled drug handling"],
    ),
    ("proc-mdma-ptsd", "jur-au"): S(
        "TGA Authorized Prescriber pathway for MDMA-AT for PTSD — psychiatrist + ethics + GMP product.",
        difficulty="Extreme",
        licenses=["Psychiatrist + TGA Authorized Prescriber", "Ethics approval"],
        facility=["Medical psychotherapy setting with monitoring"],
        training=["MDMA-AT protocol training"],
        staffing=["Two-therapist model typical + medical coverage"],
        product_source=["GMP MDMA"],
        regulatory_steps=["Authorized Prescriber application for PTSD"],
        capital_notes="Very high per-patient therapy time cost.",
        ongoing_compliance=["Controlled substance + TGA reporting"],
    ),
    ("proc-ketamine-depression", "jur-us-federal"): S(
        "Choose Spravato REMS path and/or off-label IV/IM ketamine clinic under state medical board + DEA.",
        difficulty="Moderate",
        licenses=[
            "State medical license (MD/DO/NP/PA per state)",
            "DEA registration Schedule III",
            "Spravato REMS healthcare setting certification if offering esketamine",
        ],
        facility=[
            "Monitoring for ≥2 hours (Spravato) or protocol-defined period (IV)",
            "BP monitoring; emergency equipment; patient restroom access",
            "No driving post-session policy / discharge escort rules",
        ],
        training=[
            "Spravato REMS training modules if applicable",
            "Ketamine clinic emergency protocols; ASKP-aligned standards recommended",
        ],
        staffing=[
            "REMS-enrolled prescriber + trained observers for Spravato",
            "For IV: clinician competent in sedation monitoring",
        ],
        product_source=[
            "Spravato via certified pharmacy channel",
            "Ketamine from licensed pharmacy / wholesaler",
        ],
        regulatory_steps=[
            "Enroll in Spravato REMS if offering product",
            "State controlled-substance inventory compliance",
            "CLIA-waived or partner labs if needed",
        ],
        capital_notes="Build-out for monitoring chairs and staffing ratio is the main cost; lower than inpatient psych.",
        ongoing_compliance=[
            "Controlled substance biennial inventory",
            "REMS documentation for Spravato",
            "Informed consent distinguishing FDA-approved vs off-label IV",
        ],
    ),
    ("proc-maid", "jur-ca"): S(
        "Integrate into provincial healthcare MAID pathways — dual independent assessments and mandatory reporting.",
        difficulty="High",
        licenses=[
            "Provincial medical or NP license as statute allows",
            "Hospital/clinic privileging if institutional",
        ],
        facility=[
            "Setting for assessment visits and provision (home or facility per policy)",
        ],
        training=[
            "Provincial MAID assessor/provider training modules",
            "Capacity and voluntariness evaluation skills",
        ],
        staffing=[
            "Two independent assessors",
            "Pharmacy / medication administration support",
        ],
        product_source=["Provincial medication protocols for clinician- or self-administered MAID"],
        regulatory_steps=[
            "Follow Criminal Code + provincial health authority forms",
            "Track 1 vs Track 2 safeguards (including 90-day assessment period where applicable)",
            "Report every provision to federal monitoring system",
        ],
        capital_notes="Process/legal burden more than capital equipment; usually public-system integrated.",
        ongoing_compliance=[
            "Mandatory federal reporting",
            "Update practice as mental-illness track rules evolve",
            "Referral duties if conscientious objection",
        ],
    ),
    ("proc-maid", "jur-ch"): S(
        "Right-to-die organization model under Swiss Criminal Code Art. 115 — not ordinary medical practice alone.",
        difficulty="High",
        licenses=[
            "Swiss physician for prescription of lethal medication",
            "Non-profit right-to-die organization affiliation (Dignitas/EXIT/etc. models)",
        ],
        facility=[
            "Organization premises or approved setting for accompaniment",
        ],
        training=[
            "Organization-specific assessment protocols",
            "Legal requirements for non-selfish motive accompaniment",
        ],
        staffing=[
            "Organization staff + prescribing physician + witnesses as required",
        ],
        product_source=["Prescribed sodium pentobarbital pathway under Swiss practice"],
        regulatory_steps=[
            "Member/assessment process of recognized organization",
            "Police notification procedures after death",
            "Documentation of capacity at time of act",
        ],
        capital_notes="Organizational structure and legal defense reserves matter more than clinic build-out.",
        ongoing_compliance=[
            "Post-death investigation cooperation",
            "Cantonal practice variations",
        ],
    ),
    ("proc-stem-car-t", "jur-us-federal"): S(
        "Become a manufacturer-certified REMS CAR-T center inside a hospital with ICU and cellular therapy infrastructure.",
        difficulty="Extreme",
        licenses=[
            "Hospital license",
            "REMS certification per CAR-T product (Kymriah, Yescarta, etc.)",
            "FACT accreditation strongly expected",
        ],
        facility=[
            "Apheresis",
            "Inpatient unit trained for CRS/ICANS",
            "ICU with tocilizumab immediately available",
            "Cell therapy coordination with manufacturer logistics",
        ],
        training=[
            "Product-specific REMS training for all involved staff",
            "CRS/ICANS grading and management drills",
        ],
        staffing=[
            "Cellular therapy physicians",
            "APPs, ICU, neurology, pharmacy, apheresis team",
        ],
        product_source=["Commercial CAR-T manufacturers only — chain of identity"],
        regulatory_steps=[
            "Apply to each manufacturer network",
            "Payer contracting / NTAP awareness for Medicare",
            "Registry and long-term follow-up systems",
        ],
        capital_notes="Only existing transplant/cell therapy programs; not a startup clinic model.",
        ongoing_compliance=[
            "REMS documentation",
            "Long-term secondary malignancy monitoring expectations",
            "Outcome reporting",
        ],
    ),
    ("proc-gene-crispr", "jur-us-federal"): S(
        "Authorized Casgevy (or trial) treatment center — transplant-capable hospital only.",
        difficulty="Extreme",
        licenses=["Manufacturer-authorized center status", "Hospital transplant/cell therapy program"],
        facility=["Myeloablative conditioning capacity", "Apheresis", "ICU"],
        training=["Product-specific center training"],
        staffing=["Hematology transplant team"],
        product_source=["Vertex/CRISPR Casgevy logistics"],
        regulatory_steps=["Center certification", "Payer outcomes agreements often"],
        capital_notes="Existing transplant centers only.",
        ongoing_compliance=["Long-term follow-up registries"],
    ),
    ("proc-mito-replacement", "jur-uk"): S(
        "Obtain HFEA license for mitochondrial donation — unique regulated pathway.",
        difficulty="Extreme",
        licenses=["HFEA mitochondrial donation license", "Standard HFEA IVF clinic license foundation"],
        facility=["Advanced embryology lab with micromanipulation"],
        training=["Specialist mitochondrial donation techniques approved under license"],
        staffing=["Specialist embryologists + genetics counselors"],
        product_source=["Mitochondrial donor pathway under HFEA rules"],
        regulatory_steps=[
            "HFEA license application with inspection",
            "Patient selection criteria for serious mtDNA disease risk",
            "Follow-up commitments for children born",
        ],
        capital_notes="Only a handful of centers; years of preparatory work.",
        ongoing_compliance=["HFEA inspections", "Outcome reporting", "Long-term follow-up"],
    ),
    ("proc-lecanemab", "jur-us-federal"): S(
        "Build memory-clinic + infusion + MRI safety network meeting appropriate use and coverage rules.",
        difficulty="High",
        licenses=["Medical practice; neurology/geriatrics preferred"],
        facility=[
            "Infusion suite",
            "Rapid access to MRI for ARIA monitoring",
            "APOE counseling pathway",
        ],
        training=["ARIA recognition and management", "Appropriate use criteria for anti-amyloid mAbs"],
        staffing=["Infusing clinicians/nurses", "Radiology partnership", "Care navigation"],
        product_source=["Leqembi specialty distribution"],
        regulatory_steps=[
            "CMS coverage with evidence development / registry requirements as applicable",
            "Payer prior authorization workflows",
            "Amyloid confirmation pathway (PET or CSF)",
        ],
        capital_notes="Imaging access contracts matter more than refrigerator space.",
        ongoing_compliance=["Protocolized safety MRI schedule", "Registry data", "Infusion reaction preparedness"],
    ),
    ("proc-tms-depression", "jur-us-federal"): S(
        "Purchase/lease cleared TMS device, train staff, enroll with payers for TRD medical necessity.",
        difficulty="Moderate",
        licenses=["Physician oversight license", "Clinic business license"],
        facility=["TMS treatment room; seizure response plan; waiting area"],
        training=["Manufacturer device training", "TMS protocol selection (rTMS/iTBS)"],
        staffing=["Psychiatrist medical director", "TMS technicians"],
        product_source=["FDA-cleared TMS system (MagVenture, NeuroStar, BrainsWay, etc.)"],
        regulatory_steps=["Medicare/commercial payer credentialing", "Prior auth templates"],
        capital_notes="Device capital ~tens of thousands to low six figures; room build-out.",
        ongoing_compliance=["Device maintenance", "Outcome measures for authorizations"],
    ),
    ("proc-medical-cannabis", "jur-us-ca"): S(
        "Either become a recommending clinician under state rules or a DCC-licensed dispensary — totally different setups.",
        difficulty="High",
        licenses=[
            "Physician/NP recommend authority under CA law",
            "OR for retail: Department of Cannabis Control license types (storefront, delivery, etc.)",
        ],
        facility=["For dispensary: secured premises meeting DCC rules"],
        training=["Cannabis CME for clinicians; Responsible Vendor for retail staff"],
        staffing=["Budtenders + inventory managers for retail; clinician time for recommendations"],
        product_source=["Licensed CA supply chain only; METRC tracking"],
        regulatory_steps=["DCC licensing for commercial", "Local city/county permits often harder than state"],
        capital_notes="Retail cannabis: high capital + local opposition risk. Recommend-only practice: low capital.",
        ongoing_compliance=["Seed-to-sale tracking", "Tax remittance", "Advertising limits"],
    ),
    ("proc-medical-cannabis", "jur-de"): S(
        "Physician prescription of medical cannabis via pharmacy channel — clinic setup is medical practice, not dispensary retail.",
        difficulty="Moderate",
        licenses=["German medical license (Approbation)", "Narcotic prescribing rules as applicable post-reclassification updates"],
        facility=["Medical practice"],
        training=["Cannabis therapy knowledge; documentation for indication"],
        staffing=["Physician", "Pharmacy partners for dispensing"],
        product_source=["Pharmacy-dispensed medical cannabis products"],
        regulatory_steps=["Prescription documentation meeting insurer rules if seeking coverage"],
        capital_notes="Low if existing practice; no need to open a dispensary.",
        ongoing_compliance=["Prescription records", "Driving counseling"],
    ),
    ("proc-repro-ivf", "jur-us-federal"): S(
        "Launch or join SART-member fertility practice with CLIA lab and tissue storage compliance.",
        difficulty="High",
        licenses=["REI physician preferred", "CLIA lab", "FDA registration for donor tissue if applicable", "State tissue bank licenses where required"],
        facility=["Embryology lab, andrology, retrieval OR, cryo storage with alarms"],
        training=["REI + embryologist certification pathways"],
        staffing=["REI, embryologists, nurses, financial counselors"],
        product_source=["Stimulation meds specialty pharmacy; lab consumables"],
        regulatory_steps=["CDC/SART reporting", "HIPAA + state embryo laws post-Dobbs complexity"],
        capital_notes="Often multi-million USD lab build; many join existing networks.",
        ongoing_compliance=["Success rate reporting", "Cryo tank monitoring", "Embryo disposition legal updates"],
    ),
    ("proc-fmt", "jur-us-federal"): S(
        "GI practice using FDA-cleared microbiota products for rCDI; stay inside labeled/cleared use or open an IND for research.",
        difficulty="Moderate",
        licenses=["Medical license GI/ID"],
        facility=["Endoscopy suite or appropriate delivery setting"],
        training=["FMT/microbiota product protocols"],
        staffing=["GI + nursing"],
        product_source=["FDA-cleared microbiota products (e.g. commercial) or OpenBiome-class pathways historically"],
        regulatory_steps=["Do not market for unapproved IBD indications without trial/expanded access"],
        capital_notes="Lower if using commercial products vs full stool bank.",
        ongoing_compliance=["Infection control", "Product traceability"],
    ),
    ("proc-hbot", "jur-us-federal"): S(
        "Establish UHMS-aligned hyperbaric facility with trained physician and chamber safety program.",
        difficulty="High",
        licenses=["Facility permits", "Physician hyperbaric credentials per state/payer"],
        facility=["Class A/B chamber meeting NFPA/ASME safety", "Fire suppression / oxygen safety"],
        training=["Introduction to Hyperbaric Medicine courses", "Chamber operator certification (NBDHMT pathways)"],
        staffing=["Hyperbaric physician + certified techs"],
        product_source=["Medical chamber manufacturers"],
        regulatory_steps=["Payer credentialing for UHMS-accepted indications", "Certificate of occupancy"],
        capital_notes="Chamber + facility modification often mid-six to seven figures.",
        ongoing_compliance=["Emergency drills", "Chamber maintenance logs"],
    ),
    ("proc-ibogaine-addiction", "jur-mx"): S(
        "If operating in Mexico, build a medically supervised detox facility — cardiac capability is the ethical minimum.",
        difficulty="Extreme",
        licenses=["Mexican medical facility registration", "Physician licenses (cédula)"],
        facility=["Telemetry/ECG monitoring", "Crash cart & defibrillator", "Hospital transfer agreement"],
        training=["Ibogaine cardiac risk management", "Emergency ACLS"],
        staffing=["MD on-site during treatment window", "24h nursing"],
        product_source=["Documented pharmaceutical-grade supply + QC"],
        regulatory_steps=["COFEPRIS facility compliance as applicable", "Robust informed consent in Spanish/English"],
        capital_notes="Medical monitoring infrastructure is mandatory cost — non-medical 'retreat only' is reckless.",
        ongoing_compliance=["Mandatory pre-treatment ECG/QTc/electrolytes/LFTs", "Mortality review culture"],
        notes="Legal gray zone — obtain local counsel; GITA guidelines are voluntary not law.",
    ),
    ("proc-gene-crispr", "jur-hn-prospera"): S(
        "ZEDE/Próspera pathway is informed-consent experimental biotech — not FDA equivalence; legal and political risk is material.",
        difficulty="Extreme",
        licenses=["Próspera/ZEDE health services authorization as then-current rules allow"],
        facility=["Clinic capable of gene therapy aftercare; limited island ICU — plan evacuation"],
        training=["Protocol-specific experimental therapy"],
        staffing=["Clinician-investigators", "Emergency transfer plan"],
        product_source=["Company manufacturing under ZEDE framework"],
        regulatory_steps=["Entity formation under ZEDE", "Informed consent architecture", "Monitor Honduran constitutional challenges to ZEDE"],
        capital_notes="Political/legal risk may dominate financial capital.",
        ongoing_compliance=["Consent documentation", "Adverse event handling with limited local tertiary care"],
    ),
}


def all_procedure_setup_defaults():
    return dict(PROCEDURE_SETUP_DEFAULTS)


def all_access_setup_overrides():
    return dict(ACCESS_SETUP_OVERRIDES)


def merged_setup(proc_id, jur_id=None):
    """Return setup dict for a procedure, with optional jurisdiction override replacing fields."""
    base = PROCEDURE_SETUP_DEFAULTS.get(proc_id)
    if jur_id:
        over = ACCESS_SETUP_OVERRIDES.get((proc_id, jur_id))
        if over:
            return over
    return base
