#!/usr/bin/env python3
"""
Build static, server-rendered clinical-trial landing pages from
data/clinical_trials/clinical_trials_current.json.

Outputs (all under trials/):
  index.html                          hub page linking everything with counts
  long-covid-recruiting.html          recruiting / not-yet-recruiting / by-invitation trials
  me-cfs-recruiting.html
  post-viral-overlap-recruiting.html
  all-long-covid.html                 complete list incl. completed / terminated, status badges
  all-me-cfs.html
  all-post-viral-overlap.html
  by-agent/index.html                 agents that appear in >= 2 trials
  by-agent/<agent-slug>.html

Run from the repo root:
  python scripts/build_trial_pages.py
  python scripts/build_trial_pages.py --source clinical_trials/data/clinical_trials_current.json

Idempotent: output is deterministic for a given input file, unchanged files
are not rewritten, and stale by-agent pages previously generated by this
script are removed.
"""
from __future__ import annotations

import argparse
import html
import json
import re
import sys
from collections import Counter, defaultdict
from datetime import datetime
from pathlib import Path
from urllib.parse import quote

ROOT = Path(__file__).resolve().parent.parent
DEFAULT_SOURCE = ROOT / "data" / "clinical_trials" / "clinical_trials_current.json"
OUT_DIR = ROOT / "trials"
AGENT_DIR = OUT_DIR / "by-agent"
AGENT_PAGES_DIR = ROOT / "agents"  # existing agents/<slug>/index.html profiles

SITE = "https://research.opensourcemed.info"
DATASET_URL = f"{SITE}/data/clinical_trials/clinical_trials_current.json"
SUBSTACK = "https://opensourcemed.substack.com/subscribe?utm_source=tracker"
GA_ID = "G-202S9N21TE"
BRAND_BLUE = "#2f45c4"
MARKER = "<!-- generated by scripts/build_trial_pages.py; do not edit by hand -->"

OPEN_STATUSES = ["RECRUITING", "NOT_YET_RECRUITING", "ENROLLING_BY_INVITATION"]

STATUS_LABEL = {
    "RECRUITING": "Recruiting",
    "NOT_YET_RECRUITING": "Not yet recruiting",
    "ENROLLING_BY_INVITATION": "Enrolling by invitation",
    "ACTIVE_NOT_RECRUITING": "Active, not recruiting",
    "COMPLETED": "Completed",
    "TERMINATED": "Terminated",
    "WITHDRAWN": "Withdrawn",
    "SUSPENDED": "Suspended",
    "UNKNOWN": "Unknown status",
}
STATUS_ORDER = [
    "RECRUITING", "NOT_YET_RECRUITING", "ENROLLING_BY_INVITATION",
    "ACTIVE_NOT_RECRUITING", "COMPLETED", "SUSPENDED", "TERMINATED",
    "WITHDRAWN", "UNKNOWN",
]
STATUS_CLASS = {
    "RECRUITING": "recruiting", "NOT_YET_RECRUITING": "soon",
    "ENROLLING_BY_INVITATION": "invite", "ACTIVE_NOT_RECRUITING": "active",
    "COMPLETED": "done", "TERMINATED": "stopped", "WITHDRAWN": "stopped",
    "SUSPENDED": "stopped", "UNKNOWN": "unknown",
}
# schema.org MedicalStudyStatus values
SCHEMA_STATUS = {
    "RECRUITING": "Recruiting", "NOT_YET_RECRUITING": "NotYetRecruiting",
    "ENROLLING_BY_INVITATION": "EnrollingByInvitation",
    "ACTIVE_NOT_RECRUITING": "ActiveNotRecruiting", "COMPLETED": "Completed",
    "TERMINATED": "Terminated", "WITHDRAWN": "Withdrawn",
    "SUSPENDED": "Suspended", "UNKNOWN": "ResultsNotAvailable",
}

PHASE_LABEL = {
    "EARLY_PHASE1": "Early Phase 1", "PHASE1": "Phase 1",
    "PHASE1/PHASE2": "Phase 1/2", "PHASE2": "Phase 2",
    "PHASE2/PHASE3": "Phase 2/3", "PHASE3": "Phase 3", "PHASE4": "Phase 4",
    "NA": "Phase not applicable",
}
PHASE_ORDER = ["PHASE4", "PHASE3", "PHASE2/PHASE3", "PHASE2", "PHASE1/PHASE2",
               "PHASE1", "EARLY_PHASE1", "NA"]

SPONSOR_TYPE_LABEL = {
    "INDUSTRY": "Industry", "NIH": "NIH", "FED": "US federal agency",
    "OTHER_GOV": "Other government", "NETWORK": "Research network",
    "OTHER": "Academic / non-profit / other", "INDIV": "Individual",
}

CONDITIONS = {
    "long-covid": {
        "key": "Long COVID / PASC",
        "name": "Long COVID",
        "long_name": "Long COVID / post-acute sequelae of SARS-CoV-2 (PASC)",
        "hub": "/long-covid.html",
    },
    "me-cfs": {
        "key": "ME/CFS",
        "name": "ME/CFS",
        "long_name": "myalgic encephalomyelitis / chronic fatigue syndrome (ME/CFS)",
        "hub": "/me-cfs.html",
    },
    "post-viral-overlap": {
        "key": "Unspecified / Overlap",
        "name": "post-viral overlap",
        "long_name": "overlapping or unspecified post-viral conditions (post-COVID fatigue, dysautonomia, POTS, post-viral syndromes not labelled as Long COVID or ME/CFS)",
        "hub": "/post-viral-illness.html",
    },
}

# Agent strings that are comparators / placebo arms / trial-design artifacts,
# not therapeutic agents.  They are excluded from by-agent pages only.
NOISE_AGENT_RE = re.compile(
    r"placebo|saline|sham|^control|control group|usual care|treatment as usual|"
    r"standard of care|standard care|microcrystalline cellulose|intervention group|"
    r"no intervention|wait.?list|^posture study$|follow up phone calls|transfer package|"
    r"^vehicle$|matching|dummy|comparator|"
    # assessments / procedures that are not therapies
    r"\btests?\b|testing|evaluation|assessment|questionnaire|actigraphy|wearable|"
    r"consul(t)?ation|^pasc core$|biopsy|imaging|^blood\b",
    re.I,
)


# ----------------------------------------------------------------------------
# helpers
# ----------------------------------------------------------------------------
def esc(s) -> str:
    if s is None:
        return ""
    return html.escape(str(s), quote=True)


def clean(s) -> str:
    """Return '' for None / 'None' / 'nan' / 'N/A' style values."""
    if s is None:
        return ""
    s = str(s).strip()
    if s.lower() in ("none", "nan", "null", "n/a", ""):
        return ""
    return s


def slugify(s: str) -> str:
    s = s.lower()
    s = re.sub(r"[¹²³⁰-₟]", "", s)
    s = re.sub(r"[^a-z0-9]+", "-", s)
    return s.strip("-") or "agent"


def month_year(iso: str) -> str:
    try:
        return datetime.fromisoformat(iso.replace("Z", "+00:00")).strftime("%B %Y")
    except Exception:
        return datetime.utcnow().strftime("%B %Y")


def long_date(iso: str) -> str:
    try:
        return datetime.fromisoformat(iso.replace("Z", "+00:00")).strftime("%d %B %Y")
    except Exception:
        return iso


def fmt_date(d) -> str:
    d = clean(d)
    if not d:
        return ""
    for fmt, out in (("%Y-%m-%d", "%b %Y"), ("%Y-%m", "%b %Y"), ("%Y", "%Y")):
        try:
            return datetime.strptime(d, fmt).strftime(out)
        except ValueError:
            pass
    return d


_LABEL_RE = re.compile(
    r"^\s*(background|objective|objectives|aim|aims|purpose|rationale|introduction|"
    r"design|methods|eligibility|hypothesis|summary|brief summary|study description)\s*:?\s*$",
    re.I,
)


def summarise(text, max_sent=3, max_chars=420) -> str:
    """Trim a ClinicalTrials.gov brief summary to 2-3 readable sentences."""
    text = clean(text)
    if not text:
        return ""
    # drop section labels like "Background:" on their own line
    lines = [ln.strip() for ln in text.splitlines()]
    lines = [ln for ln in lines if ln and not _LABEL_RE.match(ln)]
    text = " ".join(lines)
    text = re.sub(r"^\s*(background|objective|purpose|aims?)\s*:\s*", "", text, flags=re.I)
    text = re.sub(r"\s+", " ", text).strip()
    sents = re.split(r"(?<=[.!?])\s+(?=[A-Z0-9\"'(])", text)
    out, total = [], 0
    for s in sents:
        if not s:
            continue
        if out and (len(out) >= max_sent or total + len(s) > max_chars):
            break
        out.append(s)
        total += len(s)
    res = " ".join(out).strip()
    if len(res) > max_chars + 120:
        res = res[: max_chars + 100].rsplit(" ", 1)[0] + "…"
    if res and res[-1] not in ".!?…":
        res += "."
    return res


def phase_key(p: str) -> int:
    p = clean(p) or "NA"
    return PHASE_ORDER.index(p) if p in PHASE_ORDER else len(PHASE_ORDER)


def status_key(s: str) -> int:
    return STATUS_ORDER.index(s) if s in STATUS_ORDER else len(STATUS_ORDER)


def phase_label(p) -> str:
    p = clean(p) or "NA"
    return PHASE_LABEL.get(p, p.replace("_", " ").title())


def status_label(s) -> str:
    s = clean(s) or "UNKNOWN"
    return STATUS_LABEL.get(s, s.replace("_", " ").title())


def sponsor_type_label(s) -> str:
    s = clean(s)
    return SPONSOR_TYPE_LABEL.get(s, s.title()) if s else ""


def jsonld(obj) -> str:
    return '<script type="application/ld+json">\n' + json.dumps(obj, ensure_ascii=False, indent=1).replace("</", "<\\/") + "\n</script>"


# ----------------------------------------------------------------------------
# page chrome
# ----------------------------------------------------------------------------
EXTRA_CSS = f"""
    :root {{ --brand-blue: {BRAND_BLUE}; }}
    .main-section {{ background: #fff; padding: 8px 0 24px; }}
    .main-section .section-inner {{ max-width: 1200px; margin: 0 auto; padding: 0 var(--ui-gutter, 24px); }}
    .trials-intro {{ max-width: 72ch; margin: 0 0 28px; font-size: 1.02rem; line-height: 1.7; color: var(--ui-text, #3d4466); }}
    .trials-intro p {{ margin-bottom: 0.9rem; }}
    .trials-intro a, .trials-note a, .faq a, .cite-box a, .trial-card a:not(.btn-trial), .agent-grid a, .updated-line a {{ color: var(--brand-blue); }}
    .count-row {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(150px, 1fr)); gap: 12px; margin: 0 0 32px; }}
    .count-pill {{ display: grid; gap: 8px; align-content: start; background: #fff; border: 1px solid #e6e8f2; border-radius: 14px; padding: 16px 18px; font-size: 12px; line-height: 1.4; font-weight: 600; letter-spacing: .06em; text-transform: uppercase; color: #6b7194; box-shadow: 0 1px 2px rgba(14,20,68,.05), 0 2px 8px rgba(14,20,68,.04); }}
    .count-pill strong {{ display: block; font-family: "Fraunces", Georgia, serif; font-weight: 500; font-size: 2rem; line-height: 1; letter-spacing: -.02em; color: #0e1444; text-transform: none; }}
    .trials-note {{ background: #f7f8fc; border: 1px solid #e6e8f2; border-radius: 12px; padding: 14px 18px; font-size: 0.9rem; color: #2a3160; margin: 0 0 18px; line-height: 1.65; }}
    .trials-note strong {{ font-weight: 700; color: #0e1444; }}
    .trials-toc {{ display: flex; flex-wrap: wrap; gap: 8px; font-size: 0.86rem; margin: 28px 0 8px; padding: 14px 0; border-top: 1px solid #e6e8f2; border-bottom: 1px solid #e6e8f2; }}
    .trials-toc a {{ display: inline-block; padding: 6px 14px; border-radius: 999px; background: #f7f8fc; border: 1px solid #e6e8f2; color: #2a3160 !important; text-decoration: none !important; font-weight: 500; }}
    .trials-toc a:hover {{ background: #fff; border-color: #d5d9ea; color: #0e1444 !important; }}
    .status-group {{ margin: 56px 0 12px; }}
    .status-group h2 {{ font-size: clamp(1.4rem, 2.2vw, 1.7rem); margin-bottom: 6px; color: #0e1444; letter-spacing: -.015em; }}
    .status-group .group-sub {{ font-size: 0.92rem; color: #6b7194; margin-bottom: 8px; max-width: 72ch; }}
    .phase-group h3 {{ font-size: 11.5px; font-weight: 700; letter-spacing: .12em; text-transform: uppercase; margin: 28px 0 12px; color: #6b7194; }}
    .phase-group h3 span {{ font-size: inherit !important; }}
    .card-list {{ display: flex; flex-direction: column; gap: 14px; }}
    .trial-card {{ border: 1px solid #e6e8f2 !important; border-radius: 14px !important; padding: 20px 24px 20px 28px !important; box-shadow: 0 1px 2px rgba(14,20,68,.05), 0 2px 8px rgba(14,20,68,.04) !important; }}
    .trial-card:hover {{ transform: translateY(-2px) !important; box-shadow: 0 2px 6px rgba(14,20,68,.05), 0 14px 34px rgba(14,20,68,.08) !important; border-color: #d5d9ea !important; }}
    .trial-card::before {{ top: 0 !important; bottom: 0 !important; left: 0 !important; right: auto !important; width: 4px !important; height: auto !important; }}
    .trial-card.status-recruiting::before {{ background: #047857; }}
    .trial-card.status-soon::before {{ background: #2f45c4; }}
    .trial-card.status-invite::before {{ background: #0e1444; }}
    .trial-card.status-active::before {{ background: #ff9800; }}
    .trial-card.status-done::before {{ background: #9aa0bd; }}
    .trial-card.status-stopped::before {{ background: #c2410c; }}
    .trial-card.status-unknown::before {{ background: #d5d9ea; }}
    .trial-card .trial-title {{ font-size: 1.04rem; font-weight: 650; line-height: 1.42; margin-bottom: 10px; }}
    .trial-card .trial-meta {{ font-size: 0.84rem; color: #6b7194; margin-bottom: 4px; line-height: 1.6; }}
    .trial-card .trial-meta strong {{ color: #2a3160; font-weight: 600; }}
    .trial-card .btn-trial {{ margin-top: 12px; border-radius: 999px !important; border: 1px solid #d5d9ea !important; padding: 6px 14px; font-weight: 600 !important; color: #0e1444; }}
    .trial-card .btn-trial:hover {{ background: #f7f8fc !important; border-color: #c4c9e0 !important; color: #0e1444 !important; transform: none !important; }}
    .badge {{ display: inline-flex; align-items: center; font-size: 12px; font-weight: 650; padding: 2px 10px; border-radius: 999px; margin: 0 4px 4px 0; vertical-align: middle; letter-spacing: 0; border: 1px solid transparent; }}
    .badge-recruiting {{ background: #e7f7f0; color: #047857; border-color: #bfe9d6; }}
    .badge-soon {{ background: #eaf0ff; color: #1d4ed8; border-color: #cfdcff; }}
    .badge-invite {{ background: #eef0f8; color: #18206a; border-color: #d5d9ea; }}
    .badge-active {{ background: #fff7df; color: #a16207; border-color: #f5e0a3; }}
    .badge-done {{ background: #f7f8fc; color: #3d4466; border-color: #e6e8f2; }}
    .badge-stopped {{ background: #fff1e8; color: #c2410c; border-color: #ffd9c2; }}
    .badge-unknown {{ background: #f7f8fc; color: #6b7194; border-color: #e6e8f2; }}
    .badge-phase {{ background: #fff; color: #2a3160; border-color: #d5d9ea; }}
    .trial-summary {{ font-size: 0.92rem; line-height: 1.65; margin: 10px 0 2px; color: #3d4466; max-width: 80ch; }}
    .trial-card .trial-title a {{ color: #0e1444 !important; text-decoration: none !important; }}
    .trial-card .trial-title a:hover {{ color: var(--brand-blue) !important; text-decoration: underline !important; text-underline-offset: 3px; }}
    .faq {{ margin: 64px 0 24px; max-width: 820px; }}
    .faq h2 {{ font-size: clamp(1.4rem, 2.2vw, 1.7rem); margin-bottom: 14px; color: #0e1444; }}
    .faq details {{ border: 1px solid #e6e8f2; border-radius: 12px; padding: 0 18px; margin-bottom: 10px; background: #fff; box-shadow: 0 1px 2px rgba(14,20,68,.05); }}
    .faq summary {{ font-weight: 600; cursor: pointer; font-size: 0.97rem; color: #0e1444; padding: 14px 0; list-style: none; display: flex; gap: 10px; align-items: center; }}
    .faq summary::-webkit-details-marker {{ display: none; }}
    .faq summary::before {{ content: ""; width: 8px; height: 8px; flex: none; border-right: 2px solid #f2711c; border-bottom: 2px solid #f2711c; transform: rotate(-45deg); transition: transform .2s; }}
    .faq details[open] summary::before {{ transform: rotate(45deg); }}
    .faq details p {{ font-size: 0.93rem; margin: 0 0 16px; line-height: 1.65; color: #3d4466; }}
    .cite-box {{ background: #f7f8fc; border: 1px solid #e6e8f2; border-radius: 14px; padding: 18px 20px; font-size: 0.88rem; margin: 28px 0; max-width: 820px; line-height: 1.65; color: #2a3160; }}
    .cite-box > strong:first-child {{ display: inline-block; font-size: 11.5px; letter-spacing: .12em; text-transform: uppercase; color: #6b7194; margin-bottom: 6px; }}
    .cite-box code {{ font-size: 0.8rem; word-break: break-all; }}
    .substack-box {{ background: #fff; border: 1px solid #e6e8f2; border-left: 4px solid #ff9800; border-radius: 14px; padding: 22px 24px; margin: 32px 0; max-width: 820px; box-shadow: 0 1px 2px rgba(14,20,68,.05), 0 2px 8px rgba(14,20,68,.04); color: #0e1444; }}
    .substack-box p {{ color: #6b7194; }}
    .substack-box a.btn {{ display: inline-flex; margin-top: 12px; background: linear-gradient(180deg, #ffa31a, #f2711c); color: #fff !important; text-decoration: none !important; padding: 10px 18px; border-radius: 999px; font-weight: 650; font-size: 0.9rem; box-shadow: 0 6px 16px rgba(242,113,28,.28); }}
    .updated-line {{ font-size: 0.85rem; color: #6b7194; margin: 0 0 22px; max-width: 90ch; }}
    .agent-grid {{ display: grid; grid-template-columns: repeat(auto-fill, minmax(240px, 1fr)); gap: 12px; margin: 20px 0 40px; }}
    .agent-grid a {{ display: block; background: #fff; border: 1px solid #e6e8f2; border-radius: 12px; padding: 14px 16px; text-decoration: none !important; font-size: 0.95rem; font-weight: 600; color: #0e1444 !important; box-shadow: 0 1px 2px rgba(14,20,68,.05); transition: border-color .2s, box-shadow .2s, transform .2s; }}
    .agent-grid a:hover {{ border-color: #d5d9ea; box-shadow: 0 2px 6px rgba(14,20,68,.05), 0 14px 34px rgba(14,20,68,.08); transform: translateY(-1px); }}
    .agent-grid a span {{ display: block; font-size: 0.8rem; font-weight: 500; color: #6b7194; margin-top: 3px; }}
    .hub-grid {{ display: grid; grid-template-columns: repeat(auto-fill, minmax(min(100%, 300px), 1fr)); gap: 16px; margin: 20px 0 40px; }}
    .hub-card {{ background: #fff; border: 1px solid #e6e8f2; border-radius: 14px; padding: 22px 24px; box-shadow: 0 1px 2px rgba(14,20,68,.05), 0 2px 8px rgba(14,20,68,.04); transition: border-color .2s, box-shadow .2s, transform .2s; }}
    .hub-card:hover {{ border-color: #d5d9ea; box-shadow: 0 2px 6px rgba(14,20,68,.05), 0 14px 34px rgba(14,20,68,.08); transform: translateY(-2px); }}
    .hub-card h3 {{ font-size: 1.06rem; margin: 10px 0 8px; line-height: 1.35; }}
    .hub-card h3 a {{ color: #0e1444 !important; text-decoration: none !important; }}
    .hub-card h3 a:hover {{ color: var(--brand-blue) !important; }}
    .hub-card p a {{ color: var(--brand-blue); text-decoration: none; font-weight: 600; }}
    .hub-card p {{ font-size: 0.9rem; color: #3d4466; line-height: 1.6; }}
    .hub-card .n {{ font-family: "Fraunces", Georgia, serif; font-size: 2.3rem; font-weight: 500; line-height: 1; letter-spacing: -.02em; color: #0e1444; }}
    .empty-note {{ font-size: 0.92rem; color: #6b7194; padding: 18px; border: 1px dashed #d5d9ea; border-radius: 12px; background: #f7f8fc; }}
    .breadcrumbs {{ font-size: 13px; color: #6b7194; margin: 22px 0 18px; }}
    .breadcrumbs a {{ color: #6b7194 !important; text-decoration: none !important; }}
    .breadcrumbs a:hover {{ color: #0e1444 !important; }}
    .nav-toggle {{ display: none; background: none; border: 0; cursor: pointer; padding: 6px; }}
    .nav-toggle span {{ display: block; width: 24px; height: 2px; background: var(--primary-dark); margin: 5px 0; border-radius: 2px; }}
    @media (max-width: 768px) {{ .trials-intro {{ font-size: 0.97rem; }} .count-row {{ grid-template-columns: repeat(2, minmax(0, 1fr)); gap: 10px; }} .count-pill strong {{ font-size: 1.6rem; }} .trial-card {{ padding: 18px 18px 18px 22px !important; }} }}
"""

NAV = """
<nav>
  <div class="nav-container">
    <a href="https://opensourcemed.info" class="nav-brand">
      Open Source <span>Medicine</span>
      <span class="nav-brand-sub">Research Tracker</span>
    </a>
    <button class="nav-toggle" aria-label="Toggle navigation menu" aria-expanded="false" onclick="var l=document.querySelector('.nav-links');l.classList.toggle('open');this.classList.toggle('open');this.setAttribute('aria-expanded',l.classList.contains('open'));">
      <span></span><span></span><span></span>
    </button>
    <ul class="nav-links">
      <li><a href="/index.html">Research Tracker</a></li>
      <li><a href="/biomarker-atlas.html">Biomarkers</a></li>
      <li><a href="/clinical_trials.html">Trial Finder</a></li>
      <li><a href="/trials/index.html" class="nav-active">Recruiting Trials</a></li>
      <li><a href="/agents.html">Agents</a></li>
      <li><a href="https://opensourcemed.info">opensourcemed.info</a></li>
      <li><a href="https://www.paypal.com/ncp/payment/A2MK3BCVE4X7C" class="nav-support">Support Our Work</a></li>
    </ul>
  </div>
</nav>
"""

FOOTER = """
<footer class="osmf-network-footer">
  <div class="osmf-network-inner">
    <div class="footer-brand">Open Source Medicine Foundation</div>
    <div class="footer-links">
      <a href="https://opensourcemed.info">Open Source Medicine Foundation</a>
      <a href="/index.html">Research Tracker</a>
      <a href="/clinical_trials.html">Trial Finder</a>
      <a href="/trials/index.html">Recruiting Trials</a>
      <a href="/biomarker-atlas.html">Biomarker Atlas</a>
      <a href="/agents.html">Therapeutic Agents</a>
      <a href="https://opensourcemed.substack.com">Substack</a>
      <a href="https://opensourcemed.info/#contact">Contact</a>
    </div>
    <div class="footer-note">Trial data from ClinicalTrials.gov (NLM), refreshed automatically via GitHub Actions. Not medical advice. OSMF does not run or recruit for these trials.</div>
  </div>
</footer>
"""

DISCLAIMER = """
    <div class="disclaimer"><span>⚠️</span><div><strong>Not medical advice.</strong> This page is an automatically compiled index of entries on ClinicalTrials.gov. Listing here is not an endorsement of any trial, sponsor or treatment, and trial status can change between our refreshes. Always confirm details on ClinicalTrials.gov and discuss participation with your own clinician.</div></div>
"""


def page(title, description, canonical, body, ld_graph, og_title=None):
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
{MARKER}
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <!-- Google tag (gtag.js) -->
  <script async src="https://www.googletagmanager.com/gtag/js?id={GA_ID}"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){{dataLayer.push(arguments);}}
    gtag('js', new Date());
    gtag('config', '{GA_ID}');
  </script>
  <title>{esc(title)}</title>
  <meta name="description" content="{esc(description)}">
  <meta name="robots" content="index, follow">
  <link rel="canonical" href="{canonical}">
  <meta property="og:type" content="website">
  <meta property="og:site_name" content="Open Source Medicine Foundation">
  <meta property="og:title" content="{esc(og_title or title)}">
  <meta property="og:description" content="{esc(description)}">
  <meta property="og:url" content="{canonical}">
  <meta property="og:image" content="https://opensourcemed.info/favicon.png">
  <meta name="twitter:card" content="summary">
  <meta name="twitter:title" content="{esc(og_title or title)}">
  <meta name="twitter:description" content="{esc(description)}">
  <link rel="icon" href="https://opensourcemed.info/favicon.png" type="image/png">
  <meta name="theme-color" content="#0e1444">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="/tracker.css">
  <style>{EXTRA_CSS}  </style>
{jsonld({"@context": "https://schema.org", "@graph": ld_graph})}
</head>
<body>
{NAV}
{body}
{FOOTER}
</body>
</html>
"""


def breadcrumb_ld(items):
    return {
        "@type": "BreadcrumbList",
        "itemListElement": [
            {"@type": "ListItem", "position": i + 1, "name": n, "item": u}
            for i, (n, u) in enumerate(items)
        ],
    }


def breadcrumb_html(items):
    parts = []
    for n, u in items[:-1]:
        parts.append(f'<a href="{esc(u)}">{esc(n)}</a>')
    parts.append(esc(items[-1][0]))
    return '<div class="breadcrumbs osmf-crumbs">' + " › ".join(parts) + "</div>"


def dataset_ld(last_run):
    return {
        "@type": "Dataset",
        "@id": DATASET_URL,
        "name": "OSMF post-viral clinical trials dataset (Long COVID, ME/CFS, post-viral overlap)",
        "description": "Structured extract of interventional trials registered on ClinicalTrials.gov for Long COVID / PASC, ME/CFS and overlapping post-viral conditions, with normalised therapeutic agents, phase, status and sponsor.",
        "url": DATASET_URL,
        "license": "https://creativecommons.org/licenses/by/4.0/",
        "isAccessibleForFree": True,
        "dateModified": last_run[:10],
        "creator": {"@type": "Organization", "name": "Open Source Medicine Foundation", "url": "https://opensourcemed.info"},
        "distribution": [{"@type": "DataDownload", "encodingFormat": "application/json", "contentUrl": DATASET_URL}],
        "isBasedOn": "https://clinicaltrials.gov/",
    }


def faq_ld(faq):
    return {
        "@type": "FAQPage",
        "mainEntity": [
            {"@type": "Question", "name": q, "acceptedAnswer": {"@type": "Answer", "text": re.sub(r"<[^>]+>", "", a)}}
            for q, a in faq
        ],
    }


def faq_html(faq):
    out = ['<section class="faq" id="faq"><h2>Frequently asked questions</h2>']
    for q, a in faq:
        out.append(f"<details><summary>{esc(q)}</summary><p>{a}</p></details>")
    out.append("</section>")
    return "\n".join(out)


def trial_ld(t, condition_name=None):
    d = {
        "@type": "MedicalTrial",
        "name": clean(t.get("title")) or t["nct_id"],
        "url": t["url"],
        "identifier": t["nct_id"],
        "status": SCHEMA_STATUS.get(t["status"], t["status"].replace("_", " ").title()),
        "phase": phase_label(t.get("phase")),
    }
    if clean(t.get("sponsor")):
        d["sponsor"] = {"@type": "Organization", "name": clean(t["sponsor"])}
    conds = t.get("conditions_raw") or ([condition_name] if condition_name else [])
    if conds:
        d["healthCondition"] = [{"@type": "MedicalCondition", "name": c} for c in conds[:5]]
    return d


def itemlist_ld(name, trials, condition_name=None):
    return {
        "@type": "ItemList",
        "name": name,
        "numberOfItems": len(trials),
        "itemListElement": [
            {"@type": "ListItem", "position": i + 1, "item": trial_ld(t, condition_name)}
            for i, t in enumerate(trials)
        ],
    }


# ----------------------------------------------------------------------------
# cards
# ----------------------------------------------------------------------------
def card(t, show_conditions=False, agent_links=None):
    st = t["status"]
    cls = STATUS_CLASS.get(st, "unknown")
    agents = t["agents"]
    if agent_links:
        agent_html = ", ".join(
            f'<a href="/trials/by-agent/{agent_links[a]}.html">{esc(a)}</a>' if a in agent_links else esc(a)
            for a in agents
        )
    else:
        agent_html = esc(", ".join(agents))
    meta = []
    meta.append(f'<span class="badge badge-{cls}">{esc(status_label(st))}</span><span class="badge badge-phase">{esc(phase_label(t.get("phase")))}</span> <a href="{esc(t["url"])}" target="_blank" rel="noopener">{esc(t["nct_id"])}</a>')
    sponsor = clean(t.get("sponsor"))
    stype = sponsor_type_label(t.get("sponsor_type"))
    if sponsor:
        meta.append(f"<strong>Sponsor:</strong> {esc(sponsor)}" + (f" ({esc(stype)})" if stype else ""))
    if agents:
        meta.append(f"<strong>Intervention(s):</strong> {agent_html}")
    if show_conditions:
        mc = ", ".join(t["mapped_conditions"])
        if mc:
            meta.append(f"<strong>Condition group:</strong> {esc(mc)}")
    dates = []
    if fmt_date(t.get("start_date")):
        dates.append(f"<strong>Start:</strong> {esc(fmt_date(t['start_date']))}")
    if fmt_date(t.get("primary_completion_date")):
        dates.append(f"<strong>Primary completion:</strong> {esc(fmt_date(t['primary_completion_date']))}")
    enr = t.get("enrollment")
    if isinstance(enr, (int, float)) and enr > 0:
        et = clean(t.get("enrollment_type")).lower()
        dates.append(f"<strong>Enrollment:</strong> {int(enr)}" + (f" ({et})" if et else ""))
    if dates:
        meta.append(" &nbsp;|&nbsp; ".join(dates))
    if fmt_date(t.get("last_updated")):
        meta.append(f"<strong>Record last updated:</strong> {esc(fmt_date(t['last_updated']))}")
    summary = t["summary"]
    summary_html = f'<p class="trial-summary">{esc(summary)}</p>' if summary else ""
    meta_html = "\n  ".join(f'<div class="trial-meta">{m}</div>' for m in meta)
    return f"""<article class="trial-card status-{cls}" id="{esc(t['nct_id'])}">
  <div class="trial-title"><a href="{esc(t['url'])}" target="_blank" rel="noopener">{esc(clean(t.get('title')) or t['nct_id'])}</a></div>
  {meta_html}
  {summary_html}
  <a href="{esc(t['url'])}" target="_blank" rel="noopener" class="btn-trial">View on ClinicalTrials.gov ↗</a>
</article>"""


def _recency(t):
    return (clean(t.get("last_updated")), t["nct_id"])


def grouped_cards(trials, by_phase=True, show_conditions=False, agent_links=None, group_desc=None):
    """Group by status (then phase) and render."""
    out = []
    by_status = defaultdict(list)
    for t in trials:
        by_status[t["status"]].append(t)
    for st in sorted(by_status, key=status_key):
        group = by_status[st]
        out.append(f'<section class="status-group" id="status-{esc(st.lower())}"><h2>{esc(status_label(st))} <span style="color:var(--text-gray);font-weight:500;font-size:0.9rem">({len(group)})</span></h2>')
        if group_desc and st in group_desc:
            out.append(f'<p class="group-sub">{group_desc[st]}</p>')
        if by_phase:
            by_phase_map = defaultdict(list)
            for t in group:
                by_phase_map[clean(t.get("phase")) or "NA"].append(t)
            for ph in sorted(by_phase_map, key=phase_key):
                items = sorted(by_phase_map[ph], key=_recency, reverse=True)
                out.append(f'<div class="phase-group"><h3>{esc(phase_label(ph))} <span style="color:var(--text-gray);font-weight:500">({len(items)})</span></h3><div class="card-list">')
                out.extend(card(t, show_conditions, agent_links) for t in items)
                out.append("</div></div>")
        else:
            items = sorted(group, key=_recency, reverse=True)
            out.append('<div class="card-list">')
            out.extend(card(t, show_conditions, agent_links) for t in items)
            out.append("</div>")
        out.append("</section>")
    return "\n".join(out)


def counts_html(pairs):
    return '<div class="count-row">' + "".join(
        f'<span class="count-pill"><strong>{n}</strong> {esc(label)}</span>' for label, n in pairs
    ) + "</div>"


def substack_html():
    return f"""<div class="substack-box">
  <strong>Get new recruiting trials in your inbox.</strong>
  <p style="font-size:0.88rem;margin-top:0.3rem">We summarise newly registered post-viral trials and notable results on the OSMF Substack.</p>
  <a class="btn" href="{SUBSTACK}" rel="noopener">Subscribe on Substack</a>
</div>"""


def cite_html(url, title, last_run):
    return f"""<div class="cite-box"><strong>Cite this page</strong><br>
Open Source Medicine Foundation. <em>{esc(title)}</em>. Research Tracker, {esc(long_date(last_run))}. <code>{esc(url)}</code><br>
Underlying dataset (JSON, CC BY 4.0): <code><a href="{DATASET_URL}">{DATASET_URL}</a></code>. Source records: ClinicalTrials.gov.</div>"""


def updated_html(last_run):
    return f'<p class="updated-line">Last updated {esc(long_date(last_run))} from ClinicalTrials.gov. Trial statuses are refreshed automatically; check the registry record for the latest status and contact details.</p>'


COMMON_FAQ = [
    ("How do I join a clinical trial?",
     'Open the trial\'s ClinicalTrials.gov record (the "View on ClinicalTrials.gov" button), read the <em>Eligibility Criteria</em> and <em>Contacts and Locations</em> sections, and contact the study team listed there. Trials only enrol at the sites shown in the record, so check whether a site is near you or whether the study is remote/decentralised. Your own clinician can help you judge whether a trial is a sensible option and may need to provide medical records.'),
    ("What do the trial phases mean?",
     '<strong>Early Phase 1 / Phase 1</strong> studies test safety and dosing in a small group. <strong>Phase 2</strong> studies look for a signal of benefit in a larger group and keep checking safety. <strong>Phase 3</strong> studies are large confirmatory trials designed to show whether a treatment works well enough for approval. <strong>Phase 4</strong> studies follow approved treatments after they reach the market. <strong>"Phase not applicable"</strong> is used by the registry for behavioural, device, rehabilitation and other non-drug interventions.'),
    ("What is the difference between recruiting, not yet recruiting and enrolling by invitation?",
     '<strong>Recruiting</strong> means the study is actively enrolling participants. <strong>Not yet recruiting</strong> means the study is registered but has not opened enrolment; you can often register interest with the contact listed. <strong>Enrolling by invitation</strong> means participants are selected from a pre-defined group (for example an existing cohort) and the public generally cannot volunteer.'),
    ("Does the Open Source Medicine Foundation run these trials?",
     'No. OSMF does not sponsor, run or recruit for any trial on this page. We compile public registry entries from ClinicalTrials.gov so patients and clinicians can find them in one place. For questions about a specific study, contact the sponsor or study team listed on its ClinicalTrials.gov record.'),
    ("How often is this list updated?",
     'The underlying dataset is rebuilt automatically from the ClinicalTrials.gov API and these pages are regenerated from it. The date at the top of the page is the last successful refresh. Registry entries can lag the real-world status of a study, so a trial shown as recruiting may already be full.'),
    ("Why is a trial I know about missing?",
     'Our search targets interventional studies whose registered conditions map to Long COVID / PASC, ME/CFS or overlapping post-viral syndromes. Observational studies, trials registered only on non-US registries (EU CTR, ISRCTN, ANZCTR, etc.), and trials whose condition terms did not match our mapping are not included. The full ClinicalTrials.gov search is always more complete than any curated index.'),
]


def collection_ld(url, title, description, last_run, about=None):
    d = {
        "@type": "CollectionPage", "@id": url + "#webpage", "url": url, "name": title,
        "description": description, "dateModified": last_run[:10], "inLanguage": "en",
        "isPartOf": {"@type": "WebSite", "@id": f"{SITE}/#website", "url": f"{SITE}/", "name": "Open Source Medicine — Research Tracker"},
        "publisher": {"@type": "Organization", "name": "Open Source Medicine Foundation", "url": "https://opensourcemed.info"},
    }
    if about:
        d["about"] = about
    return d


# ----------------------------------------------------------------------------
# page builders
# ----------------------------------------------------------------------------
def build_recruiting_page(slug, cfg, trials, last_run, agent_links):
    name = cfg["name"]
    url = f"{SITE}/trials/{slug}-recruiting.html"
    my = month_year(last_run)
    title = f"Recruiting {name} clinical trials (updated {my})"
    open_trials = [t for t in trials if t["status"] in OPEN_STATUSES and cfg["key"] in t["mapped_conditions"]]
    n_rec = sum(1 for t in open_trials if t["status"] == "RECRUITING")
    n_soon = sum(1 for t in open_trials if t["status"] == "NOT_YET_RECRUITING")
    n_inv = sum(1 for t in open_trials if t["status"] == "ENROLLING_BY_INVITATION")
    n_all = sum(1 for t in trials if cfg["key"] in t["mapped_conditions"])
    phases = Counter(clean(t.get("phase")) or "NA" for t in open_trials)
    n_drug = sum(v for k, v in phases.items() if k != "NA")
    agent_counter = Counter(a for t in open_trials for a in t["agents"] if not NOISE_AGENT_RE.search(a))
    top_agents = [a for a, _ in agent_counter.most_common(8)]
    description = (f"{len(open_trials)} {name} clinical trials currently recruiting, not yet recruiting or enrolling by invitation on ClinicalTrials.gov, "
                   f"grouped by status and phase with sponsor, intervention and plain-language summaries. Updated {my}.")

    intro = f"""<div class="trials-intro">
<p>This page lists every interventional study for {esc(cfg['long_name'])} that ClinicalTrials.gov currently shows as <strong>recruiting</strong>, <strong>not yet recruiting</strong> or <strong>enrolling by invitation</strong>. It is rebuilt automatically from the registry so it stays current without manual curation.</p>
<p>Of {len(open_trials)} open trials, {n_rec} are actively recruiting, {n_soon} are registered but not yet open, and {n_inv} enrol by invitation only. {n_drug} are phased drug or biologic studies; the rest are behavioural, rehabilitation, device or other non-drug interventions, which the registry labels "phase not applicable".{(' Frequently tested interventions right now include ' + esc(', '.join(top_agents)) + '.') if top_agents else ''}</p>
<p>Looking for trials that have finished? See the <a href="/trials/all-{slug}.html">complete {esc(name)} trial list</a> ({n_all} trials including completed and terminated studies), or use the interactive <a href="/clinical_trials.html">trial finder</a> to filter by agent, phase, sponsor and status.</p>
</div>"""
    note = """<div class="trials-note"><strong>How to read this list.</strong> Trials are grouped first by recruitment status, then by phase (later phases first). Each card shows the registry ID, sponsor, intervention(s) tested, planned start and primary-completion dates and target enrollment, plus a short summary trimmed from the registry description. Our extract does not include site locations or eligibility criteria, so open the record to see where a study enrols, who qualifies and whom to contact.</div>"""
    group_desc = {
        "RECRUITING": "Actively enrolling. Contact details and sites are on the ClinicalTrials.gov record.",
        "NOT_YET_RECRUITING": "Registered but not yet open. The planned start date is an estimate; some sponsors accept expressions of interest early.",
        "ENROLLING_BY_INVITATION": "Participants are invited from a pre-selected group; the public generally cannot volunteer.",
    }
    counts = counts_html([("open trials", len(open_trials)), ("recruiting", n_rec), ("not yet recruiting", n_soon), ("enrolling by invitation", n_inv), (f"total {name} trials tracked", n_all)])
    toc = '<div class="trials-toc">' + " ".join(
        f'<a href="#status-{st.lower()}">{esc(status_label(st))}</a>' for st in OPEN_STATUSES if any(t["status"] == st for t in open_trials)
    ) + ' <a href="#faq">FAQ</a></div>'
    if open_trials:
        body_cards = grouped_cards(open_trials, by_phase=True, agent_links=agent_links, group_desc=group_desc)
    else:
        body_cards = '<p class="empty-note">No open trials for this condition in the current extract. Check back after the next refresh or search ClinicalTrials.gov directly.</p>'

    faq = COMMON_FAQ
    crumbs = [("Research Tracker", f"{SITE}/"), ("Clinical trials", f"{SITE}/trials/index.html"), (f"Recruiting {name} trials", url)]
    body = f"""
<section class="page-hero trials-hero">
  <div class="hero-eyebrow">Open clinical trials · {esc(name)}</div>
  <h1>Recruiting {esc(name)} <span>clinical trials</span></h1>
  <p>Updated {esc(my)} · {len(open_trials)} trials open to enrolment on ClinicalTrials.gov</p>
</section>
<main class="main-section">
  <div class="section-inner">
    {breadcrumb_html(crumbs)}
    {updated_html(last_run)}
    {counts}
    {intro}
    {note}
    {DISCLAIMER}
    {toc}
    {body_cards}
    {faq_html(faq)}
    {substack_html()}
    {cite_html(url, title, last_run)}
    <p class="updated-line">Related: <a href="{esc(cfg['hub'])}">{esc(name)} research hub</a> · <a href="/trials/by-agent/index.html">trials by therapeutic agent</a> · <a href="/trials/all-{slug}.html">all {esc(name)} trials</a> · <a href="/clinical_trials.html">interactive trial finder</a>.</p>
  </div>
</main>
"""
    graph = [
        collection_ld(url, title, description, last_run, {"@type": "MedicalCondition", "name": cfg["key"]}),
        breadcrumb_ld(crumbs),
        faq_ld(faq),
        itemlist_ld(title, open_trials, cfg["key"]),
        dataset_ld(last_run),
    ]
    return page(title, description, url, body, graph), len(open_trials)


def build_all_page(slug, cfg, trials, last_run, agent_links):
    name = cfg["name"]
    url = f"{SITE}/trials/all-{slug}.html"
    my = month_year(last_run)
    mine = [t for t in trials if cfg["key"] in t["mapped_conditions"]]
    sc = Counter(t["status"] for t in mine)
    title = f"All {name} clinical trials on ClinicalTrials.gov ({len(mine)} trials, updated {my})"
    description = (f"Complete list of {len(mine)} interventional {name} trials registered on ClinicalTrials.gov, including {sc.get('COMPLETED', 0)} completed and "
                   f"{sc.get('TERMINATED', 0) + sc.get('WITHDRAWN', 0)} terminated or withdrawn studies, with status badges, phase, sponsor and interventions. Useful for checking whether a treatment has been trialled.")
    intro = f"""<div class="trials-intro">
<p>Every interventional study for {esc(cfg['long_name'])} in our ClinicalTrials.gov extract, regardless of status. Use this page to answer "has <em>X</em> been trialled in {esc(name)}?": search the page (Ctrl/Cmd-F) for a drug or intervention name, or browse the <a href="/trials/by-agent/index.html">by-agent index</a>.</p>
<p>Trials are grouped by status. Completed, terminated and withdrawn studies are included because they are often the most informative: a terminated trial may indicate futility, safety concerns or simply funding problems, so always read the record. Only trials <a href="/trials/{slug}-recruiting.html">currently open to enrolment</a> are shown on the recruiting page.</p>
</div>"""
    counts = counts_html([(status_label(st).lower(), sc[st]) for st in STATUS_ORDER if sc.get(st)])
    note = """<div class="trials-note"><strong>Status badges:</strong> green = recruiting, blue = not yet recruiting, purple = enrolling by invitation, orange = active but closed to enrolment, grey = completed, red = terminated / withdrawn / suspended. "Unknown status" means the sponsor has not updated the record for more than two years past its expected completion date.</div>"""
    toc = '<div class="trials-toc">' + " ".join(
        f'<a href="#status-{st.lower()}">{esc(status_label(st))} ({sc[st]})</a>' for st in STATUS_ORDER if sc.get(st)
    ) + "</div>"
    faq = [COMMON_FAQ[3], COMMON_FAQ[1], COMMON_FAQ[5],
           ("What does \"terminated\" or \"withdrawn\" mean?",
            "<strong>Terminated</strong> means the study started but stopped early, for reasons that can include lack of funding, slow recruitment, safety signals or clear futility; the record often states why. <strong>Withdrawn</strong> means the study was cancelled before enrolling anyone. <strong>Suspended</strong> means enrolment is paused and may resume.")]
    crumbs = [("Research Tracker", f"{SITE}/"), ("Clinical trials", f"{SITE}/trials/index.html"), (f"All {name} trials", url)]
    body = f"""
<section class="page-hero trials-hero">
  <div class="hero-eyebrow">Complete trial list · {esc(name)}</div>
  <h1>All {esc(name)} <span>clinical trials</span></h1>
  <p>{len(mine)} interventional trials on ClinicalTrials.gov, all statuses · updated {esc(my)}</p>
</section>
<main class="main-section">
  <div class="section-inner">
    {breadcrumb_html(crumbs)}
    {updated_html(last_run)}
    {counts}
    {intro}
    {note}
    {DISCLAIMER}
    {toc}
    {grouped_cards(mine, by_phase=False, agent_links=agent_links)}
    {faq_html(faq)}
    {substack_html()}
    {cite_html(url, title, last_run)}
    <p class="updated-line">Related: <a href="/trials/{slug}-recruiting.html">recruiting {esc(name)} trials</a> · <a href="{esc(cfg['hub'])}">{esc(name)} research hub</a> · <a href="/clinical_trials.html">interactive trial finder</a>.</p>
  </div>
</main>
"""
    graph = [
        collection_ld(url, title, description, last_run, {"@type": "MedicalCondition", "name": cfg["key"]}),
        breadcrumb_ld(crumbs),
        faq_ld(faq),
        itemlist_ld(title, mine, cfg["key"]),
        dataset_ld(last_run),
    ]
    return page(title, description, url, body, graph), len(mine)


def build_agent_page(agent, aslug, trials, last_run, agent_links):
    url = f"{SITE}/trials/by-agent/{aslug}.html"
    my = month_year(last_run)
    mine = sorted(sorted(trials, key=_recency, reverse=True), key=lambda x: status_key(x["status"]))
    sc = Counter(t["status"] for t in mine)
    conds = Counter(c for t in mine for c in t["mapped_conditions"])
    n_open = sum(sc.get(s, 0) for s in OPEN_STATUSES)
    n_done = sc.get("COMPLETED", 0)
    title = f"{agent} clinical trials for Long COVID, ME/CFS and post-viral illness ({len(mine)} trials, updated {my})"
    cond_text = ", ".join(f"{c} ({n})" for c, n in conds.most_common())
    description = f"{len(mine)} ClinicalTrials.gov trials testing {agent} in {cond_text}: {n_open} open to enrolment, {n_done} completed. Status, phase, sponsor and summaries, updated {my}."
    profile = AGENT_PAGES_DIR / aslug / "index.html"
    profile_link = f' Read the <a href="/agents/{aslug}/">OSMF evidence profile for {esc(agent)}</a> for literature, mechanism and dosing context.' if profile.exists() else ""
    intro = f"""<div class="trials-intro">
<p>All interventional trials in our ClinicalTrials.gov extract that list <strong>{esc(agent)}</strong> as an intervention, across {esc(cond_text)}. {n_open} {'is' if n_open == 1 else 'are'} currently open to enrolment and {n_done} {'has' if n_done == 1 else 'have'} completed.{profile_link}</p>
<p>Intervention names are normalised from the registry's own arm labels, so the same compound can appear under a brand name, a generic name or a combination; check the <a href="/trials/by-agent/index.html">full agent index</a> for related entries.</p>
</div>"""
    counts = counts_html([("trials", len(mine)), ("open to enrolment", n_open)] + [(status_label(st).lower(), sc[st]) for st in STATUS_ORDER if sc.get(st) and st not in OPEN_STATUSES])
    faq = [COMMON_FAQ[0], COMMON_FAQ[1], COMMON_FAQ[3]]
    crumbs = [("Research Tracker", f"{SITE}/"), ("Clinical trials", f"{SITE}/trials/index.html"), ("By agent", f"{SITE}/trials/by-agent/index.html"), (agent, url)]
    finder_hash = "#agent=" + quote(agent, safe="")
    body = f"""
<section class="page-hero trials-hero">
  <div class="hero-eyebrow">Trials by therapeutic agent</div>
  <h1>{esc(agent)} <span>clinical trials</span></h1>
  <p>{len(mine)} post-viral trials on ClinicalTrials.gov · updated {esc(my)}</p>
</section>
<main class="main-section">
  <div class="section-inner">
    {breadcrumb_html(crumbs)}
    {updated_html(last_run)}
    {counts}
    {intro}
    {DISCLAIMER}
    {grouped_cards(mine, by_phase=False, show_conditions=True, agent_links=agent_links)}
    {faq_html(faq)}
    {substack_html()}
    {cite_html(url, title, last_run)}
    <p class="updated-line">Related: <a href="/trials/by-agent/index.html">all agents</a> · <a href="/trials/long-covid-recruiting.html">recruiting Long COVID trials</a> · <a href="/trials/me-cfs-recruiting.html">recruiting ME/CFS trials</a> · <a href="/clinical_trials.html{finder_hash}">open in trial finder</a>.</p>
  </div>
</main>
"""
    is_drug = any(clean(t.get("phase")) not in ("", "NA") for t in mine)
    graph = [
        collection_ld(url, title, description, last_run, {"@type": "Drug" if is_drug else "MedicalTherapy", "name": agent}),
        breadcrumb_ld(crumbs),
        faq_ld(faq),
        itemlist_ld(title, mine),
        dataset_ld(last_run),
    ]
    return page(title, description, url, body, graph)


def build_agent_index(agent_rows, last_run, n_total_agents):
    url = f"{SITE}/trials/by-agent/index.html"
    my = month_year(last_run)
    title = f"Post-viral clinical trials by therapeutic agent ({len(agent_rows)} agents, updated {my})"
    description = f"Index of {len(agent_rows)} drugs, supplements, devices and therapies tested in two or more Long COVID, ME/CFS or post-viral clinical trials, with trial counts and links to each agent's trial list."
    rows = sorted(agent_rows, key=lambda r: (-r["n"], r["agent"].lower()))
    grid = '<div class="agent-grid">' + "".join(
        f'<a href="/trials/by-agent/{r["slug"]}.html"><strong>{esc(r["agent"])}</strong><span>{r["n"]} trials · {r["open"]} open</span></a>' for r in rows
    ) + "</div>"
    crumbs = [("Research Tracker", f"{SITE}/"), ("Clinical trials", f"{SITE}/trials/index.html"), ("By agent", url)]
    body = f"""
<section class="page-hero trials-hero">
  <div class="hero-eyebrow">Trials by therapeutic agent</div>
  <h1>Post-viral trials <span>by agent</span></h1>
  <p>{len(agent_rows)} interventions tested in two or more trials · updated {esc(my)}</p>
</section>
<main class="main-section">
  <div class="section-inner">
    {breadcrumb_html(crumbs)}
    {updated_html(last_run)}
    <div class="trials-intro"><p>Each page lists every Long COVID, ME/CFS and post-viral-overlap trial in our ClinicalTrials.gov extract that tests the named intervention, with status badges so you can see at a glance whether a treatment is still being studied, has completed, or was stopped. Interventions that appear in only one trial ({n_total_agents - len(agent_rows)} of {n_total_agents} distinct intervention strings) are searchable in the <a href="/clinical_trials.html">interactive trial finder</a>. Placebo, saline and usual-care comparator arms are excluded here.</p></div>
    {DISCLAIMER}
    {grid}
    {substack_html()}
    {cite_html(url, title, last_run)}
  </div>
</main>
"""
    graph = [
        collection_ld(url, title, description, last_run),
        breadcrumb_ld(crumbs),
        {"@type": "ItemList", "name": title, "numberOfItems": len(rows),
         "itemListElement": [{"@type": "ListItem", "position": i + 1, "name": r["agent"], "url": f"{SITE}/trials/by-agent/{r['slug']}.html"} for i, r in enumerate(rows)]},
        dataset_ld(last_run),
    ]
    return page(title, description, url, body, graph)


def build_hub(stats, agent_rows, last_run, trials):
    url = f"{SITE}/trials/index.html"
    my = month_year(last_run)
    n = len(trials)
    n_open = sum(1 for t in trials if t["status"] in OPEN_STATUSES)
    title = f"Long COVID, ME/CFS and post-viral clinical trials ({n} trials, updated {my})"
    description = f"Static index of {n} interventional trials for Long COVID / PASC, ME/CFS and overlapping post-viral conditions from ClinicalTrials.gov: {n_open} currently open to enrolment, plus complete lists and per-agent pages."
    cards = []
    for slug, cfg in CONDITIONS.items():
        s = stats[slug]
        cards.append(f"""<div class="hub-card"><div class="n">{s['open']}</div><h3><a href="/trials/{slug}-recruiting.html">Recruiting {esc(cfg['name'])} trials</a></h3><p>Trials currently recruiting, not yet recruiting or enrolling by invitation, grouped by status and phase.</p><p style="margin-top:0.5rem"><a href="/trials/all-{slug}.html">All {s['all']} {esc(cfg['name'])} trials (any status) →</a></p></div>""")
    top = sorted(agent_rows, key=lambda r: (-r["n"], r["agent"].lower()))[:6]
    cards.append(f"""<div class="hub-card"><div class="n">{len(agent_rows)}</div><h3><a href="/trials/by-agent/index.html">Trials by therapeutic agent</a></h3><p>One page per intervention tested in two or more trials. Most trialled: {esc(', '.join(r['agent'] for r in top))}.</p></div>""")
    cards.append(f"""<div class="hub-card"><div class="n">{n}</div><h3><a href="/clinical_trials.html">Interactive trial finder</a></h3><p>Filter all {n} trials by condition, status, phase, sponsor type and agent, with free-text search and shareable links.</p></div>""")
    sc = Counter(t["status"] for t in trials)
    counts = counts_html([("trials tracked", n), ("open to enrolment", n_open)] + [(status_label(st).lower(), sc[st]) for st in ("COMPLETED", "ACTIVE_NOT_RECRUITING", "TERMINATED", "UNKNOWN") if sc.get(st)])
    crumbs = [("Research Tracker", f"{SITE}/"), ("Clinical trials", url)]
    faq = [COMMON_FAQ[0], COMMON_FAQ[3], COMMON_FAQ[4], COMMON_FAQ[5]]
    body = f"""
<section class="page-hero trials-hero">
  <div class="hero-eyebrow">Clinical trials index</div>
  <h1>Post-viral <span>clinical trials</span></h1>
  <p>Long COVID, ME/CFS and overlapping post-viral conditions · {n} trials · updated {esc(my)}</p>
</section>
<main class="main-section">
  <div class="section-inner">
    {breadcrumb_html(crumbs)}
    {updated_html(last_run)}
    {counts}
    <div class="trials-intro"><p>These pages are rebuilt automatically from ClinicalTrials.gov so that patients, clinicians and researchers can see which post-viral trials are open right now, which have finished, and which interventions have been tested. Each trial links directly to its registry record. OSMF does not run any of these trials.</p></div>
    <div class="hub-grid">{''.join(cards)}</div>
    {DISCLAIMER}
    {faq_html(faq)}
    {substack_html()}
    {cite_html(url, title, last_run)}
  </div>
</main>
"""
    graph = [
        collection_ld(url, title, description, last_run),
        breadcrumb_ld(crumbs),
        faq_ld(faq),
        dataset_ld(last_run),
    ]
    return page(title, description, url, body, graph)


# ----------------------------------------------------------------------------
# main
# ----------------------------------------------------------------------------
def load_trials(source: Path):
    with open(source, encoding="utf-8") as f:
        data = json.load(f)
    trials = []
    seen = set()
    for t in data.get("trials", []):
        nct = clean(t.get("nct_id"))
        if not nct or nct in seen:
            continue
        seen.add(nct)
        t = dict(t)
        t["nct_id"] = nct
        t["status"] = clean(t.get("status")).upper() or "UNKNOWN"
        t["url"] = clean(t.get("link")) or f"https://clinicaltrials.gov/study/{nct}"
        t["agents"] = [clean(a) for a in (t.get("agents") or []) if clean(a)]
        t["mapped_conditions"] = [clean(c) for c in (t.get("mapped_conditions") or []) if clean(c)]
        t["conditions_raw"] = [clean(c) for c in (t.get("conditions_raw") or []) if clean(c)]
        t["summary"] = summarise(t.get("brief_summary"))
        trials.append(t)
    trials.sort(key=_recency, reverse=True)
    return data.get("last_run") or datetime.utcnow().isoformat(), trials


def write(path: Path, content: str):
    path.parent.mkdir(parents=True, exist_ok=True)
    old = path.read_text(encoding="utf-8") if path.exists() else None
    if old != content:
        path.write_text(content, encoding="utf-8", newline="\n")
        return True
    return False


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--source", type=Path, default=DEFAULT_SOURCE, help="path to clinical_trials_current.json")
    ap.add_argument("--min-agent-trials", type=int, default=2)
    args = ap.parse_args(argv)

    if not args.source.exists():
        print(f"ERROR: source not found: {args.source}", file=sys.stderr)
        return 1
    last_run, trials = load_trials(args.source)
    print(f"source: {args.source} ({len(trials)} trials, last_run {last_run})")

    # agents with >= N trials (excluding comparator noise)
    agent_trials = defaultdict(list)
    for t in trials:
        for a in sorted(set(t["agents"])):
            if NOISE_AGENT_RE.search(a):
                continue
            agent_trials[a].append(t)
    n_total_agents = len(agent_trials)
    eligible = {a: ts for a, ts in agent_trials.items() if len(ts) >= args.min_agent_trials}
    # resolve slug collisions deterministically
    slug_of, used = {}, {}
    for a in sorted(eligible, key=lambda s: (-len(eligible[s]), s.lower())):
        s = slugify(a)
        if s in used:
            i = 2
            while f"{s}-{i}" in used:
                i += 1
            s = f"{s}-{i}"
        used[s] = a
        slug_of[a] = s

    written = changed = 0

    def emit(path, content):
        nonlocal written, changed
        written += 1
        if write(path, content):
            changed += 1

    stats = {}
    for slug, cfg in CONDITIONS.items():
        html_out, n_open = build_recruiting_page(slug, cfg, trials, last_run, slug_of)
        emit(OUT_DIR / f"{slug}-recruiting.html", html_out)
        html_out, n_all = build_all_page(slug, cfg, trials, last_run, slug_of)
        emit(OUT_DIR / f"all-{slug}.html", html_out)
        stats[slug] = {"open": n_open, "all": n_all}
        print(f"  {cfg['name']}: {n_open} open / {n_all} total")

    agent_rows = []
    for a in sorted(eligible, key=lambda s: slug_of[s]):
        ts = eligible[a]
        aslug = slug_of[a]
        emit(AGENT_DIR / f"{aslug}.html", build_agent_page(a, aslug, ts, last_run, slug_of))
        agent_rows.append({"agent": a, "slug": aslug, "n": len(ts), "open": sum(1 for t in ts if t["status"] in OPEN_STATUSES)})
    emit(AGENT_DIR / "index.html", build_agent_index(agent_rows, last_run, n_total_agents))
    print(f"  by-agent: {len(agent_rows)} agents with >= {args.min_agent_trials} trials (of {n_total_agents} distinct non-comparator agents)")

    emit(OUT_DIR / "index.html", build_hub(stats, agent_rows, last_run, trials))

    # remove stale generated agent pages
    keep = {f"{s}.html" for s in slug_of.values()} | {"index.html"}
    removed = 0
    if AGENT_DIR.exists():
        for p in AGENT_DIR.glob("*.html"):
            if p.name not in keep:
                try:
                    if MARKER in p.read_text(encoding="utf-8", errors="ignore"):
                        p.unlink()
                        removed += 1
                except OSError:
                    pass
    print(f"done: {written} pages generated, {changed} changed, {removed} stale by-agent pages removed -> {OUT_DIR}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
