"""Generate app/gene_therapy_repurpos.py from the OSMF disease-intelligence data.

Why baked, not read at runtime: the disease-intelligence JSONs live at the repo root
(data/disease-intelligence/), but Render deploys only med-freedom-map/backend/. So we
extract a compact top-N of ranked candidates here (dev) and commit the result, which the
API imports with zero runtime file dependency or free-tier memory cost.

Re-run after the disease-intelligence data updates:
    cd med-freedom-map/backend && python scripts/build_gene_therapy_repurpos.py

Maps each gene-therapy disease id -> disease-intelligence slug. Add rows to SLUG_MAP as
more monogenic diseases get intelligence pages.
"""
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
# repo root = .../research-tracker ; backend = .../med-freedom-map/backend
REPO_ROOT = os.path.abspath(os.path.join(HERE, "..", "..", ".."))
DI_DIR = os.path.join(REPO_ROOT, "data", "disease-intelligence")
OUT = os.path.join(HERE, "..", "app", "gene_therapy_repurpos.py")
CANONICAL = "https://research.opensourcemed.info/disease-intelligence/{slug}.html"
TOP_N = 8

# gene-therapy entry id  ->  disease-intelligence slug.
# Only map to a page for the SAME disease — do not borrow a sibling's candidates
# (e.g. beta-thalassemia must not show sickle-cell candidates). Add rows as the
# disease-intelligence set gains pages for more monogenic diseases.
SLUG_MAP = {
    "scd": "sickle-cell-disease",
    "beta-thal": "beta-thalassemia",
    "hemophilia-a": "hemophilia",
    "hemophilia-b": "hemophilia",
    "cf": "cystic-fibrosis",
}


def _best_link(cand):
    for pref in ("Open Targets", "ChEMBL"):
        for l in cand.get("external_links") or []:
            if l.get("label") == pref:
                return l.get("url")
    links = cand.get("external_links") or []
    return links[0]["url"] if links else None


def extract(slug):
    path = os.path.join(DI_DIR, f"{slug}.json")
    if not os.path.exists(path):
        return None
    with open(path, encoding="utf-8") as f:
        d = json.load(f)
    ranked = (d.get("therapeutics") or {}).get("merged_ranked") or []
    cands = []
    for c in ranked[:TOP_N]:
        cands.append({
            "name": (c.get("name") or "").title(),
            "drug_type": c.get("drug_type_label"),
            "phase": c.get("phase_label"),
            "evidence": c.get("evidence_tier_label"),
            "repurposing": bool(c.get("repurposing_signal")),
            "score": c.get("score"),
            "url": _best_link(c),
        })
    counts = (d.get("summary") or {}).get("therapeutic_counts") or {}
    return {
        "slug": slug,
        "url": CANONICAL.format(slug=slug),
        "condition": (d.get("condition") or {}).get("name"),
        "candidate_total": counts.get("merged"),
        "candidates": cands,
    }


def main():
    out = {}
    for gt_id, slug in SLUG_MAP.items():
        data = extract(slug)
        if data:
            out[gt_id] = data
            print(f"  {gt_id:16s} -> {slug} ({len(data['candidates'])} shown / {data['candidate_total']} total)")
        else:
            print(f"  {gt_id:16s} -> {slug} (MISSING JSON, skipped)")

    header = (
        '"""AUTO-GENERATED by scripts/build_gene_therapy_repurpos.py — do not edit by hand.\n'
        'Compact top-N repurposing/management candidates per gene-therapy disease, sourced\n'
        'from the OSMF disease-intelligence (RepurpOS) dataset. Re-run the script to refresh.\n'
        '"""\n'
        'import json\n\n'
    )
    # Embed as a JSON string parsed at import time -> guaranteed-valid Python
    # (avoids emitting JSON's false/true/null as bare names).
    payload = json.dumps(out, ensure_ascii=False)
    body = "REPURPOS = json.loads(r'''" + payload + "''')\n"
    with open(OUT, "w", encoding="utf-8") as f:
        f.write(header + body)
    print(f"Wrote {os.path.relpath(OUT, REPO_ROOT)} with {len(out)} diseases.")


if __name__ == "__main__":
    main()
